# docker stack deploy -c stack.yml jupyter
# optional pgadmin container
version: "3.7"
networks:
    demo-net:
services:
  spark:
    image: f22-spark-notebook:latest
    ports:
      - "8888:8888/tcp"
      - "4040:4040/tcp"
    networks:
      - demo-net
    working_dir: /home/jovyan/work
    environment:
      CHOWN_HOME: "yes"
      GRANT_SUDO: "yes"
      NB_UID: 1000
      NG_GID: 100
      NB_USER: jovyan
      NB_GROUP: staff
      ENVIRONMENT: ${ENVIRONMENT}
    user: root
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
    - ..\..\:/home/jovyan/work
    - C:\Users\Chris\workspaces\data\:/home/jovyan/work/data
    - D:\workspaces\data\:/home/jovyan/overflow_workspace/data
