version: '2.1'

services:
  zookeeper-server:
    image: 'zookeeper:3.4.9'
    ports:
      - '2181:2181'
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper-server:2888:3888
    volumes:
      - C:\Users\Chris\workspaces\data\kafka\zk-data:/var/lib/zookeeper/data
      - C:\Users\Chris\workspaces\data\kafka\zk-txn-logs:/var/lib/zookeeper/log
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:19092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka"
  kafka:
    image: confluentinc/cp-kafka:5.5.1
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://127.0.0.1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-server:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper-server
    volumes:
      - C:\Users\Chris\workspaces\data\kafka\kafka-data:/var/lib/kafka/data
#  kafka-server2:
#    image: 'bitnami/kafka:latest'
#    networks:
#      - kafka-net
#    ports:
#      - '9093:9092'
#    environment:
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9093
#      - ALLOW_PLAINTEXT_LISTENER=yes
#    depends_on:
#      - zookeeper-server