# 39th day; top rev prev year: .0038
# 29th day; top rev prev year: 0.0022
stock_dict_top_rev = dict(
    _2016=['AAPL', 'TM', 'MCK', 'ABC', 'COST', 'HMC', 'KR', 'WBA', 'CAH', 'MSFT', 'NTTYY', 'JXHLY', 'PG', 'SNE', 'PEP', 'VOD', 'INTC', 'DIS', 'HPQ', 'CSCO',
           'SYY', 'FDX',
           'BHP', 'TTM', 'MUFG', 'TSN', 'ORCL', 'DCMYY', 'SNEX', 'S', 'ACN', 'HPE', 'NKE', 'TFCF', 'DE', 'SMFG', 'RY', 'BTTGY', 'RAD', 'FLEX', 'QCOM', 'MFG',
           'TD', 'MDT',
           'ADNT', 'NGG', 'SBUX', 'DXC', 'BNS', 'IX', 'ACM', 'JBL', 'AVT', 'GIS', 'JCI', 'DEO', 'NGL', 'EMR', 'MU', 'CCL', 'WFM', 'PFGC', 'SSL', 'WBK', 'MON',
           'BMO',
           'WDC', 'IBN', 'ARMK', 'KMX', 'V', 'STX', 'NMR', 'SNX', 'SVU', 'VIAB', 'KYOCY', 'PH', 'BABA', 'TEL', 'J', 'BBBY', 'CSX', 'ODP', 'VEDL', 'WRK', 'ADP',
           'DHI',
           'EL', 'HSIC', 'CM', 'BDX', 'AZO', 'NAV', 'PCP', 'TYC', 'AMAT', 'LEN', 'HRL', 'CAG'],
    _2017=['WMT', 'TM', 'AAPL', 'MCK', 'ABC', 'CAH', 'COST', 'HMC', 'WBA', 'KR', 'NTTYY', 'MSFT', 'HD', 'TGT', 'SNE', 'PG', 'LOW', 'PEP', 'JXHLY', 'INTC',
           'DELL', 'FDX',
           'ACI', 'VOD', 'SYY', 'DIS', 'HPQ', 'CSCO', 'DCMYY', 'TTM', 'BBY', 'TSN', 'ORCL', 'ACN', 'BHP', 'NKE', 'S', 'TJX', 'RY', 'SMFG', 'BTTGY', 'DE', 'MDT',
           'SNEX',
           'HPE', 'MUFG', 'TFCF', 'TD', 'KHC', 'M', 'TECD', 'IX', 'USFD', 'FLEX', 'BABA', 'RAD', 'JCI', 'SBUX', 'QCOM', 'SHLDQ', 'DG', 'BNS', 'DLTR', 'MU',
           'MFG', 'KSS',
           'WDC', 'JBL', 'NGG', 'V', 'SPLS', 'ACM', 'AVGO', 'CCL', 'IBN', 'AVT', 'BMO', 'WBK', 'SNX', 'PFGC', 'ADNT', 'DEO', 'KMX', 'TAK', 'GIS', 'GPS', 'EMR',
           'WRK',
           'JWN', 'AMAT', 'MON', 'ARMK', 'TXT', 'DHI', 'VIAB', 'SSL', 'SWK', 'JCPNQ', 'ROST', 'K'],
    _2018=['WMT', 'AAPL', 'TM', 'MCK', 'ABC', 'COST', 'CAH', 'HMC', 'WBA', 'KR', 'MSFT', 'HD', 'JNJ', 'DELL', 'SNE', 'TGT', 'INTC', 'LOW', 'PG', 'FDX', 'VOD',
           'PEP',
           'ACI', 'DIS', 'SYY', 'HPQ', 'CSCO', 'TTM', 'BHP', 'BBY', 'ACN', 'TSN', 'BABA', 'ORCL', 'MUFG', 'DE', 'NKE', 'TJX', 'TECD', 'BTTGY', 'SMFG', 'RY', 'S',
           'HPE',
           'TFCF', 'MU', 'MDT', 'TD', 'SNEX', 'KHC', 'FLEX', 'IX', 'M', 'SBUX', 'USFD', 'DG', 'JCI', 'MFG', 'QCOM', 'DLTR', 'JBL', 'BNS', 'DXC', 'RAD', 'NGG',
           'AVGO',
           'WDC', 'V', 'LEN', 'KSS', 'SNX', 'AVT', 'CCL', 'IBN', 'PFGC', 'BMO', 'ADNT', 'EMR', 'KMX', 'AMAT', 'SHLDQ', 'WRK', 'DEO', 'DHI', 'BDX', 'GPS', 'WBK',
           'ARMK',
           'GIS', 'TAK', 'JWN', 'PH', 'SVU', 'ROST', 'TEL', 'SWK', 'TXT', 'VEDL', 'ACM', 'KYOCY'],
    _2019=['WMT', 'AAPL', 'TM', 'MCK', 'ABC', 'COST', 'CAH', 'HMC', 'WBA', 'KR', 'MSFT', 'HD', 'JNJ', 'DELL', 'SNE', 'TGT', 'INTC', 'LOW', 'PG', 'FDX', 'VOD',
           'PEP',
           'ACI', 'DIS', 'SYY', 'HPQ', 'CSCO', 'TTM', 'BHP', 'BBY', 'ACN', 'TSN', 'BABA', 'ORCL', 'MUFG', 'DE', 'NKE', 'TJX', 'TECD', 'BTTGY', 'SMFG', 'RY', 'S',
           'HPE',
           'TFCF', 'MU', 'MDT', 'TD', 'SNEX', 'KHC', 'FLEX', 'IX', 'M', 'SBUX', 'USFD', 'DG', 'JCI', 'MFG', 'QCOM', 'DLTR', 'JBL', 'BNS', 'DXC', 'RAD', 'NGG',
           'AVGO',
           'WDC', 'V', 'LEN', 'KSS', 'SNX', 'AVT', 'CCL', 'IBN', 'PFGC', 'BMO', 'ADNT', 'EMR', 'KMX', 'AMAT', 'SHLDQ', 'WRK', 'DEO', 'DHI', 'BDX', 'GPS', 'WBK',
           'ARMK',
           'GIS', 'TAK', 'JWN', 'PH', 'SVU', 'ROST', 'TEL', 'SWK', 'TXT', 'VEDL', 'ACM', 'KYOCY'],
    _2020=['WMT', 'TM', 'AAPL', 'MCK', 'ABC', 'COST', 'CAH', 'HMC', 'WBA', 'MSFT', 'KR', 'HD', 'DELL', 'JNJ', 'SNE', 'TGT', 'INTC', 'LOW', 'FDX', 'DIS', 'PG',
           'PEP',
           'ACI', 'SYY', 'HPQ', 'VOD', 'BABA', 'CSCO', 'BHP', 'TTM', 'ACN', 'BBY', 'TSN', 'ORCL', 'DE', 'NKE', 'TJX', 'TECD', 'RY', 'MUFG', 'S', 'SNEX', 'TD',
           'BTTGY',
           'MDT', 'HPE', 'SMFG', 'SBUX', 'FLEX', 'USFD', 'DG', 'JBL', 'KHC', 'M', 'QCOM', 'JCI', 'SNX', 'BNS', 'MU', 'V', 'DLTR', 'AVGO', 'UNFI', 'LEN', 'IX',
           'RAD',
           'CCL', 'DXC', 'KSS', 'NGG', 'PFGC', 'AVT', 'BMO', 'TAK', 'IBN', 'MFG', 'EMR', 'WRK', 'KMX', 'DHI', 'BDX', 'GIS', 'GPS', 'WDC', 'ADNT', 'DEO', 'ARMK',
           'JWN',
           'ROST', 'EL', 'AMAT', 'SSL', 'SWK', 'PH', 'CM', 'ADP', 'WBK', 'ACM', 'K', 'TEL'],
    _2021=['WMT', 'TM', 'AAPL', 'MCK', 'ABC', 'COST', 'CAH', 'MSFT', 'WBA', 'HMC', 'KR', 'HD', 'DELL', 'TGT', 'SNE', 'BABA', 'LOW', 'PG', 'FDX', 'DIS', 'ACI',
           'VOD',
           'SYY', 'CSCO', 'ACN', 'BBY', 'TSN', 'BHP', 'TJX', 'ORCL', 'NKE', 'TECD', 'RY', 'MUFG', 'TTM', 'TD', 'TAK', 'MDT', 'BTTGY', 'DG', 'JBL', 'UNFI',
           'PFGC', 'SMFG',
           'M', 'FLEX', 'BNS', 'DLTR', 'QCOM', 'SBUX', 'JCI', 'RAD', 'V', 'MU', 'IX', 'KMX', 'DHI', 'KSS', 'IBN', 'DXC', 'BMO', 'MFG', 'NGG', 'AVT', 'GIS',
           'WRK', 'BDX',
           'CRM', 'EMR', 'WDC', 'GPS', 'ROST', 'JWN', 'DEO', 'WBK', 'ADP', 'CM', 'EL', 'PH', 'TXT', 'J', 'ACM', 'BJ', 'LB', 'ARMK', 'INFY', 'ADNT', 'AZO',
           'AMCR', 'FOXA',
           'TEL', 'NMR', 'BERY', 'JCPNQ', 'BBBY', 'LDOS', 'VEDL', 'CAG', 'SSL', 'NVDA'])

# Bottom pe and untradable
stock_dict_bottom_pe_untradeable = dict(
    _2016=['FRTG', 'VSAT', 'CSII', 'SHAK', 'XTEG', 'CVLT', 'AXR', 'STZ', 'PCYG', 'PLT', 'MANU', 'XTEG', 'XTEG', 'ELEC', 'CYAN', 'GSIT', 'GEOS', 'GCI', 'MTRX', 'LCI',
           'INVN', 'OMN', 'MIME', 'NEWM', 'ELEC', 'MXC', 'NTCT', 'GHM', 'ENR', 'CSII', 'EXTR', 'PCTY', 'CUB', 'CCN', 'MITK', 'VRTU', 'QRVO', 'NMRD', 'FC', 'HBK', 'DLNO',
           'ARCW', 'LITE', 'HRB', 'RENT', 'KMT', 'MIME', 'PRCP', 'KTOS', 'LPG', 'TTWO', 'GWRE', 'ATGE', 'FORM', 'DAKT', 'CVLT', 'IDTI', 'NMRD', 'MOD', 'HQI', 'DJCO',
           'NUAN', 'SCHL', 'CCUR', 'MG', 'AMD', 'NX', 'TAL', 'EGHT', 'PINC', 'DJCO', 'PTC', 'SPGX', 'NGL', 'TNAV', 'ECEZ', 'PZZA', 'PANW', 'SKIS', 'GWRE', 'AJRD', 'ASH',
           'EPAY', 'QRVO', 'NMRD', 'SRDX', 'MIME', 'JVA', 'QRVO', 'VOXX', 'CGNT', 'PRCP', 'EGAN', 'MJCO', 'TEAM', 'ENZ', 'MLAB', 'PAY', 'AGTC', 'EEI'],
    _2017=['FRTG', 'IINX', 'VSAT', 'CSII', 'SHAK', 'XTEG', 'CVLT', 'AXR', 'STZ', 'PCYG', 'PLT', 'MANU', 'XTEG', 'XTEG', 'ELEC', 'CYAN', 'NXEO', 'PRMW', 'GSIT', 'GEOS',
           'GCI', 'MTRX', 'LCI', 'INVN', 'OMN', 'MIME', 'PHUN', 'NEWM', 'CRM', 'ELEC', 'MXC', 'RH', 'NTCT', 'GHM', 'ENR', 'CSII', 'EXTR', 'PCTY', 'CUB', 'MITK', 'VRTU',
           'QRVO', 'NMRD', 'FC', 'HBK', 'DLNO', 'ARCW', 'LITE', 'HRB', 'KMT', 'MIME', 'PRCP', 'KTOS', 'VRNT', 'LPG', 'ADSK', 'TTWO', 'GWRE', 'GWPH', 'PRMW', 'ATGE',
           'DAKT', 'CVLT', 'IDTI', 'KHC', 'NMRD', 'MOD', 'HQI', 'DJCO', 'NUAN', 'SCHL', 'CCUR', 'NX', 'ARWA', 'STAA', 'TAL', 'EGHT', 'PINC', 'DJCO', 'PTC', 'SPGX', 'NGL',
           'TNAV', 'ECEZ', 'PZZA', 'PANW', 'SKIS', 'GWRE', 'ASH', 'EPAY', 'QRVO', 'NMRD', 'CAL', 'FOSL', 'SRDX', 'MIME', 'JVA', 'QRVO', 'VOXX', 'PRCP'],
    _2018=['FRTG', 'IINX', 'VSAT', 'CSII', 'SHAK', 'XTEG', 'CVLT', 'AXR', 'STZ', 'PCYG', 'PLT', 'MANU', 'XTEG', 'XTEG', 'ELEC', 'CYAN', 'NXEO', 'PRMW', 'GSIT', 'GEOS',
           'MTRX', 'LCI', 'OMN', 'MIME', 'CRM', 'ELEC', 'MXC', 'RH', 'NTCT', 'GHM', 'ENR', 'CSII', 'EXTR', 'PCTY', 'CUB', 'MITK', 'SGH', 'VRTU', 'QRVO', 'NMRD', 'FC',
           'HBK', 'DLNO', 'ARCW', 'LITE', 'HRB', 'KMT', 'MIME', 'PRCP', 'VRNT', 'LPG', 'ADSK', 'TTWO', 'GWRE', 'GWPH', 'PRMW', 'ATGE', 'FORM', 'DAKT', 'CVLT', 'IDTI',
           'KHC', 'NMRD', 'MOD', 'HQI', 'DJCO', 'NUAN', 'SCHL', 'CCUR', 'AMD', 'NX', 'STAA', 'TAL', 'EGHT', 'PINC', 'DJCO', 'PTC', 'SPGX', 'NGL', 'TNAV', 'ECEZ', 'PANW',
           'SKIS', 'GWRE', 'ASH', 'EPAY', 'QRVO', 'NMRD', 'CAL', 'FOSL', 'SRDX', 'MIME', 'JVA', 'QRVO', 'VOXX', 'PRCP', 'ITGR', 'EGAN', 'AQUA', 'MJCO'],
    _2019=['FAT', 'FRTG', 'IINX', 'VSAT', 'HCCH', 'WINR', 'CSII', 'SHAK', 'XTEG', 'CVLT', 'AXR', 'STZ', 'PCYG', 'PLT', 'MANU', 'XTEG', 'XTEG', 'CYAN', 'NXEO', 'PRMW',
           'IIIV', 'GSIT', 'GEOS', 'MTRX', 'LCI', 'OMN', 'MIME', 'NEWM', 'CRM', 'MXC', 'RH', 'NTCT', 'GHM', 'ENR', 'CSII', 'EXTR', 'PCTY', 'CUB', 'MITK', 'SGH', 'VRTU',
           'QRVO', 'NMRD', 'FC', 'HBK', 'ARCW', 'LITE', 'HRB', 'KMT', 'MIME', 'PRCP', 'KTOS', 'VRNT', 'LPG', 'ADSK', 'HCCH', 'TTWO', 'ZS', 'GWRE', 'GWPH', 'PRMW', 'ATGE',
           'FORM', 'DAKT', 'XTEG', 'CVLT', 'IDTI', 'KHC', 'NMRD', 'MOD', 'HQI', 'DJCO', 'NUAN', 'QTNA', 'SCHL', 'CCUR', 'SONO', 'AMD', 'NX', 'STAA', 'TAL', 'EGHT', 'PINC',
           'DJCO', 'PTC', 'NGL', 'TNAV', 'PZZA', 'PANW', 'SKIS', 'GWRE', 'ASH', 'EPAY', 'QRVO', 'NMRD', 'CAL', 'FOSL', 'SRDX', 'MIME', 'JVA'],
    _2020=['FAT', 'IINX', 'VSAT', 'HCCH', 'WINR', 'CSII', 'SHAK', 'XTEG', 'CVLT', 'LOAC', 'AXR', 'STZ', 'PCYG', 'PLT', 'MANU', 'XTEG', 'XTEG', 'CYAN', 'PRMW', 'IIIV',
           'GSIT', 'GEOS', 'MTRX', 'LCI', 'OMN', 'MIME', 'CRM', 'MXC', 'LAAB', 'RH', 'TMRR', 'NTCT', 'GHM', 'ENR', 'CSII', 'EXTR', 'PCTY', 'CUB', 'MITK', 'SGH', 'VRTU',
           'QRVO', 'NMRD', 'FC', 'TNCP', 'LITE', 'HRB', 'KMT', 'MIME', 'PRCP', 'KTOS', 'VRNT', 'LPG', 'ADSK', 'HCCH', 'TTWO', 'ZS', 'GWRE', 'PRMW', 'ATGE', 'FORM', 'DAKT',
           'XTEG', 'CVLT', 'KHC', 'NMRD', 'MOD', 'DJCO', 'NUAN', 'SCHL', 'CCUR', 'SONO', 'AMD', 'NX', 'TAL', 'EGHT', 'PINC', 'DJCO', 'PTC', 'NGL', 'TNAV', 'PZZA', 'PANW',
           'SKIS', 'GWRE', 'ASH', 'EPAY', 'QRVO', 'NMRD', 'CAL', 'FOSL', 'PTON', 'SRDX', 'MIME', 'JVA', 'QRVO', 'VOXX', 'PRCP', 'BILL', 'EGAN'],
    _2021=['IINX', 'VSAT', 'HCCH', 'WINR', 'CSII', 'CVLT', 'LOAC', 'AXR', 'STZ', 'PCYG', 'PLT', 'MANU', 'CYAN', 'IIIV', 'GSIT', 'BWMY', 'GEOS', 'MTRX', 'LCI', 'FEDU',
           'MIME', 'ECRP', 'CRM', 'MXC', 'LAAB', 'RH', 'LSAC', 'NTCT', 'GHM', 'ENR', 'CSII', 'EXTR', 'PCTY', 'CUB', 'SGH', 'VRTU', 'QRVO', 'NMRD', 'FC', 'TNCP', 'LITE',
           'HRB', 'KMT', 'MIME', 'PRCP', 'VRNT', 'LPG', 'ADSK', 'HCCH', 'TTWO', 'ZS', 'GWRE', 'ATGE', 'DAKT', 'CVLT', 'NMRD', 'MOD', 'NUAN', 'SCHL', 'CCUR', 'SONO',
           'STAA', 'TAL', 'EGHT', 'PINC', 'PTC', 'NGL', 'TNAV', 'PANW', 'GWRE', 'ASH', 'EPAY', 'QRVO', 'NMRD', 'CAL', 'PTON', 'SRDX', 'MIME', 'QRVO', 'VOXX', 'PRCP',
           'BILL', 'EGAN', 'AQUA', 'MJCO', 'TEAM', 'ENZ', 'EQOS', 'LOAC', 'MLAB', 'MTA', 'AGTC', 'LTRX', 'IIIV', 'NLOK', 'DRI', 'POST', 'EGHT', 'ANGO', 'DCT']
)

# 39th day; above 30 pe + tradeable; 0.0078
# 29th day; above 30 pe + tradeable; 0.0055
stock_dict_30pe_tradeable_1 = dict(
    _2016=['POST', 'BNED', 'CSC', 'ASH', 'CSCO', 'LRN', 'MTSI', 'RAD', 'TEAM', 'CVLT', 'PTC', 'CVLT', 'CRS', 'MLAB', 'CUB', 'EPC', 'ABM', 'NYT', 'MCK', 'CSII',
           'AVX',
           'VIAV', 'RAMP', 'PZZA', 'MPSX', 'ZOES', 'MYGN', 'BDX', 'LNN', 'NUAN', 'MCK', 'GWRE', 'BRC', 'GWRE', 'SJR', 'EGHT', 'ODP', 'ASEI', 'NXGN', 'PCTY',
           'LGF.B',
           'DECK', 'HAIN', 'GWRE', 'GWRE', 'CIEN', 'ZOES', 'MYCC', 'RAMP', 'PTC', 'MOG.A', 'RXN', 'LOGI', 'HABT', 'EPAY', 'AVAV', 'PRGO', 'EPAY', 'KRNY', 'FNSR',
           'DLB',
           'POST', 'VSAT', 'NXGN', 'CUB', 'AIR', 'NTAP', 'VSAT', 'KTOS', 'AMD', 'MSGN', 'PLAY', 'GIMO', 'CMD', 'PLXS', 'SPH', 'EZPW', 'AIR', 'NAV', 'CRS',
           'VRTU', 'HAE',
           'JJSF', 'GPN', 'KLIC', 'MNR', 'WING', 'SYY', 'CUDA', 'PCTY', 'MLAB', 'RGS', 'CALM', 'AIR', 'ABMD', 'ISLE', 'GGG', 'SHAK', 'HAIN', 'SHAK'],
    _2017=['TAST', 'WWW', 'POST', 'CSC', 'ASH', 'CSCO', 'LRN', 'MTSI', 'RAD', 'SUM', 'CRM', 'TEAM', 'CVLT', 'PTC', 'SUM', 'CVLT', 'CRS', 'CHS', 'MLAB', 'CUB',
           'EPC',
           'ABM', 'NYT', 'MCK', 'CSII', 'AVX', 'SUM', 'VIAV', 'IMBI', 'RAMP', 'PZZA', 'ZOES', 'HAWK', 'MYGN', 'BDX', 'LNN', 'NUAN', 'MCK', 'GWRE', 'BRC', 'GWRE',
           'SJR',
           'EGHT', 'ASEI', 'MRVL', 'NXGN', 'PCTY', 'LGF.B', 'DECK', 'HAIN', 'NORD', 'GWRE', 'GWRE', 'JNJ', 'CIEN', 'STAA', 'SUM', 'ZOES', 'MYCC', 'SLAB', 'RAMP',
           'LNCE',
           'COKE', 'PTC', 'MOG.A', 'RXN', 'ISIL', 'EBF', 'LOGI', 'CRM', 'HABT', 'EPAY', 'CY', 'AVAV', 'EPAY', 'ADSK', 'ANF', 'RH', 'ANF', 'ICHR', 'KRNY', 'FNSR',
           'DLB',
           'CRM', 'POST', 'VSAT', 'NXGN', 'CUB', 'CONN', 'AIR', 'NTAP', 'VSAT', 'ITGR', 'KTOS', 'MSGN', 'PLAY', 'CMD', 'PLXS', 'SPH', 'EZPW'],
    _2018=['WWW', 'POST', 'BNED', 'ASH', 'CSCO', 'LRN', 'MTSI', 'RAD', 'HLNE', 'WINS', 'COHU', 'SUM', 'CRM', 'TEAM', 'CVLT', 'PTC', 'SUM', 'CVLT', 'CRS', 'CHS',
           'MLAB',
           'CUB', 'EPC', 'ABM', 'MCK', 'CSII', 'PRMW', 'AVX', 'SUM', 'VIAV', 'IMBI', 'RAMP', 'ZOES', 'HAWK', 'MYGN', 'BDX', 'LNN', 'NUAN', 'MCK', 'GWRE', 'BRC',
           'GWRE',
           'SJR', 'EGHT', 'ODP', 'MRVL', 'NXGN', 'PCTY', 'LGF.B', 'DECK', 'HAIN', 'AQUA', 'GWRE', 'GWRE', 'CIEN', 'STAA', 'SUM', 'ZOES', 'SLAB', 'PSDO', 'RAMP',
           'LNCE',
           'PTC', 'MOG.A', 'RXN', 'LOGI', 'CRM', 'HABT', 'EPAY', 'AVAV', 'EPAY', 'ADSK', 'WINS', 'ANF', 'RH', 'ANF', 'ICHR', 'KRNY', 'FNSR', 'DLB', 'CRM',
           'POST', 'VSAT',
           'NXGN', 'CUB', 'CONN', 'AIR', 'NTAP', 'VSAT', 'ITGR', 'AMD', 'MSGN', 'PLAY', 'ACB', 'CMD', 'PLXS', 'SPH', 'EZPW', 'AIR', 'MITK'],
    _2019=['TAST', 'WWW', 'POST', 'BNED', 'ASH', 'CSCO', 'LRN', 'MTSI', 'SIGM', 'RAD', 'HLNE', 'COHU', 'SUM', 'CRM', 'TEAM', 'CVLT', 'PTC', 'SUM', 'CVLT', 'CRS',
           'CHS',
           'MLAB', 'CUB', 'EPC', 'ABM', 'NYT', 'MCK', 'CSII', 'PRMW', 'AVX', 'SUM', 'VIAV', 'IMBI', 'RAMP', 'PZZA', 'SRDX', 'MYGN', 'BDX', 'LNN', 'NUAN', 'MCK',
           'GWRE',
           'BRC', 'GWRE', 'SJR', 'EGHT', 'ODP', 'MRVL', 'NXGN', 'PCTY', 'LGF.B', 'DECK', 'HAIN', 'AQUA', 'GWRE', 'GWRE', 'JNJ', 'CIEN', 'STAA', 'CIVI', 'SUM',
           'SLAB',
           'PSDO', 'RAMP', 'COKE', 'PTC', 'MOG.A', 'RXN', 'LOGI', 'CRM', 'HABT', 'EPAY', 'CY', 'AVAV', 'EPAY', 'ADSK', 'ANF', 'RH', 'ANF', 'ICHR', 'KRNY',
           'FNSR', 'DLB',
           'DAVA', 'QTNA', 'CRM', 'POST', 'VSAT', 'NXGN', 'CUB', 'CONN', 'AIR', 'NTAP', 'VSAT', 'ITGR', 'KTOS', 'AMD', 'MSGN', 'PLAY', 'BGFV'],
    _2020=['TAST', 'WWW', 'POST', 'BNED', 'ASH', 'CSCO', 'EPAC', 'LRN', 'MTSI', 'RAD', 'HLNE', 'COHU', 'SUM', 'CRM', 'TEAM', 'CVLT', 'PTC', 'ZM', 'SUM', 'CVLT',
           'CRS',
           'CHS', 'MLAB', 'CUB', 'EPC', 'ABM', 'NYT', 'MCK', 'CSII', 'PRMW', 'MSGS', 'AVX', 'SUM', 'VIAV', 'IMBI', 'RAMP', 'PZZA', 'NLOK', 'SRDX', 'MYGN', 'BDX',
           'LNN',
           'NUAN', 'MCK', 'GWRE', 'BRC', 'GWRE', 'SJR', 'EGHT', 'ODP', 'MRVL', 'NXGN', 'PCTY', 'LGF.B', 'DECK', 'HAIN', 'AQUA', 'GWRE', 'GWRE', 'JNJ', 'CIEN',
           'SUM',
           'SLAB', 'PSDO', 'RAMP', 'COKE', 'PTC', 'MOG.A', 'RXN', 'LOGI', 'CRM', 'EPAY', 'CY', 'AVAV', 'EPAY', 'ADSK', 'ANF', 'RH', 'ANF', 'GO', 'ICHR', 'KRNY',
           'FNSR',
           'DLB', 'DAVA', 'CRM', 'POST', 'VSAT', 'NXGN', 'CUB', 'CONN', 'IFMK', 'AIR', 'BBW', 'NTAP', 'VSAT', 'KTOS', 'AMD', 'MSGN', 'PLAY'],
    _2021=['POST', 'BNED', 'ASH', 'CSCO', 'EPAC', 'LRN', 'MTSI', 'RAD', 'HLNE', 'CRM', 'TEAM', 'CVLT', 'PTC', 'ZM', 'CVLT', 'CRS', 'CHS', 'MLAB', 'CUB', 'EPC',
           'MCK',
           'CSII', 'MSGS', 'VIAV', 'RAMP', 'NLOK', 'SRDX', 'MYGN', 'BDX', 'LNN', 'NUAN', 'MCK', 'SMRTQ', 'GWRE', 'BRC', 'GWRE', 'SJR', 'EGHT', 'AVCT', 'MRVL',
           'NXGN',
           'PCTY', 'LGF.B', 'DECK', 'HAIN', 'AQUA', 'GWRE', 'GWRE', 'STAA', 'LAKE', 'RAMP', 'ELF', 'PTC', 'MOG.A', 'RXN', 'LOGI', 'CRM', 'AGTC', 'DGII', 'EPAY',
           'AVAV',
           'EPAY', 'ADSK', 'WINS', 'ANF', 'RH', 'ANF', 'KRNY', 'DLB', 'DAVA', 'CRM', 'POST', 'VSAT', 'NXGN', 'CUB', 'CONN', 'IFMK', 'AIR', 'BBW', 'NTAP', 'VSAT',
           'MSGN',
           'PLAY', 'ACB', 'CMD', 'PLXS', 'SPH', 'AIR', 'CRS', 'VRTU', 'VRNT', 'HAE', 'JJSF', 'VRNT', 'KLIC', 'MNR', 'TAK', 'MANU', 'SYY', 'PCTY']
)

# 39th day; High netinc; 0.0013
# 29th day; High netinc; 0.0010;
stock_dict_high_netinc = dict(
    _2016=['TLK', 'KEP', 'CIB', 'SHG', 'TM', 'KB', 'MUFG', 'SKM', 'LPL', 'SMFG', 'BCH', 'KT', 'NTTYY', 'HMC', 'BSAC', 'DCMYY', 'TSM', 'CAJ', 'PKX', 'CCU', 'TTM',
           'IBN', 'CHL', 'HDB', 'WIT', 'AAPL', 'MBT', 'CHT', 'PTR', 'NVO', 'LFC', 'BIDU', 'SNP', 'SSL', 'ITUB', 'BABA', 'BRK.B', 'WFC', 'JPM', 'RDY', 'PHI',
           'CEO', 'ASX', 'BBD', 'GILD', 'VZ', 'NVS', 'FMX', 'C', 'GOOGL', 'XOM', 'BAC', 'ERIC', 'HSBC', 'T', 'IBM', 'ABEV', 'MSFT', 'INTC', 'FNMA', 'TV', 'CHU',
           'KOF', 'ORCL', 'RY', 'GM', 'YNDX', 'SPIL', 'CSCO', 'GSK', 'DIS', 'TFCF', 'BUD', 'CMCSA', 'WBK', 'TD', 'DD', 'AAL', 'F', 'KO', 'UAL', 'MDLZ', 'PG',
           'BNS', 'PFE', 'AMGN', 'PM', 'NTES', 'FMCC', 'V', 'UBS', 'MS', 'GS', 'VOD', 'USB', 'UNH', 'PRU', 'PEP', 'MET', 'QCOM'],
    _2017=['TLK', 'KEP', 'CIB', 'SHG', 'EC', 'TM', 'KB', 'SKM', 'PKX', 'LPL', 'SMFG', 'MUFG', 'KT', 'NTTYY', 'BCH', 'DCMYY', 'BSAC', 'EOCCY', 'HMC', 'TSM', 'IX',
           'CAJ', 'SNE', 'CCU', 'HDB', 'CHL', 'IBN', 'TTM', 'NJDCY', 'WIT', 'BABA', 'MBT', 'SNP', 'AAPL', 'CHT', 'NVO', 'FMX', 'BRK.B', 'JPM', 'WFC', 'ITUB',
           'ASX', 'MSFT', 'RDY', 'PHI', 'GOOGL', 'LFC', 'BBD', 'BAC', 'JNJ', 'AGN', 'C', 'WMT', 'MO', 'GILD', 'SSL', 'VZ', 'T', 'ABEV', 'FNMA', 'IBM', 'BIDU',
           'NTES', 'CSCO', 'KOF', 'PG', 'RY', 'INTC', 'FB', 'EBR', 'SPIL', 'GM', 'DIS', 'ORCL', 'TD', 'CMCSA', 'PTR', 'XOM', 'FMCC', 'AMGN', 'GE', 'WBK', 'GS',
           'EBAY', 'PFE', 'BNS', 'UNH', 'HD', 'PM', 'YNDX', 'LN', 'NVS', 'BMA', 'KO', 'PEP', 'TOT', 'RAI', 'V', 'MS', 'ABBV'],
    _2018=['TLK', 'EC', 'KB', 'SHG', 'PKX', 'CIB', 'SKM', 'LPL', 'TM', 'KEP', 'NTTYY', 'DCMYY', 'SMFG', 'HMC', 'BCH', 'BSAC', 'KT', 'EOCCY', 'TSM', 'CAJ',
           'MUFG', 'CCU', 'HDB', 'CHL', 'IBN', 'WIT', 'SNE', 'TTM', 'MBT', 'VEDL', 'SNP', 'AAPL', 'BRK.B', 'BABA', 'CHT', 'NVO', 'BTI', 'FMX', 'LFC', 'VZ', 'T',
           'MSFT', 'CEO', 'ASX', 'PTR', 'ITUB', 'CMCSA', 'JPM', 'WFC', 'PFE', 'SSL', 'XOM', 'BIDU', 'BAC', 'BBD', 'FB', 'PG', 'TEO', 'WMT', 'PHI', 'GRVY',
           'RDS.A', 'YPF', 'GOOGL', 'RDY', 'RY', 'KHC', 'HSBC', 'UNP', 'NTES', 'UNH', 'TD', 'MO', 'CHTR', 'CSCO', 'INTC', 'ORCL', 'YNDX', 'CVX', 'BMA', 'DIS',
           'TGS', 'PAM', 'RIO', 'TOT', 'BA', 'SNY', 'LN', 'BNS', 'WBK', 'HD', 'PRU', 'EDN', 'NGG', 'F', 'NVS', 'BUD', 'ABEV', 'V', 'UMC'],
    _2019=['TLK', 'EC', 'SHG', 'SKM', 'KB', 'CIB', 'TM', 'PKX', 'MUFG', 'HMC', 'SMFG', 'KT', 'BCH', 'BSAC', 'SNE', 'TSM', 'CCU', 'IX', 'CAJ', 'TAK', 'HDB',
           'CHL', 'WIT', 'IBN', 'TTM', 'BABA', 'SNP', 'AAPL', 'PTR', 'CEO', 'YNDX', 'NVO', 'YPF', 'CHT', 'FMX', 'GOOGL', 'JPM', 'BAC', 'BIDU', 'ASX', 'CEPU',
           'ITUB', 'RDS.A', 'WFC', 'FB', 'CHA', 'INTC', 'XOM', 'T', 'C', 'TGS', 'PAM', 'BBD', 'MSFT', 'FNMA', 'VZ', 'JNJ', 'KOF', 'CVX', 'MU', 'VEDL', 'HSBC',
           'RIO', 'EBR', 'NVS', 'DIS', 'PEP', 'RY', 'AVGO', 'UNH', 'CMCSA', 'TOT', 'LFC', 'TD', 'PFE', 'ABEV', 'BA', 'GS', 'V', 'CHU', 'AMZN', 'WMT', 'RDY',
           'PG', 'BP', 'UL', 'UN', 'BMA', 'VIV', 'MS', 'SSL', 'IBM', 'HD', 'BNS', 'AMGN', 'TEO', 'WBK', 'GM', 'PM', 'NGG'],
    _2020=['TLK', 'EC', 'SHG', 'KB', 'CIB', 'TM', 'PKX', 'SNE', 'SKM', 'MUFG', 'KT', 'BSAC', 'HMC', 'SMFG', 'TSM', 'IX', 'HDB', 'CCU', 'TAK', 'CAJ', 'CHL',
           'WIT', 'BABA', 'BRK.B', 'CEO', 'LFC', 'SNP', 'AAPL', 'MBT', 'VEDL', 'PTR', 'IBN', 'MSFT', 'NVO', 'JPM', 'GOOGL', 'CHT', 'BAC', 'ITUB', 'NTES', 'INTC',
           'BBD', 'WFC', 'C', 'VZ', 'RDY', 'FB', 'ASX', 'PFE', 'RDS.A', 'JNJ', 'XOM', 'FNMA', 'T', 'UNH', 'CMCSA', 'RY', 'YNDX', 'TGS', 'PAM', 'KOF', 'JD', 'V',
           'ABEV', 'NVS', 'TD', 'CSCO', 'AMZN', 'LBTYA', 'CHU', 'TOT', 'HD', 'ORCL', 'DIS', 'PBR', 'MRK', 'IBM', 'MS', 'KO', 'BUD', 'GS', 'WUBA', 'BNS', 'LLY',
           'BHP', 'MA', 'RIO', 'ABBV', 'AMGN', 'EBR', 'HSBC', 'PEP', 'FMCC', 'COP', 'PM', 'TCOM', 'USB', 'WBK', 'AXP', 'GM'],
    _2021=['TM', 'SNE', 'HMC', 'MUFG', 'IX', 'HDB', 'SMFG', 'BABA', 'WIT', 'IBN', 'AAPL', 'MSFT', 'TAK', 'RDY', 'WMT', 'PG', 'TD', 'RY', 'HD', 'CSCO', 'V',
           'ORCL', 'BHP', 'BNS', 'VMW', 'QCOM', 'ACN', 'BMO', 'MDT', 'DELL', 'LOW', 'COST', 'NLOK', 'CM', 'TGT', 'TJX', 'EA', 'NVDA', 'MU', 'NKE', 'ADP', 'DHI',
           'INFY', 'WBK', 'LRCX', 'GIS', 'TSN', 'EMR', 'APD', 'INTU', 'AZO', 'DG', 'ROST', 'KR', 'CPB', 'MRVL', 'BBY', 'DEO', 'FDX', 'NGG', 'ADI', 'KLAC', 'PH',
           'HOLX', 'PAYX', 'ROK', 'STX', 'FOXA', 'CLX', 'SBUX', 'HRL', 'MCK', 'KMX', 'CTAS', 'BDX', 'CAG', 'DLTR', 'BF.B', 'NTAP', 'RJF', 'TXT', 'SWKS', 'BEN',
           'XLNX', 'SJM', 'ULTA', 'CPRT', 'TDG', 'KSS', 'SJR', 'EL', 'VFC', 'LDOS', 'MXIM', 'RYAAY', 'LULU', 'JCI', 'RMD', 'AMCR', 'ATO']
)

# 39th day; highest above 30pe+ and tradeable fixed 1; 0.0035
# 29th day; highest above 30pe+ and tradeable fixed 1; 0.0039
stock_dict_30pe_tradable_2 = dict(
    _2016=['GERN', 'BSFT', 'CSC', 'INCY', 'PENN', 'PCRX', 'MITT', 'FTI', 'TRU', 'SGRY', 'PEN', 'FTNT', 'YRCW', 'REXR', 'EGRX', 'AMZN', 'SNCR', 'ZOES', 'ATHN',
           'GWRE', 'BRC', 'NFLX', 'ULTI', 'EGHT', 'ODP', 'ASEI', 'CX', 'CCOI', 'ALXN', 'FNV', 'CIEN', 'BKI', 'SPSC', 'MINI', 'FCPT', 'ENV', 'LOGI', 'AEM',
           'HABT', 'MDSO', 'AVAV', 'FWONA', 'PRGO', 'RKUS', 'MOMO', 'ORC', 'EXAM', 'KRNY', 'FNSR', 'CXO', 'OLED', 'XXIA', 'ACOR', 'PNM', 'NUE', 'SSNC', 'PLAY',
           'VIRT', 'GIMO', 'PRTY', 'KMI', 'UNVR', 'ZBH', 'PRE', 'KRG', 'AAWW', 'HAE', 'ATML', 'NBHC', 'MBLY', 'GPRE', 'CCRN', 'BLKB', 'NPTN', 'AVID', 'LOGM',
           'SINA', 'IMMR', 'AIR', 'SCU', 'ISLE', 'WB', 'DOC', 'LYG', 'IRC', 'ITRI', 'PAYC', 'HTA', 'CCJ', 'BCR', 'OAK', 'HSC', 'RGEN', 'TVPT', 'ACAT', 'EQT',
           'EQIX', 'WES', 'EDR', 'QTS'],
    _2017=['TAST', 'MPLX', 'PEIX', 'ZLTQ', 'KRG', 'MTSI', 'BSFT', 'SEMG', 'TEAM', 'CVLT', 'BP', 'LOGM', 'KW', 'CHS', 'CUB', 'CEO', 'CC', 'TEVA', 'CMG', 'ACHC',
           'ECHO', 'HAWK', 'TRP', 'SUI', 'ARRS', 'CHU', 'GWRE', 'CQH', 'NFLX', 'WEB', 'SUM', 'ZOES', 'MYCC', 'IQV', 'GKOS', 'RAMP', 'LNCE', 'ELF', 'SPSC',
           'SALE', 'RMBS', 'TRCO', 'ERIC', 'HSTM', 'OFIX', 'BIO', 'SWC', 'OFC', 'WEX', 'GTT', 'CG', 'EQIX', 'ATHN', 'MORE', 'CONE', 'ICHR', 'INCY', 'ULTI',
           'DEA', 'ANIP', 'BSM', 'NXPI', 'AXTA', 'SBAC', 'WAGE', 'FSP', 'VSAT', 'NXGN', 'FTNT', 'SHPG', 'PCH', 'HPP', 'ITGR', 'MSGN', 'AMZN', 'SITC', 'SU',
           'SNCR', 'ERII', 'RP', 'SPH', 'ORC', 'GPT', 'BUD', 'MITK', 'AG', 'CHEF', 'PEN', 'CRS', 'KMPR', 'VRNT', 'LN', 'BKI', 'OMCL', 'ALRM', 'CCOI', 'TGE',
           'HSBC', 'PTR', 'PTHN'],
    _2018=['IONS', 'FTAI', 'WWW', 'RP', 'ASH', 'IT', 'SPSC', 'QTS', 'FLS', 'NSA', 'LRN', 'AM', 'KMI', 'RAD', 'HLNE', 'MCRN', 'VIRT', 'SID', 'EURN', 'BIP', 'PTC',
           'MELI', 'SUM', 'PTEN', 'WAT', 'EPC', 'ABM', 'NYT', 'PEN', 'IMAX', 'RAMP', 'ACIW', 'ULTI', 'CARG', 'BSIG', 'REI', 'GRA', 'LX', 'MRVL', 'IR', 'CCOI',
           'PCTY', 'LGF.B', 'DECK', 'BSX', 'ZBRA', 'NCSM', 'GWRE', 'JNJ', 'AAXN', 'USM', 'TREE', 'ALB', 'PSDO', 'TTEC', 'SRCL', 'AMPH', 'FTNT', 'BCO', 'LGND',
           'GOL', 'AXTA', 'ORC', 'DEA', 'ABT', 'GRPN', 'WINS', 'RH', 'ANF', 'HSC', 'AMZN', 'SBAC', 'QGEN', 'ATVI', 'EQC', 'HR', 'CRY', 'CRM', 'WPM', 'POST',
           'OFIX', 'KO', 'VSAT', 'EQIX', 'OPI', 'NFLX', 'BGFV', 'MTW', 'CCI', 'APPF', 'CHCT', 'SWIR', 'VRTX', 'DD', 'NAV', 'KRG', 'DLR', 'PUMP', 'COG', 'CWH'],
    _2019=['AXS', 'CONE', 'EHTH', 'WP', 'CSCO', 'PODD', 'GNL', 'PDCE', 'CEVA', 'PEN', 'CSII', 'ATUS', 'AVX', 'SUM', 'SAIL', 'IMBI', 'PZZA', 'BDX', 'MCK', 'SWCH',
           'SJR', 'NSA', 'ENV', 'SBAC', 'NXGN', 'PEGA', 'UNIT', 'TGP', 'HAIN', 'AQUA', 'CATM', 'PGRE', 'ACIA', 'NBIX', 'MEET', 'ALXN', 'STAA', 'AMH', 'APA',
           'PTC', 'CXP', 'Y', 'CRM', 'SSRM', 'ADSW', 'ZNGA', 'EPAY', 'PAAS', 'EIGI', 'NUVA', 'BEP', 'FTAI', 'ANF', 'NEO', 'CWST', 'TERP', 'LBRDA', 'DLB', 'QTNA',
           'SMLP', 'SYNH', 'DEA', 'ICUI', 'CUB', 'CONN', 'TPIC', 'NTAP', 'TDC', 'GDDY', 'ACB', 'PLXS', 'SAND', 'FARO', 'RGEN', 'OSPN', 'SJI', 'ELAN', 'PRNB',
           'RP', 'AYX', 'TCMD', 'BRK.B', 'ALTR', 'INCY', 'CHCT', 'RGS', 'ULTI', 'GCP', 'ALRM', 'CARB', 'ABMD', 'VMW', 'HSKA', 'INXN', 'SHAK', 'JBGS', 'SSNC',
           'ANGI', 'RCII', 'CMPR'],
    _2020=['CWK', 'CEVA', 'CIIC', 'AAXN', 'PRA', 'ALUS', 'NOK', 'SUM', 'SBSW', 'SFTW', 'QTS', 'DRQ', 'ONTO', 'PODD', 'CVLT', 'F', 'MCK', 'PRMW', 'BAND', 'CRY',
           'MSGS', 'VIAV', 'DOYU', 'NLOK', 'MYGN', 'LNN', 'GSHD', 'GWRE', 'SWCH', 'PEAK', 'INOV', 'NEO', 'PNTG', 'WTTR', 'E', 'BANC', 'BLKB', 'MMSI', 'SWI',
           'FIS', 'NBIX', 'BIP', 'AMG', 'CXP', 'SLAB', 'FMX', 'UMH', 'DEA', 'COKE', 'AYX', 'RXN', 'RGEN', 'TREE', 'VRT', 'CY', 'HTA', 'BKR', 'EPAY', 'FOE',
           'UEIC', 'DXCM', 'CSTL', 'CVA', 'GO', 'LBRDA', 'GSX', 'UNIT', 'AUDC', 'SBAC', 'CONE', 'LINX', 'LXFR', 'SSTI', 'ELAN', 'MNRL', 'IQV', 'BCO', 'WPM',
           'KTOS', 'AMD', 'OPRT', 'BIDU', 'NXPI', 'FSP', 'GMRE', 'EZPW', 'AIR', 'COLD', 'ZNGA', 'HPP', 'KRUS', 'VRTU', 'VICR', 'HPK', 'FWONA', 'GKOS', 'VFF',
           'GPN', 'KLIC', 'ATUS'],
    _2021=['POST', 'EPAC', 'CRM', 'ZM', 'CRS', 'MLAB', 'SRDX', 'NUAN', 'MOG.A', 'ADSK', 'DAVA', 'AIR', 'CMD', 'VRNT', 'JJSF', 'TAK', 'SYY', 'PCTY', 'CALM',
           'HQY', 'SLP', 'STAA', 'SMTC', 'SBUX', 'MSGE', 'AIT', 'EL', 'VIAV', 'JBL', 'DSGX', 'NXGN', 'BDX', 'AMSWA', 'MTN', 'PTC', 'VEEV', 'WBA', 'SMPL', 'HAE',
           'CTLT', 'REX', 'NEOG', 'NKE', 'VAR', 'CMTL', 'NVDA', 'DGII', 'BRKS', 'FICO', 'MRCY', 'SLQT', 'NSSC', 'TDG', 'TFSL', 'OTEX', 'DEO', 'FLEX', 'JCI',
           'JKHY', 'EGAN', 'HLNE', 'WDFC', 'EDU', 'LULU', 'LRN', 'RMD', 'EXPO', 'TECH', 'INTU', 'LITE', 'THR', 'RGLD', 'GBDC', 'COST', 'SR', 'FIVE', 'BF.B',
           'ADI', 'V', 'FDS', 'EAT', 'SXI', 'AVAV', 'APD', 'MSFT', 'BRBR', 'EXP', 'KEM', 'LAKE', 'VFC', 'AAPL', 'FRHC', 'ETH', 'GMS', 'TTWO', 'ABMD', 'WGO',
           'RAVN', 'RPM', 'PAHC']
    )

# high divyield: 0.0026 (but at -50% loss in real returns)
# 29th day: high divyield: 0.0031
stock_dict_high_divyield = dict(
    _2016=['SPXC', 'NI', 'EBAY', 'AROC', 'OA', 'BAX', 'GHC', 'MEMP', 'LINE', 'VNRSQ', 'EPC', 'A', 'TOO', 'MCEP', 'KLAC', 'TRS', 'TGNA', 'BWXT', 'NRF', 'WINMQ',
           'CEQP', 'PPC', 'TROX', 'WMC', 'ETP', 'HSNI', 'TRCO', 'CG', 'TGP', 'VTR', 'ARLP', 'BTE', 'CPTA', 'ORC', 'NYMT', 'ERF', 'XAN', 'ARR', 'MITT', 'TK',
           'AHT', 'PNNT', 'GMLP', 'MCC', 'CPLP', 'PDLI', 'TKC', 'SSP', 'CVRR', 'TAL1', 'PSEC', 'GLP', 'UAN', 'VIV', 'CYS', 'MMLP', 'ALDW', 'EC', 'ADP', 'NTI',
           'RESI', 'CIG', 'HTS', 'NRZ', 'CPG', 'AGNC', 'PMT', 'CIM', 'SCU', 'CLMT', 'VNO', 'ANH', 'IVR', 'CMO', 'KMI', 'APO', 'MTGE', 'OCSL', 'NLY', 'TWO',
           'MAS', 'DCP', 'SXC', 'TRGP', 'WPZ', 'MFA', 'SMLP', 'PAA', 'BX', 'BBDC', 'TGH', 'ACTG', 'PPL', 'OPI', 'MBT', 'GLNG', 'SHO', 'ARCC', 'SIR', 'JE'],
    _2017=['MSGN', 'MTW', 'RRD', 'CSC', 'HPQ', 'BKS', 'SYNT', 'VIAV', 'CYH', 'VC', 'FCAU', 'FCPT', 'YUM', 'CUZ', 'NGL', 'DHR', 'LDOS', 'GRA', 'EQR', 'EURN',
           'DHT',
           'CLMT', 'ETP', 'IHG', 'NAT', 'MMLP', 'ORC', 'AWI', 'PNNT', 'FRO', 'MCC', 'CPLP', 'NYMT', 'PPC', 'AINV', 'CIM', 'CPTA', 'ARR', 'PLNT', 'WMC', 'TNK',
           'CYS', 'JWN', 'PSEC', 'DRI', 'AGNC', 'OCSL', 'CEQP', 'SXCP', 'SUN', 'USAC', 'BKCC', 'SFL', 'NLY', 'PHI', 'UAN', 'NRZ', 'ANH', 'PMT', 'ARI', 'ITGR',
           'MITT', 'STNG', 'TDW', 'CG', 'IVR', 'TWO', 'DLNG', 'PRA', 'SNR', 'MFA', 'SPH', 'BBDC', 'MTGE', 'STX', 'CIG', 'IEP', 'WING', 'GMLP', 'NMFC', 'MDCA',
           'WPG', 'FIG', 'GLP', 'APAM', 'WDR', 'UNIT', 'LADR', 'AMID', 'AHGP', 'GLOP', 'CMO', 'EEP', 'ARCC', 'CMTL', 'GNL', 'SMLP', 'CCP', 'QIWI', 'OPI'],
    _2018=['DRYS', 'MACK', 'ASH', 'HPE', 'TGNA', 'ALEX', 'CKH', 'HCC', 'FNF', 'HLT', 'VNO', 'TWO', 'APTV', 'NAT', 'CTXS', 'CLNY', 'CPTA', 'ORC', 'TDG', 'CNX',
           'BBDC', 'TERP', 'WINMQ', 'PK', 'TRCO', 'NS', 'MET', 'JCI', 'WPG', 'SNR', 'SPH', 'SXCP', 'UNIT', 'CIM', 'XRX', 'NCMI', 'NYMT', 'MCC', 'CNSL', 'CYS',
           'WMC', 'PSEC', 'ETP', 'GEL', 'EEQ', 'EEP', 'FSK', 'PMT', 'SUN', 'BRG', 'IEP', 'MDC', 'SMLP', 'NRZ', 'ANH', 'CHMI', 'PNNT', 'AGNC', 'MITT', 'PRA',
           'SFL',
           'MFA', 'BPL', 'ENLK', 'NLY', 'GMLP', 'MTGE', 'NMFC', 'VAR', 'ARI', 'AINV', 'ARCC', 'GNL', 'AHGP', 'ARLP', 'HTGC', 'PAA', 'TCPC', 'OPI', 'CEQP',
           'SBRA',
           'CMO', 'OHI', 'MHLD', 'IVR', 'STWD', 'LADR', 'ARR', 'NEWT', 'ENBL', 'PAGP', 'TSLX', 'DCP', 'TNK', 'SITC', 'BKE', 'AB', 'CODI', 'VOD', 'NEWM'],
    _2019=['RENN', 'KDP', 'WYND', 'EQT', 'ALV', 'PNR', 'CYOU', 'TRN', 'SITC', 'DOV', 'HCC', 'OPI', 'SMTA', 'SMLP', 'SRC', 'WPG', 'GMLP', 'AMC', 'SNR', 'RFP',
           'OSB', 'ORC', 'FSK', 'USAC', 'PCH', 'VGR', 'CNSL', 'BPL', 'UNIT', 'BKE', 'TEO', 'WMC', 'NGG', 'TWO', 'APAM', 'NGL', 'MC', 'NRZ', 'PEI', 'CPTA',
           'BGCP',
           'NS', 'SEMG', 'MCC', 'NYMT', 'VEDL', 'OMI', 'SFL', 'NEWM', 'BEN', 'PBI', 'ANDX', 'VEON', 'ATUS', 'IEP', 'AGNC', 'SNP', 'NLY', 'MIC', 'SUN', 'GNL',
           'AHT', 'WRI', 'NBR', 'MFA', 'ARLP', 'DCP', 'MBT', 'CATO', 'IVR', 'AINV', 'GEL', 'PSEC', 'HTGC', 'ABR', 'CIM', 'ENLC', 'CNS', 'ARR', 'ARI', 'TCPC',
           'BKS', 'SBRA', 'NCMI', 'NMFC', 'GLOP', 'PK', 'AB', 'SPH', 'CLNC', 'PMT', 'TRGP', 'WING', 'TSLX', 'LADR', 'ARCC', 'EQM', 'VET', 'STWD', 'QUAD'],
    _2020=['KAR', 'DD', 'NTGR', 'SMLP', 'WPG', 'BTU', 'HSIC', 'QUAD', 'HCC', 'DXC', 'LYB', 'SATS', 'CNSL', 'ARLP', 'ENLC', 'VMW', 'IRWD', 'PUK', 'ORC', 'PEI',
           'VET', 'EQM', 'TGS', 'BAK', 'AM', 'NVS', 'GLOP', 'GME', 'FMC', 'FCAU', 'ETRN', 'IEP', 'CGBD', 'ENBL', 'UAN', 'NYMT', 'DCP', 'CLNC', 'WES', 'NRZ',
           'FSK',
           'MITT', 'CHMI', 'JE', 'ARR', 'HEP', 'AHT', 'BKS', 'WMC', 'VEON', 'AINV', 'TARO', 'TEO', 'DX', 'SFUN', 'VGR', 'GEO', 'BSM', 'USAC', 'BKE', 'SNP',
           'TRIP',
           'TWO', 'CPTA', 'AGNC', 'NLY', 'IVR', 'MAC', 'NGL', 'PSEC', 'AMC', 'WERN', 'SUN', 'GEL', 'EQC', 'ADT', 'APAM', 'MFA', 'MPLX', 'RC', 'MC', 'TCPC',
           'ARI',
           'SPH', 'TPVG', 'DHC', 'GLOG', 'GCI', 'EFC', 'NMFC', 'EC', 'TUP', 'VEDL', 'REPH', 'VOD', 'TGE', 'CIM', 'SKT', 'SFL', 'NWG'],
    _2021=['JILL', 'NLOK', 'NGL', 'MSGS', 'AINV', 'JE', 'HP', 'SPH', 'PSEC', 'TLRDQ', 'VFC', 'MDP', 'MSM', 'TLYS', 'GBDC', 'GME', 'M', 'BKE', 'CHS', 'COTY',
           'CATO', 'TPR', 'BNS', 'OCSL', 'TFSL', 'CFFN', 'JBSS', 'CM', 'NUAN', 'VOD', 'DBI', 'UVV', 'ETH', 'PDCO', 'TDG', 'BMO', 'TD', 'RY', 'DXC', 'KSS', 'SJR',
           'BBBY', 'HRB', 'SIG', 'VEDL', 'GWB', 'BHP', 'PLT', 'GPS', 'STX', 'BEN', 'NGG', 'LB', 'MNR', 'ANF', 'EAT', 'SMG', 'WBA', 'SR', 'NJR', 'AMCR', 'WMS',
           'WBK', 'MOV', 'NTAP', 'EBF', 'HMC', 'BIG', 'NFG', 'WAFD', 'UGI', 'FL', 'JWN', 'RL', 'CBT', 'GBX', 'WRK', 'PLCE', 'SCHN', 'PETS', 'MATW', 'AEO', 'CAH',
           'SCS', 'KRNY', 'CBRL', 'WDC', 'CAE', 'DRI', 'PAYX', 'CRS', 'LM', 'SYY', 'WOR', 'MXIM', 'AVT', 'CSCO', 'ENR', 'INFY', 'EMR'],
)

# 39th day: low divyield: 0.0517; affected by huge outliers
# 29th day: low divyield:
stock_dict_low_div_yield = dict(
	_2016=['SIVB', 'RSLS', 'GDOT', 'GDDY', 'RSPP', 'RSTI', 'GBT', 'RTEC', 'RRGB', 'RUN', 'G', 'FWP', 'FWONA', 'FVE', 'RVNC', 'RWLK', 'FTNT', 'RUSHA', 'GENE', 'RPXC', 'GEOS', 'RMTI', 'RNET', 'GLOB', 'RNG', 'GLFMQ', 'GLBR', 'GKOS', 'ROCK', 'ROG', 'GIMO', 'GIGA', 'GIB', 'GHDX', 'RP', 'RPD', 'RPTP', 'GERN', 'FTK', 'GLPG', 'FTI1', 'RXDX', 'SAM', 'FLXN', 'FLWS', 'FLTX', 'FLT', 'SANM', 'FLOW', 'SALT', 'FLEX', 'FIT', 'FISV', 'SATS', 'SAVE', 'SBAC', 'FGEN', 'FFIV', 'FLDM', 'FMCC', 'SALE', 'FMI', 'RXN', 'FSLR', 'S', 'SA', 'FRSH', 'FRPT', 'SAAS', 'FPRX', 'FORM', 'FOR', 'FOLD', 'FOE', 'FNSR', 'FNMA', 'SAGE', 'SAIA', 'FN', 'FTI', 'RMBS', 'GLRE', 'RLYP', 'RAMP', 'RARE', 'RATE', 'HHC', 'HGEN', 'RAX', 'RBBN', 'RAD', 'RCKT', 'RDEN', 'HDP', 'RDUS', 'RDWR', 'HCA', 'REGI', 'REGN', 'HELE'],
	_2017=['ZYNE', 'PRFT', 'FEYE', 'FET', 'FDC', 'FCX', 'FCN', 'PRLB', 'PRAH', 'PRO', 'PRTA', 'FCB', 'PRTY', 'PRXL', 'FBP', 'FBC', 'FB', 'PRSC', 'PSTG', 'FFIV', 'PRAA', 'PLUS', 'PLXS', 'FLOW', 'PMC', 'FLEX', 'PNK', 'FIZZ', 'FGEN', 'FIVN', 'PNRA', 'FIT', 'FISV', 'POAI', 'PODD', 'POST', 'PPBI', 'FIVE', 'FARO', 'FANG', 'PTC', 'QCP', 'QDEL', 'QEP', 'QGEN', 'QLGC', 'ETFC', 'QLYS', 'ETSY', 'QRTEA', 'QRVO', 'ESPR', 'ESNT', 'QTWO', 'QUIK', 'ESL', 'ESI', 'ESRX', 'PYPL', 'PXD', 'EVBG', 'PTCT', 'EZPW', 'EYES', 'EXTN', 'EXPR', 'PTHN', 'PTLA', 'EXLS', 'EXK', 'EXEL', 'EXAS', 'EWLL', 'PVG', 'EW', 'EVHC', 'EVH', 'PWR', 'FLT', 'FLXN', 'FLY', 'PLUG', 'GERN', 'PCRX', 'PCTY', 'PDCE', 'PDFS', 'GDS', 'GDOT', 'PBYI', 'GDDY', 'GCP', 'GCO', 'PE', 'GBT', 'PEIX', 'PEN', 'PENN', 'PDS', 'PBR'],
	_2018=['KEYS', 'MBI', 'MB', 'MASI', 'MARK', 'MARA', 'MANH', 'MAG', 'LYV', 'LXU', 'LXRX', 'LXFT', 'LX', 'LULU', 'LTRPA', 'LTBR', 'LSCC', 'LRN', 'LQ', 'LPX', 'LPSN', 'LPNT', 'LPI', 'LOXO', 'MBUU', 'LOPE', 'MCB', 'MCRN', 'MLNX', 'MKL', 'MITL', 'MITK', 'MIME', 'MIK', 'MIDD', 'MHO', 'MHK', 'MGTI', 'MGNX', 'MGLN', 'MGI', 'MGEN', 'MEET', 'MEDP', 'MDXG', 'MDSO', 'MDRX', 'MDGL', 'MDCO', 'MDCA', 'MD', 'MCFT', 'LOMA', 'LOCO', 'LNTH', 'KN', 'KMX', 'KLXI', 'KLIC', 'KLDX', 'KGC', 'KEYW', 'ZUMZ', 'KEX', 'KERX', 'KEM', 'KANG', 'KALA', 'JUNO', 'JT', 'JRJC', 'JOE', 'JOBS', 'JMEI', 'JKS', 'JELD', 'JD', 'JBLU', 'KOP', 'KOS', 'KRA', 'KRNT', 'LNG', 'LN', 'LL', 'LKQ', 'LJPC', 'LIVN', 'LITE', 'LHCG', 'LH', 'LGND', 'LGIH', 'MMI', 'LE', 'LCI', 'LC', 'LBTYA', 'LBRDA', 'LBC'],
	_2019=['ZUMZ', 'EXTN', 'PLAB', 'EXPR', 'PLAY', 'PLM', 'PLNT', 'EXLS', 'EXTR', 'EXEL', 'EXAS', 'EWLL', 'PLUS', 'EW', 'EVRI', 'PLXS', 'PODD', 'PLUG', 'EVOP', 'EYE', 'EZPW', 'PETQ', 'FDC', 'PFGC', 'PFPT', 'FCN', 'PGNX', 'PGTI', 'EYES', 'FCAU', 'PI', 'FBC', 'FB', 'FATE', 'PINC', 'FARO', 'PIXY', 'PHIO', 'EVH', 'EVBG', 'POST', 'PRTY', 'PS', 'PSDO', 'PSTG', 'PTC', 'PTCT', 'EPZM', 'PRTK', 'PTE', 'PTLA', 'EPC', 'EPAY', 'EPAM', 'EOLS', 'PUMP', 'ENVA', 'PTI', 'PRTA', 'PRSC', 'PRQR', 'PPBI', 'ETSY', 'ETRN', 'PPC', 'PQG', 'PRAA', 'PRAH', 'PRFT', 'PRLB', 'PRNB', 'ESPR', 'ESNT', 'PRO', 'ESL', 'ESIO', 'ESI', 'ESGR', 'PERY', 'ENV', 'PENN', 'FET', 'FSCT', 'FSB', 'ORLY', 'FRPT', 'FRO', 'OSIS', 'FRGI', 'ORBC', 'OSPN', 'OSTK', 'FPRX', 'FOXF', 'FOSL', 'FORM', 'FOLD', 'FOE', 'FRAN', 'FOCS'],
	_2020=['KLXE', 'MBOT', 'MBI', 'MAT', 'MASI', 'MANH', 'MAG', 'LYV', 'LYFT', 'LXRX', 'LX', 'LVGO', 'LUMO', 'LULU', 'LTRPA', 'LTHM', 'LSCC', 'LRN', 'LPSN', 'LPI', 'LOVE', 'LOPE', 'LOMA', 'LOCO', 'MBUU', 'LNTH', 'MCFT', 'MDB', 'MLNX', 'MKL', 'MKD', 'MITK', 'MIRM', 'MIME', 'MIK', 'MIDD', 'MHO', 'MHK', 'MGY', 'MGTX', 'MGNX', 'MGNI', 'MGLN', 'MGI', 'MELI', 'MEET', 'MEDP', 'MDXG', 'MDRX', 'MDRIQ', 'MDGL', 'MD', 'MMI', 'LNG', 'LMPX', 'KRNT', 'KRA', 'KPTI', 'KOP', 'KOD', 'KNDI', 'KN', 'KMX', 'ZYME', 'KIRK', 'KIDS', 'KGC', 'KEYS', 'KEX', 'KERN', 'KEP', 'KDMN', 'KB', 'KALV', 'JT', 'JOE', 'JOBS', 'JMIA', 'KRTX', 'LN', 'KRUS', 'KT', 'LLNW', 'LL', 'LKQ', 'LJPC', 'LIVN', 'LITE', 'LINX', 'LIND', 'LILA', 'LHCG', 'LH', 'LGND', 'LGIH', 'LE', 'LCI', 'LC', 'LBTYA', 'LBRDA'],
	_2021=['KMX', 'MIME', 'MIK', 'MESO', 'MEIP', 'MDLA', 'MDB', 'MCFT', 'MBUU', 'LULU', 'LRN', 'LPG', 'LOVE', 'LITE', 'LGF.B', 'LE', 'LCI', 'LAKE', 'MMYT', 'ZUMZ', 'MODN', 'MSGE', 'OLLI', 'OKTA', 'OGI', 'NXGN', 'NTNX', 'NTCT', 'NSSC', 'NNVC', 'NEWR', 'NEOG', 'MYOV', 'MYGN', 'MUFG', 'MU', 'MTSI', 'MTOR', 'MSGN', 'MRCY', 'KLXE', 'KERN', 'JCPNQ', 'GCO', 'FRHC', 'FRAN', 'FOXF', 'FN', 'FLWS', 'FLEX', 'FIZZ', 'FIVE', 'FICO', 'FFIV', 'EXTR', 'EXPR', 'ESTC', 'ESGC', 'EQOS', 'EPC', 'GENE', 'GIII', 'GMBL', 'GMS', 'IX', 'IMVT', 'IMRN', 'IIVI', 'IIIV', 'IBIO', 'HZO', 'HQY', 'OSIS', 'HOME', 'HIBB', 'HEXO', 'HELE', 'HDS', 'HAIN', 'HAE', 'GWRE', 'GOOS', 'HOLX', 'PANW', 'PBH', 'PCTY', 'TWST', 'TTWO', 'TTM', 'TRMB', 'TMBR', 'TM', 'THR', 'TECD', 'TEAM', 'TAL', 'TAK', 'SYNA', 'SWBI', 'STAA'],
)

# 39th day: high netinccmn: 0.0212 but affected by outliers
# 29th day: high netinccmn: 0.0011
stock_dict_high_netinccmn = dict(
	_2016=['TLK', 'KEP', 'CIB', 'SHG', 'TM', 'KB', 'MUFG', 'SKM', 'LPL', 'SMFG', 'BCH', 'KT', 'NTTYY', 'HMC', 'BSAC', 'DCMYY', 'TSM', 'CAJ', 'PKX', 'CCU', 'TTM', 'IBN', 'CHL', 'HDB', 'WIT', 'AAPL', 'MBT', 'CHT', 'PTR', 'NVO', 'LFC', 'BIDU', 'SNP', 'SSL', 'ITUB', 'BABA', 'BRK.B', 'JPM', 'RDY', 'PHI', 'WFC', 'CEO', 'ASX', 'BBD', 'GILD', 'VZ', 'NVS', 'FMX', 'C', 'XOM', 'GOOGL', 'BAC', 'ERIC', 'T', 'IBM', 'HSBC', 'ABEV', 'MSFT', 'INTC', 'FNMA', 'TV', 'CHU', 'KOF', 'ORCL', 'RY', 'GM', 'YNDX', 'SPIL', 'CSCO', 'GSK', 'DIS', 'TFCF', 'BUD', 'CMCSA', 'WBK', 'TD', 'AAL', 'F', 'KO', 'DD', 'UAL', 'MDLZ', 'PG', 'PFE', 'AMGN', 'BNS', 'PM', 'NTES', 'FMCC', 'V', 'UBS', 'VOD', 'UNH', 'MS', 'PRU', 'USB', 'GS', 'PEP', 'QCOM', 'MO'],
	_2017=['TLK', 'KEP', 'CIB', 'SHG', 'EC', 'TM', 'KB', 'SKM', 'PKX', 'LPL', 'SMFG', 'MUFG', 'KT', 'NTTYY', 'BCH', 'DCMYY', 'BSAC', 'EOCCY', 'HMC', 'TSM', 'IX', 'CAJ', 'SNE', 'CCU', 'HDB', 'CHL', 'IBN', 'TTM', 'NJDCY', 'WIT', 'BABA', 'MBT', 'SNP', 'AAPL', 'CHT', 'NVO', 'FMX', 'BRK.B', 'JPM', 'ITUB', 'ASX', 'MSFT', 'WFC', 'RDY', 'PHI', 'GOOGL', 'LFC', 'BBD', 'BAC', 'JNJ', 'C', 'AGN', 'WMT', 'MO', 'GILD', 'SSL', 'VZ', 'T', 'ABEV', 'FNMA', 'IBM', 'BIDU', 'NTES', 'CSCO', 'KOF', 'PG', 'RY', 'INTC', 'FB', 'EBR', 'SPIL', 'GM', 'DIS', 'ORCL', 'TD', 'CMCSA', 'PTR', 'XOM', 'FMCC', 'AMGN', 'WBK', 'EBAY', 'PFE', 'GS', 'UNH', 'HD', 'BNS', 'PM', 'GE', 'YNDX', 'LN', 'NVS', 'BMA', 'KO', 'PEP', 'TOT', 'RAI', 'V', 'ABBV', 'QCOM'],
	_2018=['TLK', 'EC', 'KB', 'SHG', 'PKX', 'CIB', 'SKM', 'LPL', 'TM', 'KEP', 'NTTYY', 'DCMYY', 'SMFG', 'HMC', 'BCH', 'BSAC', 'KT', 'EOCCY', 'TSM', 'CAJ', 'MUFG', 'CCU', 'HDB', 'CHL', 'IBN', 'WIT', 'SNE', 'TTM', 'MBT', 'VEDL', 'SNP', 'AAPL', 'BRK.B', 'BABA', 'CHT', 'NVO', 'BTI', 'FMX', 'LFC', 'VZ', 'T', 'MSFT', 'CEO', 'ASX', 'PTR', 'ITUB', 'CMCSA', 'JPM', 'PFE', 'WFC', 'SSL', 'XOM', 'BIDU', 'BBD', 'BAC', 'FB', 'PG', 'TEO', 'WMT', 'PHI', 'GRVY', 'RDS.A', 'YPF', 'GOOGL', 'RDY', 'RY', 'KHC', 'UNP', 'NTES', 'UNH', 'TD', 'MO', 'CHTR', 'HSBC', 'CSCO', 'INTC', 'ORCL', 'YNDX', 'CVX', 'BMA', 'DIS', 'TGS', 'PAM', 'RIO', 'TOT', 'BA', 'SNY', 'LN', 'WBK', 'HD', 'BNS', 'PRU', 'EDN', 'NGG', 'F', 'NVS', 'BUD', 'ABEV', 'V', 'UMC'],
	_2019=['TLK', 'EC', 'SHG', 'SKM', 'KB', 'CIB', 'TM', 'PKX', 'MUFG', 'HMC', 'SMFG', 'KT', 'BCH', 'BSAC', 'SNE', 'TSM', 'CCU', 'IX', 'CAJ', 'TAK', 'HDB', 'CHL', 'WIT', 'IBN', 'TTM', 'BABA', 'SNP', 'AAPL', 'PTR', 'CEO', 'YNDX', 'NVO', 'YPF', 'CHT', 'FMX', 'GOOGL', 'JPM', 'BIDU', 'ASX', 'CEPU', 'BAC', 'ITUB', 'RDS.A', 'FB', 'CHA', 'INTC', 'XOM', 'WFC', 'T', 'C', 'TGS', 'PAM', 'BBD', 'MSFT', 'FNMA', 'VZ', 'JNJ', 'KOF', 'CVX', 'MU', 'VEDL', 'RIO', 'EBR', 'NVS', 'HSBC', 'DIS', 'PEP', 'RY', 'AVGO', 'UNH', 'CMCSA', 'TOT', 'LFC', 'PFE', 'TD', 'ABEV', 'BA', 'V', 'CHU', 'AMZN', 'WMT', 'GS', 'RDY', 'PG', 'BP', 'UN', 'UL', 'BMA', 'VIV', 'SSL', 'IBM', 'HD', 'AMGN', 'BNS', 'MS', 'TEO', 'WBK', 'GM', 'PM', 'NGG'],
	_2020=['TLK', 'EC', 'SHG', 'KB', 'CIB', 'TM', 'PKX', 'SNE', 'SKM', 'MUFG', 'KT', 'BSAC', 'HMC', 'SMFG', 'TSM', 'IX', 'HDB', 'CCU', 'TAK', 'CAJ', 'CHL', 'WIT', 'BABA', 'BRK.B', 'CEO', 'LFC', 'SNP', 'AAPL', 'MBT', 'VEDL', 'PTR', 'IBN', 'MSFT', 'NVO', 'JPM', 'GOOGL', 'CHT', 'ITUB', 'BAC', 'NTES', 'INTC', 'BBD', 'C', 'VZ', 'RDY', 'FB', 'ASX', 'WFC', 'PFE', 'RDS.A', 'JNJ', 'XOM', 'FNMA', 'T', 'UNH', 'CMCSA', 'RY', 'YNDX', 'TGS', 'PAM', 'KOF', 'JD', 'V', 'ABEV', 'NVS', 'CSCO', 'AMZN', 'LBTYA', 'TD', 'CHU', 'TOT', 'HD', 'ORCL', 'DIS', 'PBR', 'MRK', 'IBM', 'KO', 'BUD', 'MS', 'LLY', 'BHP', 'WUBA', 'BNS', 'MA', 'RIO', 'GS', 'ABBV', 'AMGN', 'EBR', 'PEP', 'FMCC', 'COP', 'PM', 'TCOM', 'WBK', 'AXP', 'WMT', 'CVS', 'FCAU'],
	_2021=['TM', 'SNE', 'HMC', 'MUFG', 'IX', 'HDB', 'SMFG', 'BABA', 'WIT', 'IBN', 'AAPL', 'MSFT', 'TAK', 'RDY', 'WMT', 'PG', 'TD', 'RY', 'HD', 'CSCO', 'V', 'ORCL', 'BHP', 'BNS', 'VMW', 'QCOM', 'ACN', 'BMO', 'MDT', 'DELL', 'LOW', 'COST', 'NLOK', 'CM', 'TGT', 'TJX', 'EA', 'NVDA', 'MU', 'NKE', 'ADP', 'DHI', 'INFY', 'WBK', 'LRCX', 'GIS', 'TSN', 'EMR', 'APD', 'INTU', 'AZO', 'DG', 'ROST', 'KR', 'CPB', 'MRVL', 'BBY', 'DEO', 'FDX', 'NGG', 'ADI', 'KLAC', 'PH', 'HOLX', 'PAYX', 'ROK', 'STX', 'FOXA', 'CLX', 'SBUX', 'HRL', 'MCK', 'KMX', 'CTAS', 'CAG', 'BF.B', 'DLTR', 'NTAP', 'RJF', 'TXT', 'SWKS', 'BEN', 'XLNX', 'SJM', 'BDX', 'ULTA', 'CPRT', 'KSS', 'SJR', 'EL', 'VFC', 'LDOS', 'MXIM', 'RYAAY', 'LULU', 'JCI', 'RMD', 'AMCR', 'ATO', 'MCHP'],
)

# 39th day: high roe: 0.0662 someoutliers but kinda good; rerun by trimming outliers
# 29th day: high roe: 0.0261 someoutliers but kinda good; rerun by trimming outliers
stock_dict_high_roe = dict(
	_2016=['BNFT', 'OMER', 'CUDA', 'SRRA', 'AZPN', 'HTGM', 'UNISQ', 'ALLE', 'ARIA', 'KMB', 'CL', 'SNECQ', 'WTI', 'UPLMQ', 'NYMX', 'CCK', 'BEAV', 'XCOOQ', 'INST', 'MAS', 'LII', 'AMD', 'NSPX', 'GLBR', 'FUN', 'PBI', 'CLX', 'SONC', 'AVP', 'FNMA', 'PAHC', 'UPS', 'MJN', 'SPGI', 'MNKD', 'TOWR', 'FMCC', 'AAL', 'OUTR', 'SGMS', 'MO', 'LNG', 'CSTM', 'GSK', 'SIRI', 'AMRN', 'MX', 'HSNI', 'LGND', 'SABR', 'VZ', 'USG', 'CEB', 'SIX', 'SHW', 'PZZA', 'BSIG', 'SEDG', 'ABBV', 'VC', 'STRZA', 'JE', 'BAH', 'UAL', 'TUP', 'EXEL', 'LMT', 'FPRX', 'XOMA', 'AXL', 'NHTC', 'NXST', 'LAZ', 'GILD', 'DLYT', 'IBM', 'MACK', 'BZH', 'HW', 'ALDW', 'RPD', 'JMBA', 'AVDL', 'JACK', 'NVO', 'YUM', 'CBOE', 'BRSS', 'BA', 'EVTC', 'NTI', 'ASPS', 'SHLX', 'MSI', 'MTG', 'TCO', 'APAM', 'EVH', 'PLKI', 'ALGT'],
	_2017=['GOGO', 'RSLS', 'HALO', 'LII', 'SNES', 'NKTR', 'CQH', 'MCD', 'CRZO', 'AMD', 'KMB', 'BANT', 'ISEE', 'FUN', 'CHRS', 'ZIOP', 'SPGI', 'WIX', 'IRTC', 'IMGN', 'AMCX', 'NOVN', 'EWLL', 'FNMA', 'CLX', 'BERY', 'BA', 'FMCC', 'KOP', 'MO', 'PNK', 'HLF', 'RACE', 'LMT', 'BEAV', 'PLKI', 'TNET', 'ALLE', 'VVV', 'WNRL', 'OMER', 'UPS', 'IMMU', 'KLAC', 'OKE', 'TPX', 'CCK', 'TLND', 'PAHC', 'BUFF', 'HRB', 'SGY', 'PBI', 'EXEL', 'BNFT', 'TCO', 'VLP', 'TUP', 'ABBV', 'AMRN', 'NSP', 'MESG', 'EBAY', 'INTU', 'ISLE', 'TPL', 'BAH', 'NVO', 'APTI', 'HSY', 'BWXT', 'HD', 'NHTC', 'MASI', 'SEE', 'GILD', 'MAR', 'SHW', 'WYND', 'AIRG', 'SSNI', 'MTD', 'NILE', 'ABC', 'DAN', 'NRP', 'TSE', 'IBM', 'EVTC', 'YRD', 'EGRX', 'HSNI', 'MANH', 'BF.B', 'MA', 'NOG', 'MACK', 'BSIG', 'ABG', 'CBOE'],
	_2018=['CQH', 'KERX', 'MACK', 'FG', 'MYSZ', 'BA', 'CMTA', 'GOVX', 'FUN', 'LII', 'HMNY', 'NAKD', 'KALA', 'AMPE', 'KMB', 'STRP', 'AMCX', 'CISN', 'MARA', 'MYO', 'HDP', 'UPS', 'MARK', 'MCFT', 'VRAY', 'WK', 'WBT', 'INPX', 'HTGM', 'PBI', 'AGEN', 'APPN', 'ENR', 'ROKU', 'TPX', 'GSK', 'GCP', 'NVAX', 'AVEO', 'PRO', 'HLF', 'CANB', 'PLX', 'ASPS', 'SPWH', 'OMER', 'BANT', 'FMCC', 'CURO', 'LMT', 'CLX', 'CDK', 'IMMU', 'SPGI', 'SEE', 'BNFT', 'WYNN', 'TCO', 'AMRN', 'TNET', 'TPL', 'PGEM', 'FNMA', 'AZUL', 'HD', 'CORT', 'CSRA', 'LPI', 'WYND', 'ORLY', 'GOGO', 'QTRX', 'CC', 'VLP', 'CAR', 'CWH', 'HOV', 'BTI', 'CIEN', 'DLYT', 'BLMN', 'VZ', 'NSP', 'FSCT', 'HGV', 'CQP', 'ABBV', 'ALLE', 'HSY', 'RYAM', 'MSCI', 'HALO', 'RACE', 'RDFN', 'OEC', 'KLAC', 'ZIOP', 'MBUU', 'LW', 'NPO'],
	_2019=['FUN', 'JE', 'PRO', 'FTSI', 'MYT', 'GLNG', 'LXRX', 'CRMD', 'NIO', 'AVLR', 'PIXY', 'LMT', 'PS', 'HEAR', 'ENDP', 'BLPH', 'MDB', 'WK', 'MCO', 'GOVX', 'SPGI', 'AKS', 'HJLI', 'ORLY', 'RST', 'HD', 'AM', 'FNMA', 'ENR', 'IRWD', 'BNFT', 'W', 'MSCI', 'DCTH', 'UPS', 'GSK', 'VSM', 'OMER', 'NIHD', 'AMCX', 'DLPH', 'CQP', 'BLMN', 'NVAX', 'WFTIQ', 'ACRX', 'HCC', 'APAM', 'EWLL', 'PBI', 'RETA', 'YRD', 'AGEN', 'TPL', 'CEI', 'NSP', 'SBUX', 'MCFT', 'VAPO', 'CLX', 'PEP', 'MA', 'TNTR', 'RAD', 'HSY', 'ALSN', 'BSIG', 'CC', 'ENPH', 'CTXS', 'MTD', 'AMRS', 'OEC', 'HLT', 'SIBN', 'STX', 'CASA', 'ATKR', 'CBB', 'RHP', 'UXIN', 'CELG', 'AZUL', 'CEPU', 'POOL', 'HX', 'SGH', 'LNTH', 'WEN', 'CHDN', 'FTDR', 'ALLE', 'PVAC', 'NVO', 'EXEL', 'UL', 'UN', 'HDS', 'MANH', 'SPB'],
	_2020=['JE', 'QTNT', 'CYTK', 'HD', 'RDUS', 'TMDX', 'APDN', 'IAA', 'VIVE', 'NIO', 'CLVS', 'PAE', 'ORLY', 'SPGI', 'MDRIQ', 'LJPC', 'OCGN', 'RH', 'MCO', 'RAPT', 'HRB', 'LXRX', 'CHRS', 'LLY', 'XBIT', 'IDXX', 'TBLT', 'BSIG', 'PIXY', 'CURO', 'MTCH2', 'AVEO', 'ACRX', 'BNFT', 'BURL', 'LMT', 'NSP', 'BPMP', 'UI', 'GOVX', 'BE', 'GSKY', 'PBI', 'WAT', 'IMGN', 'AVDL', 'CQP', 'MA', 'FNMA', 'DAO', 'W', 'TBPH', 'APAM', 'MKD', 'LBTYA', 'WKHS', 'AMRS', 'CLX', 'RCM', 'MTD', 'MAR', 'ENPH', 'REPH', 'FMCC', 'RST', 'INSG', 'DOMO', 'MBT', 'UPS', 'STX', 'CTXS', 'AZUL', 'HSC', 'CROX', 'RAMP', 'QCOM', 'TGI', 'THC', 'CLF', 'CRON', 'DBD', 'AVNT', 'ALSN', 'ITW', 'NTAP', 'CMPR', 'BKNG', 'CDW', 'RHP', 'ATKR', 'SMG', 'TPL', 'POOL', 'BWXT', 'NVAX', 'FICO', 'AMGN', 'SPG', 'NVO', 'BLMN'],
	_2021=['WBK', 'PIXY', 'MYOV', 'CYDY', 'DOMO', 'NTNX', 'QTNT', 'WMG', 'GMBL', 'TLRDQ', 'LW', 'NTAP', 'LOW', 'AVCT', 'CLX', 'VMW', 'ROK', 'BURL', 'QCOM', 'HRB', 'FICO', 'JE', 'NLOK', 'AAPL', 'CPB', 'ORCL', 'CHWY', 'MTOR', 'JWN', 'TJX', 'BAH', 'STX', 'ROST', 'SMG', 'FDS', 'HOLX', 'ATKR', 'LRCX', 'KLAC', 'CLCT', 'BBY', 'ADP', 'HLNE', 'BF.B', 'PLAY', 'EA', 'INTU', 'PAYX', 'WDFC', 'LULU', 'MSFT', 'MXIM', 'BR', 'ULTA', 'LOGI', 'GOOS', 'BIG', 'HDS', 'ACN', 'LB', 'FIZZ', 'CPRT', 'CSCO', 'WSM', 'XLNX', 'V', 'BERY', 'PLCE', 'NKE', 'GIS', 'TGT', 'PG', 'CTAS', 'RMD', 'DCI', 'DECK', 'MBUU', 'FIVE', 'BKE', 'INFY', 'AQUA', 'NVDA', 'DG', 'APPS', 'KMX', 'FOXF', 'EMR', 'CRVL', 'EXPO', 'EGAN', 'COST', 'JBSS', 'BABA', 'RPM', 'SCS', 'DHI', 'PINC', 'SPWH', 'WMT', 'MRVL'],
)

# 39th day: low evebitda: 0.0046; positive every year, during the whole year!
# 29th day: low evebitda: 0.0031; positive every year,
stock_dict_low_evebitda = dict(
	_2016=['CYS', 'BLT', 'QLIK', 'TAHO', 'ARR', 'MXL', 'EHTH', 'WMC', 'PCTY', 'ACHN', 'HES', 'CQP', 'AMTG', 'ABCO', 'BMRN', 'NYCB', 'DATA', 'PANW', 'AAAP', 'CHGG', 'SGRY', 'IONS', 'SHOP', 'DXCM', 'MTGE', 'OFG', 'NOW', 'TWTR', 'CPA', 'WAC', 'TSLA', 'MMYT', 'ALKS', 'CS', 'ANAC', 'ETSY', 'LBRDA', 'TRCO', 'SA', 'HALO', 'AKTX', 'RNG', 'W', 'VRTX', 'N', 'SMLP', 'AKS', 'GLNG', 'BLOX', 'SGMS', 'OMF', 'PARR', 'DWRE', 'CNX', 'TXTR', 'NGD', 'KTWO', 'WTS', 'TWOU', 'OPK', 'ZG', 'FVE', 'SSRM', 'NBIX', 'QTWO', 'SGEN', 'SRNE', 'GOLD', 'HUBS', 'PODD', 'NRE', 'NKTR', 'PFPT', 'CSOD', 'ERII', 'IMPV', 'AVP', 'UTEK', 'GHDX', 'SAFT', 'MGNX', 'LDRH', 'QUOT', 'PACB', 'LNG', 'NG', 'FET', 'TUBE', 'CLLS', 'RMTI', 'ATEX', 'NEWR', 'SPNC', 'ARAY', 'SSP', 'ATRC', 'MXWL', 'BHI', 'SCOR', 'JD'],
	_2017=['OPK', 'RNG', 'GLP', 'FORM', 'IONS', 'CIT', 'CAG', 'CPE', 'ACOR', 'CALD', 'GHDX', 'LPI', 'RES', 'BLOX', 'RRC', 'AUY', 'ARR', 'OCSL', 'CLMT', 'SHOP', 'HMHC', 'EVBG', 'CAVM', 'WMC', 'SA', 'ACTG', 'BL', 'CSOD', 'EXEL', 'DB', 'TWOU', 'ARAY', 'VNDA', 'PANW', 'KTWO', 'DXCM', 'NVRO', 'XEC', 'CECE', 'ACIU', 'TEX', 'GLNG', 'IRWD', 'ALKS', 'VIAV', 'MNTA', 'CS', 'GSAT', 'SPNC', 'GLBS', 'SPXC', 'PFPT', 'PCRX', 'HES', 'FCX', 'TWLO', 'VRNS', 'WDAY', 'RETA', 'VCRA', 'AMD', 'SSNI', 'SGEN', 'PRGS', 'ZG', 'MBI', 'WPX', 'MB', 'MDCO', 'SUN', 'NBR', 'LC', 'HUBS', 'QTWO', 'WIX', 'BNFT', 'FET', 'FI', 'AR', 'NFG', 'NG', 'NOW', 'NR', 'KMT', 'CRSP', 'ATEN', 'CY', 'IRTC', 'KOS', 'BHI', 'CBI', 'FMSA', 'BCEI', 'BCOR', 'CHGG', 'CWEI', 'SQ', 'SHIP', 'ATRC', 'FGEN'],
	_2018=['LACQ', 'CALD', 'BLDP', 'SAIL', 'LPSN', 'SQ', 'TRVG', 'AU', 'DNOW', 'DFRG', 'KTOS', 'ATEN', 'VNET', 'GE', 'MDRX', 'SHOP', 'ONDK', 'PFPT', 'VCRA', 'RDFN', 'TWOU', 'AEGN', 'ALKS', 'RAMP', 'DXCM', 'CSOD', 'MB', 'PCRX', 'COWN', 'EVHC', 'KTWO', 'ZG', 'NKTR', 'HUBS', 'MAG', 'OSTK', 'BL', 'QTWO', 'VRNS', 'PANW', 'AXGN', 'NGD', 'MZOR', 'APOP', 'GLNG', 'SA', 'EVBG', 'NVRO', 'AYX', 'FRGI', 'ROKU', 'APEX', 'THS', 'AMBC', 'ANAB', 'ALTM', 'CLNE', 'INCY', 'SPTN', 'SRPT', 'ALTR', 'MAT', 'APPN', 'EXAS', 'XENT', 'EHTH', 'WINMQ', 'WIX', 'CVNA', 'WDAY', 'SEAS', 'NBIX', 'NVCR', 'SGEN', 'STRP', 'DRQ', 'BGNE', 'VNDA', 'IRTC', 'ADSK', 'MGNX', 'ARGX', 'HZNP', 'TWLO', 'ANGI', 'W', 'ARAY', 'ZEN', 'APTI', 'RNR', 'NEWR', 'SFS', 'BITA', 'LL', 'LC', 'XL', 'JT', 'ATRC', 'BNFT', 'MULE'],
	_2019=['TWO', 'ROKU', 'BMRN', 'MBI', 'USAT', 'CLW', 'WMGI', 'COHU', 'SRDX', 'CVNA', 'KEYS', 'ZG', 'ALKS', 'GSHD', 'EVH', 'CPTA', 'NMRD', 'BL', 'RAMP', 'ATRS', 'SHOP', 'GKOS', 'HUBS', 'DATA', 'IVR', 'TWOU', 'WIX', 'NEWR', 'TRVG', 'QTWO', 'PFPT', 'SLCA', 'ZS', 'ATRC', 'LPSN', 'UPWK', 'VCEL', 'DXCM', 'WDAY', 'NVCR', 'GLNG', 'SMTA', 'MTSI', 'TLRY', 'EB', 'CPLG', 'GLPG', 'TDOC', 'CRON', 'TWLO', 'SPLK', 'CDXS', 'AQ', 'ORC', 'RGS', 'ZEN', 'EGHT', 'ARR', 'RST', 'EXAS', 'NOK', 'SA', 'NIHD', 'DNLI', 'BNFT', 'ADSK', 'EVBG', 'AVEO', 'BRSWQ', 'RMBS', 'VRNS', 'COUP', 'MDGL', 'CNO', 'FGEN', 'INSP', 'ALLK', 'XXII', 'SIBN', 'PSTG', 'HCM', 'MODN', 'RE', 'LC', 'PS', 'SGEN', 'GH', 'XENT', 'TRHC', 'FEYE', 'AMRN', 'RPD', 'INST', 'NVRO', 'ARGX', 'IRTC', 'AXGN', 'HALO', 'FTCH', 'CYRX'],
	_2020=['BYND', 'CIR', 'BILI', 'INSG', 'SHOP', 'ERJ', 'ZS', 'NFE', 'LPI', 'AMRN', 'SXC', 'OFIX', 'ROKU', 'PGNY', 'VCRA', 'PFPT', 'BLFS', 'BAND', 'TXG', 'DX', 'UPWK', 'SCWX', 'NEBLQ', 'MAG', 'TNDM', 'AVLR', 'WDAY', 'ICD', 'TDOC', 'APPS', 'SGEN', 'COUP', 'EVER', 'BITA', 'VCYT', 'SVMK', 'DDD', 'AVNS', 'JE', 'KIDS', 'TLRA', 'CDLX', 'RPD', 'DLX', 'CDXS', 'NG', 'GH', 'QTWO', 'SPLK', 'MODN', 'TDW', 'ZG', 'EVBG', 'AAWW', 'WIX', 'VCEL', 'AUDC', 'DVN', 'SA', 'ZEN', 'DLTR', 'OII', 'OKTA', 'NWL', 'ATEN', 'EXAS', 'SUPV', 'MBI', 'LOVE', 'PAR', 'FGEN', 'SMAR', 'ATRC', 'FSLY', 'ESTC', 'NET', 'ADTN', 'TEAM', 'MDXG', 'ADPT', 'INSP', 'CFX', 'MDB', 'NLY', 'KOD', 'LN', 'PEGA', 'UTHR', 'TWLO', 'GKOS', 'MOS', 'APPN', 'THS', 'EIDX', 'AXSM', 'IOTS', 'SKY', 'LMPX', 'BREW', 'FEYE'],
	_2021=['MODN', 'HAIN', 'DCT', 'STZ', 'WDAY', 'COUP', 'APHA', 'WMG', 'BILL', 'ZS', 'TEAM', 'PHR', 'SPLK', 'DOCU', 'CRWD', 'HOME', 'SFIX', 'OKTA', 'CREE', 'SMAR', 'MDB', 'CAMP', 'DT', 'PLAN', 'AMBA', 'CHWY', 'AINV', 'CSII', 'MSGS', 'ARWR', 'PSTG', 'MDP', 'ASH', 'BMRA', 'COTY', 'SCHL', 'SMFG', 'MDLA', 'PD', 'ESTC', 'BOX', 'MCFT', 'ENTA', 'PRSP', 'ZUO', 'EXTR', 'IBIO', 'TWST', 'EQOS', 'TPR', 'WORK', 'ATEX', 'KLXE', 'AHPI', 'VSTO', 'AYTU', 'HP', 'CLDR', 'APEX', 'MESO', 'YEXT', 'NWSA', 'IMRN', 'LOVE', 'CASH', 'AGYS', 'CYDY', 'EGHT', 'BBBY', 'IMVT', 'RAMP', 'GENE', 'AVCT', 'AKTS', 'EXPR', 'PLL', 'AGX', 'GMBL', 'MUFG', 'COHR', 'CAH', 'PSTI', 'MEIP', 'QTNT', 'MYGN', 'KERN', 'JILL', 'REPL', 'NTNX', 'SCSC', 'JE', 'DOMO', 'XAIR', 'NNVC', 'CGC', 'PDCO', 'ABC', 'DXC', 'GME', 'RGS'],
)

