# TODO: 2021-09-16: chris.flesche Select best increase by month, then get recommendations for following month;


# 39th day: low pe above 30: Annualized return: -0.09: overall mean roi: 0.0018
# 29th day: low pe above 30: Annualized return: 0.67: overall mean roi: 0.0024
# 39th day: low pe:
# 29th day: low pe:
stock_dict_low_pe_above_30 = dict(
	_2016_p0={'start_dt': '2016-01-01', 'end_dt': '2016-12-31', 'period': '0', 'tickers': ['GTN', 'HUN', 'EL', 'PAA', 'MKC', 'LII', 'PG', 'BDC', 'RPAI', 'ROLL', 'CVA', 'AZN', 'PMC', 'FICO', 'GOLD1', 'QIHU', 'CPSI', 'NSP', 'EFX', 'EGOV', 'DMND', 'PRIM', 'BSTC', 'ECOL', 'STE1', 'PSXP', 'A', 'SBUX', 'IDTI', 'TNC', 'MLM', 'ARMK', 'MTSI', 'JJSF', 'SHPG', 'CMG', 'NCLH', 'GTT', 'EVHC', 'EBSB', 'WM', 'NSA', 'ATVI', 'SCHW', 'STL', 'SF', 'AMAG', 'MTW', 'BCPC', 'AGNC', 'MDVN', 'USPH', 'APAM', 'RXN', 'ETFC', 'CE', 'BWLD', 'MPLX', 'ANSS', 'SIX', 'DM', 'FI', 'GHL', 'BMI', 'FBP', 'AZPN', 'CVGW', 'SPG', 'DISH', 'MSCI', 'PNY', 'WY', 'LNN', 'SYY', 'FR', 'CRS', 'MRK', 'PNRA', 'MNRO', 'BANR', 'PRAH', 'FLWS', 'AGN', 'RCL', 'WEX', 'NNN', 'BXP', 'NWL', 'PPL', 'ROCK', 'ECL', 'BIP', 'ANIP', 'GOOGL', 'XRAY', 'TECH', 'AVB', 'AM2', 'SJM', 'VSTO']},
	_2017_p0={'start_dt': '2017-01-01', 'end_dt': '2017-12-31', 'period': '0', 'tickers': ['ORA', 'LULU', 'HTLD', 'SYY', 'AF', 'MAT', 'ANSS', 'EL', 'DRE', 'RXN', 'UE', 'TXRH', 'MCHP', 'APAM', 'CTRE', 'MKSI', 'MANH', 'ARG', 'SPG', 'PDM', 'HSY', 'SCI', 'COST', 'QUAD', 'IPAR', 'A', 'MTRN', 'ADTN', 'COHR', 'BWLD', 'FDC', 'PRFT', 'APLE', 'TRQ', 'RUSHA', 'MSEX', 'XRAY', 'BCR', 'ANH', 'KHC', 'PZZA', 'SYT', 'STOR', 'ECOL', 'COO', 'MDT', 'AAWW', 'LDOS', 'DPZ', 'EQGP', 'CXP', 'RSG', 'SFM', 'MWA', 'PRLB', 'LHX', 'SCCO', 'WCC', 'GLOB', 'CRTO', 'ZTO', 'KRO', 'RCI', 'WDFC', 'YDKN', 'CHUY', 'KIM', 'AEG', 'ZTS', 'COMM', 'ARMK', 'HOLX', 'QSR', 'NNN', 'SWIR', 'CMC', 'ABAX', 'EXPO', 'FB', 'CZR', 'AAON', 'HRC', 'LFUS', 'PSA', 'WNR', 'SCHL', 'MLM', 'EPAM', 'ISRG', 'GIMO', 'BMI', 'FIVE', 'CWT', 'ATRI', 'PNRA', 'MNRO', 'SCMP', 'SNPS', 'OCFC', 'TMUS']},
	_2018_p0={'start_dt': '2018-01-01', 'end_dt': '2018-12-31', 'period': '0', 'tickers': ['LMNX', 'MED', 'BHLB', 'COL', 'SON', 'MORN', 'ASML', 'GGG', 'MKC', 'NNN', 'NLSN', 'GMS', 'TDG', 'ETSY', 'HUBB', 'CDK', 'AGCO', 'SYX', 'STOR', 'HSY', 'PEB', 'DXPE', 'AZN', 'AWR', 'CLH', 'BECN', 'UCBI', 'PPBI', 'CR', 'ELF', 'AET', 'PSA', 'JJSF', 'CLDT', 'FCE.A', 'IBKC', 'WABC', 'EXK', 'AXP', 'QCOM', 'MGPI', 'TEX', 'COO', 'CBPO', 'SCHW', 'TER', 'ATRI', 'A', 'TMHC', 'RGC', 'FB', 'VMI', 'FICO', 'RMD', 'ELY', 'CFX', 'WCN', 'IPAR', 'CL', 'V', 'KAMN', 'LNCE', 'MTCH', 'ROLL', 'SRNE', 'THRM', 'BC', 'BUFF', 'LXFT', 'AHH', 'WES2', 'TCX', 'EXTN', 'IPGP', 'PINC', 'AXTI', 'GOLD1', 'ABAX', 'SKX', 'FRT', 'TREX', 'ISBC', 'SIR', 'NCR', 'REGN', 'HHC', 'HOME', 'MSCC', 'FOXF', 'BRKS', 'ITW', 'MAR', 'FBC', 'RES', 'GPN', 'ZAGG', 'TMO', 'GGP', 'WHR', 'CVGW']},
	_2019_p0={'start_dt': '2019-01-01', 'end_dt': '2019-12-31', 'period': '0', 'tickers': ['PRFT', 'RPAI', 'RMR', 'NEPT', 'ATR', 'CGNX', 'USG', 'SINA', 'PBF', 'BECN', 'TMO', 'VNO', 'SITE', 'HDB', 'SNPS', 'VRSN', 'FSLR', 'AON', 'IIVI', 'DAR', 'HLF', 'IRT', 'SCSC', 'MBUU', 'AM', 'AMED', 'KO', 'ADP', 'OFC', 'BR', 'PJT', 'EXLS', 'PRGS', 'CPRT', 'DD', 'MRK', 'UI', 'WMT', 'SRE', 'ALV', 'BCPC', 'MOG.A', 'BG', 'CUBE', 'COST', 'CME', 'TECD', 'TRNO', 'STAG', 'FDS', 'CLB', 'SHW', 'MA', 'THRM', 'AKAM', 'WPX', 'CATO', 'RAVN', 'TPR', 'FIVE', 'ARE', 'GPRE', 'URBN', 'DCI', 'WAIR', 'AU', 'WDC', 'BLL', 'KELYA', 'WELL', 'PQG', 'ANIP', 'MDP', 'IDCC', 'ROLL', 'CF', 'MNR', 'NTES', 'KNSL', 'CWT', 'ADC', 'RYN', 'OSUR', 'WST', 'MXIM', 'GDOT', 'CDNS', 'MDT', 'HCSG', 'PSMT', 'EA', 'WCN', 'TIF', 'SXI', 'ARGO', 'WEX', 'EXPO', 'APC', 'LFC', 'RDY']},
	_2020_p0={'start_dt': '2020-01-01', 'end_dt': '2020-12-31', 'period': '0', 'tickers': ['ROLL', 'TTC', 'CPRT', 'NVMI', 'TWNK', 'NKE', 'WHD', 'MEDP', 'IFF', 'ST', 'WRLD', 'ES', 'IBP', 'ATVI', 'BMY', 'BF.B', 'KEYS', 'ATR', 'AEM', 'RHP', 'STOR', 'IEX', 'BR', 'MNST', 'VMC', 'COO', 'AMCR', 'EQR', 'TNC', 'EPR', 'RBA', 'ADP', 'MSEX', 'CSV', 'NEE', 'SPGI', 'MGEE', 'OSIS', 'HDB', 'MCO', 'TDY', 'SEDG', 'FB', 'MEET', 'NI', 'MLNX', 'MSI', 'ESI', 'AON', 'CHE', 'MLCO', 'TTWO', 'IAA', 'LBRT', 'PSDO', 'ARES', 'MMC', 'TUP', 'TV', 'KDP', 'POOL', 'CKH', 'EXR', 'AZPN', 'JRVR', 'PAGS', 'LRN', 'MGP', 'MTN', 'CBPO', 'DLTH', 'CMP', 'PXD', 'EHTH', 'CALM', 'GFI', 'TRIP', 'LFUS', 'BFS', 'BP', 'LOW', 'FND', 'EQM', 'WMB', 'CME', 'MKC', 'PSN', 'MEOH', 'PHG', 'IHG', 'SXT', 'PE', 'TITN', 'NATI', 'IRM', 'UGI', 'MGLN', 'TR', 'SPXC', 'MTD']},
	_2021_p0={'start_dt': '2021-01-01', 'end_dt': '2021-12-31', 'period': '0', 'tickers': ['QNST', 'SWKS', 'BURL', 'LANC', 'ACN', 'CPRT', 'BR', 'PAHC', 'RPM', 'RAVN', 'WGO', 'ABMD', 'TTWO', 'GMS', 'ETH', 'FRHC', 'AAPL', 'VFC', 'LAKE', 'KEM', 'EXP', 'BRBR', 'MSFT', 'APD', 'AVAV', 'SXI', 'EAT', 'FDS', 'V', 'ADI', 'BF.B', 'FIVE', 'SR', 'COST', 'GBDC', 'RGLD', 'THR', 'LITE', 'INTU', 'TECH', 'EXPO', 'RMD', 'LRN', 'LULU', 'EDU', 'WDFC', 'HLNE', 'EGAN', 'JKHY', 'JCI', 'FLEX', 'DEO', 'OTEX', 'TFSL', 'TDG', 'NSSC', 'SLQT', 'MRCY', 'FICO', 'BRKS', 'DGII', 'NVDA', 'CMTL', 'VAR', 'NKE', 'NEOG', 'REX', 'CTLT', 'HAE', 'SMPL', 'WBA', 'VEEV', 'PTC', 'MTN', 'AMSWA', 'BDX', 'NXGN', 'DSGX', 'JBL', 'VIAV', 'EL', 'AIT', 'MSGE', 'SBUX', 'SMTC', 'STAA', 'SLP', 'HQY', 'CALM', 'PCTY', 'SYY', 'TAK', 'JJSF', 'VRNT', 'CMD', 'AIR', 'DAVA', 'ADSK', 'MOG.A', 'NUAN']},
)

# 39th day: high pe above 30: Annualized return: 0.14: overall mean roi: 0.0024
# 29th day: high pe above 30: Annualized return: 2.33: overall mean roi: 0.0034
 # 39th day: high pe:
# 29th day: high pe:
stock_dict_high_pe_above_30 = dict(
	_2016_p0={'start_dt': '2016-01-01', 'end_dt': '2016-12-31', 'period': '0', 'tickers': ['GERN', 'BSFT', 'CSC', 'INCY', 'PENN', 'PCRX', 'MITT', 'FTI', 'TRU', 'SGRY', 'PEN', 'FTNT', 'YRCW', 'REXR', 'EGRX', 'AMZN', 'SNCR', 'ZOES', 'ATHN', 'GWRE', 'BRC', 'NFLX', 'ULTI', 'EGHT', 'ODP', 'ASEI', 'CX', 'CCOI', 'ALXN', 'FNV', 'CIEN', 'BKI', 'SPSC', 'MINI', 'FCPT', 'ENV', 'LOGI', 'AEM', 'HABT', 'MDSO', 'AVAV', 'FWONA', 'PRGO', 'RKUS', 'MOMO', 'ORC', 'EXAM', 'KRNY', 'FNSR', 'CXO', 'OLED', 'XXIA', 'ACOR', 'PNM', 'NUE', 'SSNC', 'PLAY', 'VIRT', 'GIMO', 'PRTY', 'KMI', 'UNVR', 'ZBH', 'PRE', 'KRG', 'AAWW', 'HAE', 'ATML', 'NBHC', 'MBLY', 'GPRE', 'CCRN', 'BLKB', 'NPTN', 'AVID', 'LOGM', 'SINA', 'IMMR', 'AIR', 'SCU', 'ISLE', 'WB', 'DOC', 'LYG', 'IRC', 'ITRI', 'PAYC', 'HTA', 'CCJ', 'BCR', 'OAK', 'HSC', 'RGEN', 'TVPT', 'ACAT', 'EQT', 'EQIX', 'WES', 'EDR', 'QTS']},
	_2017_p0={'start_dt': '2017-01-01', 'end_dt': '2017-12-31', 'period': '0', 'tickers': ['TAST', 'MPLX', 'PEIX', 'ZLTQ', 'KRG', 'MTSI', 'BSFT', 'SEMG', 'TEAM', 'CVLT', 'BP', 'LOGM', 'KW', 'CHS', 'CUB', 'CEO', 'CC', 'TEVA', 'CMG', 'ACHC', 'ECHO', 'HAWK', 'TRP', 'SUI', 'ARRS', 'CHU', 'GWRE', 'NFLX', 'WEB', 'SUM', 'ZOES', 'MYCC', 'IQV', 'GKOS', 'RAMP', 'LNCE', 'ELF', 'SPSC', 'SALE', 'RMBS', 'TRCO', 'ERIC', 'HSTM', 'OFIX', 'BIO', 'SWC', 'OFC', 'WEX', 'GTT', 'CG', 'EQIX', 'ATHN', 'MORE', 'CONE', 'ICHR', 'INCY', 'ULTI', 'DEA', 'ANIP', 'BSM', 'NXPI', 'AXTA', 'SBAC', 'WAGE', 'VSAT', 'NXGN', 'FTNT', 'SHPG', 'PCH', 'HPP', 'ITGR', 'MSGN', 'AMZN', 'SITC', 'SU', 'SNCR', 'ERII', 'RP', 'SPH', 'ORC', 'GPT', 'BUD', 'MITK', 'AG', 'CHEF', 'PEN', 'CRS', 'KMPR', 'VRNT', 'LN', 'BKI', 'OMCL', 'ALRM', 'CCOI', 'TGE', 'HSBC', 'PTR', 'PTHN', 'USCR', 'RAVN']},
	_2018_p0={'start_dt': '2018-01-01', 'end_dt': '2018-12-31', 'period': '0', 'tickers': ['IONS', 'FTAI', 'WWW', 'RP', 'ASH', 'IT', 'SPSC', 'QTS', 'FLS', 'NSA', 'LRN', 'AM', 'KMI', 'RAD', 'HLNE', 'MCRN', 'VIRT', 'SID', 'EURN', 'BIP', 'PTC', 'MELI', 'SUM', 'PTEN', 'WAT', 'EPC', 'ABM', 'NYT', 'PEN', 'IMAX', 'RAMP', 'ACIW', 'ULTI', 'CARG', 'BSIG', 'GRA', 'LX', 'MRVL', 'IR', 'CCOI', 'PCTY', 'LGF.B', 'DECK', 'BSX', 'ZBRA', 'NCSM', 'GWRE', 'JNJ', 'AAXN', 'USM', 'TREE', 'ALB', 'PSDO', 'TTEC', 'SRCL', 'AMPH', 'FTNT', 'BCO', 'LGND', 'GOL', 'AXTA', 'ORC', 'DEA', 'ABT', 'GRPN', 'WINS', 'RH', 'ANF', 'HSC', 'AMZN', 'SBAC', 'QGEN', 'ATVI', 'EQC', 'HR', 'CRY', 'CRM', 'WPM', 'POST', 'OFIX', 'KO', 'VSAT', 'EQIX', 'OPI', 'NFLX', 'BGFV', 'MTW', 'CCI', 'APPF', 'CHCT', 'SWIR', 'VRTX', 'DD', 'NAV', 'KRG', 'DLR', 'PUMP', 'COG', 'CWH', 'ZNGA']},
	_2019_p0={'start_dt': '2019-01-01', 'end_dt': '2019-12-31', 'period': '0', 'tickers': ['AXS', 'CONE', 'EHTH', 'WP', 'CSCO', 'PODD', 'GNL', 'PDCE', 'CEVA', 'PEN', 'CSII', 'ATUS', 'AVX', 'SUM', 'SAIL', 'IMBI', 'PZZA', 'BDX', 'MCK', 'SWCH', 'SJR', 'NSA', 'ENV', 'SBAC', 'NXGN', 'PEGA', 'UNIT', 'TGP', 'HAIN', 'AQUA', 'CATM', 'PGRE', 'ACIA', 'NBIX', 'MEET', 'ALXN', 'STAA', 'AMH', 'APA', 'PTC', 'CXP', 'Y', 'CRM', 'SSRM', 'ADSW', 'ZNGA', 'EPAY', 'PAAS', 'EIGI', 'NUVA', 'BEP', 'FTAI', 'ANF', 'NEO', 'CWST', 'TERP', 'LBRDA', 'DLB', 'QTNA', 'SMLP', 'SYNH', 'DEA', 'ICUI', 'CUB', 'CONN', 'TPIC', 'NTAP', 'TDC', 'GDDY', 'ACB', 'PLXS', 'FARO', 'RGEN', 'OSPN', 'SJI', 'ELAN', 'PRNB', 'RP', 'AYX', 'TCMD', 'BRK.B', 'ALTR', 'INCY', 'CHCT', 'RGS', 'ULTI', 'GCP', 'ALRM', 'CARB', 'ABMD', 'VMW', 'HSKA', 'INXN', 'SHAK', 'JBGS', 'SSNC', 'ANGI', 'RCII', 'CMPR', 'MAC']},
	_2020_p0={'start_dt': '2020-01-01', 'end_dt': '2020-12-31', 'period': '0', 'tickers': ['CWK', 'CEVA', 'CIIC', 'AAXN', 'PRA', 'ALUS', 'NOK', 'SUM', 'SBSW', 'SFTW', 'QTS', 'DRQ', 'ONTO', 'PODD', 'CVLT', 'F', 'MCK', 'PRMW', 'BAND', 'CRY', 'MSGS', 'VIAV', 'DOYU', 'NLOK', 'MYGN', 'LNN', 'GSHD', 'GWRE', 'SWCH', 'PEAK', 'INOV', 'NEO', 'PNTG', 'WTTR', 'E', 'BANC', 'BLKB', 'MMSI', 'SWI', 'FIS', 'NBIX', 'BIP', 'AMG', 'CXP', 'SLAB', 'FMX', 'UMH', 'DEA', 'COKE', 'AYX', 'RXN', 'RGEN', 'TREE', 'VRT', 'CY', 'HTA', 'BKR', 'EPAY', 'FOE', 'UEIC', 'DXCM', 'CSTL', 'CVA', 'GO', 'LBRDA', 'GSX', 'UNIT', 'AUDC', 'SBAC', 'CONE', 'LINX', 'SSTI', 'ELAN', 'MNRL', 'IQV', 'BCO', 'WPM', 'KTOS', 'AMD', 'OPRT', 'BIDU', 'NXPI', 'GMRE', 'EZPW', 'AIR', 'COLD', 'ZNGA', 'HPP', 'KRUS', 'VRTU', 'VICR', 'HPK', 'FWONA', 'GKOS', 'VFF', 'GPN', 'KLIC', 'ATUS', 'KRNT', 'MNR']},
	_2021_p0={'start_dt': '2021-01-01', 'end_dt': '2021-12-31', 'period': '0', 'tickers': ['POST', 'EPAC', 'CRM', 'ZM', 'CRS', 'MLAB', 'SRDX', 'NUAN', 'MOG.A', 'ADSK', 'DAVA', 'AIR', 'CMD', 'VRNT', 'JJSF', 'TAK', 'SYY', 'PCTY', 'CALM', 'HQY', 'SLP', 'STAA', 'SMTC', 'SBUX', 'MSGE', 'AIT', 'EL', 'VIAV', 'JBL', 'DSGX', 'NXGN', 'BDX', 'AMSWA', 'MTN', 'PTC', 'VEEV', 'WBA', 'SMPL', 'HAE', 'CTLT', 'REX', 'NEOG', 'NKE', 'VAR', 'CMTL', 'NVDA', 'DGII', 'BRKS', 'FICO', 'MRCY', 'SLQT', 'NSSC', 'TDG', 'TFSL', 'OTEX', 'DEO', 'FLEX', 'JCI', 'JKHY', 'EGAN', 'HLNE', 'WDFC', 'EDU', 'LULU', 'LRN', 'RMD', 'EXPO', 'TECH', 'INTU', 'LITE', 'THR', 'RGLD', 'GBDC', 'COST', 'SR', 'FIVE', 'BF.B', 'ADI', 'V', 'FDS', 'EAT', 'SXI', 'AVAV', 'APD', 'MSFT', 'BRBR', 'EXP', 'KEM', 'LAKE', 'VFC', 'AAPL', 'FRHC', 'ETH', 'GMS', 'TTWO', 'ABMD', 'WGO', 'RAVN', 'RPM', 'PAHC']},
)

# 39th day: high divyield: 39 days: Annualized return: -0.53: overall mean roi: 0.0007
# 29th day: high divyield: 29 days: Annualized return: -0.33: overall mean roi: 0.0022
# 39th day: high divyield:
# 29th day: high divyield:
stock_dict_high_divyield = dict(
	_2016_p0={'start_dt': '2016-01-01', 'end_dt': '2016-12-31', 'period': '0', 'tickers': ['SPXC', 'NI', 'EBAY', 'AROC', 'OA', 'BAX', 'GHC', 'MEMP', 'LINE', 'VNRSQ', 'EPC', 'A', 'TOO', 'KLAC', 'MCEP', 'TRS', 'TGNA', 'BWXT', 'NRF', 'WINMQ', 'CEQP', 'PPC', 'TROX', 'WMC', 'ETP', 'HSNI', 'TRCO', 'CG', 'TGP', 'VTR', 'BTE', 'ARLP', 'ORC', 'CPTA', 'NYMT', 'ERF', 'XAN', 'ARR', 'MITT', 'TK', 'AHT', 'PNNT', 'GMLP', 'CPLP', 'MCC', 'PDLI', 'TKC', 'SSP', 'CVRR', 'TAL1', 'PSEC', 'UAN', 'GLP', 'VIV', 'CYS', 'MMLP', 'ALDW', 'EC', 'ADP', 'RESI', 'NTI', 'CIG', 'NRZ', 'HTS', 'CPG', 'AGNC', 'PMT', 'CIM', 'SCU', 'CLMT', 'ANH', 'VNO', 'IVR', 'CMO', 'KMI', 'MTGE', 'APO', 'NLY', 'OCSL', 'TWO', 'MAS', 'DCP', 'SXC', 'TRGP', 'WPZ', 'MFA', 'SMLP', 'BX', 'PAA', 'BBDC', 'TGH', 'ACTG', 'PPL', 'OPI', 'MBT', 'GLNG', 'SHO', 'ARCC', 'SIR', 'JE']},
	_2017_p0={'start_dt': '2017-01-01', 'end_dt': '2017-12-31', 'period': '0', 'tickers': ['MSGN', 'MTW', 'RRD', 'CSC', 'HPQ', 'BKS', 'SYNT', 'VIAV', 'CYH', 'VC', 'FCAU', 'FCPT', 'YUM', 'CUZ', 'NGL', 'DHR', 'LDOS', 'GRA', 'EQR', 'EURN', 'CLMT', 'DHT', 'ETP', 'IHG', 'NAT', 'MMLP', 'ORC', 'AWI', 'PNNT', 'FRO', 'MCC', 'CPLP', 'NYMT', 'PPC', 'AINV', 'CIM', 'ARR', 'CPTA', 'PLNT', 'WMC', 'TNK', 'CYS', 'JWN', 'PSEC', 'DRI', 'AGNC', 'OCSL', 'CEQP', 'SXCP', 'SUN', 'USAC', 'SFL', 'BKCC', 'NLY', 'PHI', 'UAN', 'NRZ', 'ANH', 'PMT', 'ITGR', 'ARI', 'MITT', 'CG', 'STNG', 'TDW', 'IVR', 'TWO', 'DLNG', 'PRA', 'SNR', 'MFA', 'SPH', 'BBDC', 'MTGE', 'STX', 'CIG', 'IEP', 'WING', 'WPG', 'NMFC', 'MDCA', 'GMLP', 'FIG', 'GLP', 'WDR', 'APAM', 'UNIT', 'AMID', 'LADR', 'AHGP', 'CMO', 'GLOP', 'CMTL', 'ARCC', 'EEP', 'QIWI', 'GNL', 'CCP', 'SMLP', 'OPI']},
	_2018_p0={'start_dt': '2018-01-01', 'end_dt': '2018-12-31', 'period': '0', 'tickers': ['DRYS', 'MACK', 'ASH', 'HPE', 'TGNA', 'ALEX', 'CKH', 'HCC', 'FNF', 'HLT', 'VNO', 'TWO', 'APTV', 'NAT', 'CTXS', 'CLNY', 'CPTA', 'ORC', 'TDG', 'CNX', 'BBDC', 'WINMQ', 'TERP', 'PK', 'TRCO', 'NS', 'JCI', 'MET', 'WPG', 'SNR', 'SXCP', 'SPH', 'CIM', 'XRX', 'UNIT', 'NYMT', 'NCMI', 'CNSL', 'MCC', 'CYS', 'WMC', 'PSEC', 'ETP', 'EEQ', 'GEL', 'EEP', 'FSK', 'PMT', 'SUN', 'IEP', 'SMLP', 'MDC', 'NRZ', 'ANH', 'CHMI', 'PNNT', 'AGNC', 'MITT', 'PRA', 'SFL', 'MFA', 'BPL', 'NLY', 'GMLP', 'ENLK', 'ARI', 'NMFC', 'VAR', 'MTGE', 'AINV', 'ARCC', 'GNL', 'AHGP', 'HTGC', 'ARLP', 'TCPC', 'PAA', 'OPI', 'CEQP', 'OHI', 'SBRA', 'CMO', 'MHLD', 'IVR', 'STWD', 'ARR', 'LADR', 'NEWT', 'ENBL', 'PAGP', 'TSLX', 'TNK', 'DCP', 'NEWM', 'OCSL', 'CODI', 'BKE', 'VOD', 'SITC', 'AB']},
	_2019_p0={'start_dt': '2019-01-01', 'end_dt': '2019-12-31', 'period': '0', 'tickers': ['RENN', 'KDP', 'WYND', 'EQT', 'ALV', 'PNR', 'CYOU', 'TRN', 'SITC', 'DOV', 'HCC', 'OPI', 'SMTA', 'SMLP', 'SRC', 'WPG', 'GMLP', 'AMC', 'SNR', 'RFP', 'OSB', 'ORC', 'FSK', 'USAC', 'PCH', 'VGR', 'BPL', 'CNSL', 'UNIT', 'BKE', 'TEO', 'WMC', 'NGG', 'TWO', 'APAM', 'MC', 'NGL', 'PEI', 'NRZ', 'BGCP', 'CPTA', 'NS', 'SEMG', 'MCC', 'NYMT', 'VEDL', 'OMI', 'SFL', 'NEWM', 'BEN', 'PBI', 'ANDX', 'VEON', 'ATUS', 'IEP', 'AGNC', 'SNP', 'NLY', 'GNL', 'SUN', 'MIC', 'WRI', 'AHT', 'NBR', 'MFA', 'ARLP', 'DCP', 'MBT', 'IVR', 'CATO', 'AINV', 'GEL', 'HTGC', 'PSEC', 'ABR', 'CIM', 'ENLC', 'ARR', 'CNS', 'TCPC', 'ARI', 'SBRA', 'BKS', 'NCMI', 'NMFC', 'GLOP', 'PK', 'AB', 'SPH', 'WING', 'TRGP', 'CLNC', 'PMT', 'TSLX', 'LADR', 'EQM', 'VET', 'ARCC', 'STWD', 'QUAD']},
	_2020_p0={'start_dt': '2020-01-01', 'end_dt': '2020-12-31', 'period': '0', 'tickers': ['KAR', 'DD', 'NTGR', 'SMLP', 'WPG', 'BTU', 'HSIC', 'QUAD', 'HCC', 'DXC', 'LYB', 'SATS', 'CNSL', 'ARLP', 'ENLC', 'VMW', 'IRWD', 'PUK', 'ORC', 'PEI', 'VET', 'EQM', 'TGS', 'BAK', 'AM', 'NVS', 'GLOP', 'GME', 'FMC', 'FCAU', 'ETRN', 'IEP', 'CGBD', 'ENBL', 'UAN', 'NYMT', 'DCP', 'CLNC', 'WES', 'FSK', 'NRZ', 'MITT', 'CHMI', 'HEP', 'JE', 'ARR', 'WMC', 'BKS', 'AHT', 'DX', 'TEO', 'SFUN', 'TARO', 'AINV', 'VEON', 'VGR', 'GEO', 'USAC', 'BSM', 'TRIP', 'BKE', 'SNP', 'TWO', 'CPTA', 'AGNC', 'NGL', 'IVR', 'NLY', 'MAC', 'WERN', 'PSEC', 'AMC', 'SUN', 'GEL', 'EQC', 'ADT', 'MFA', 'APAM', 'MPLX', 'RC', 'TCPC', 'MC', 'SPH', 'ARI', 'TPVG', 'GCI', 'GLOG', 'DHC', 'EFC', 'TUP', 'NMFC', 'EC', 'VEDL', 'REPH', 'VOD', 'TGE', 'CIM', 'SFL', 'NWG', 'SKT']},
	_2021_p0={'start_dt': '2021-01-01', 'end_dt': '2021-12-31', 'period': '0', 'tickers': ['JILL', 'NLOK', 'NGL', 'MSGS', 'AINV', 'JE', 'HP', 'SPH', 'PSEC', 'VFC', 'MDP', 'MSM', 'TLYS', 'GBDC', 'GME', 'M', 'BKE', 'CHS', 'COTY', 'CATO', 'OCSL', 'TPR', 'BNS', 'TFSL', 'CFFN', 'CM', 'JBSS', 'NUAN', 'VOD', 'DBI', 'UVV', 'ETH', 'PDCO', 'TDG', 'BMO', 'TD', 'RY', 'DXC', 'KSS', 'SJR', 'HRB', 'BBBY', 'VEDL', 'SIG', 'GWB', 'BHP', 'PLT', 'GPS', 'STX', 'NGG', 'BEN', 'LB', 'ANF', 'MNR', 'SMG', 'WBA', 'EAT', 'SR', 'NJR', 'MOV', 'AMCR', 'WMS', 'WBK', 'EBF', 'NTAP', 'BIG', 'HMC', 'NFG', 'WAFD', 'FL', 'JWN', 'UGI', 'RL', 'CBT', 'GBX', 'MATW', 'SCHN', 'PLCE', 'WRK', 'AEO', 'PETS', 'CAH', 'SCS', 'CBRL', 'KRNY', 'WDC', 'PAYX', 'DRI', 'CAE', 'LM', 'CRS', 'MXIM', 'WOR', 'AVT', 'SYY', 'GIS', 'CSCO', 'INFY', 'EMR', 'ENR']},
)

# 39th day: low divyield: 39 days: Annualized return: 0.12: overall mean roi: 0.0030
# 29th day: low divyield: 29 days: Annualized return: 1.78: overall mean roi: 0.0034
# 39th day: low divyield:
# 29th day: low divyield:
stock_dict_low_divyield = dict(
	_2016_p0={'start_dt': '2016-01-01', 'end_dt': '2016-12-31', 'period': '0', 'tickers': ['ENTG', 'S', 'SA', 'SAAS', 'GERN', 'GEOS', 'GENE', 'SAGE', 'GHDX', 'SAIA', 'GDDY', 'SALE', 'SALT', 'GBT', 'SAM', 'SANM', 'SATS', 'GDOT', 'G', 'RXN', 'GIMO', 'RRGB', 'RSPP', 'RSTI', 'GLUU', 'RTEC', 'GLRE', 'RUN', 'GIB', 'GLPG', 'GLOB', 'RVNC', 'GLFMQ', 'GLBR', 'RWLK', 'GKOS', 'RXDX', 'RUSHA', 'FWP', 'FWONA', 'FVE', 'SCLN', 'FLXN', 'FLWS', 'FLTX', 'FLT', 'FLOW', 'FLEX', 'FMI', 'FLDM', 'FIT', 'FISV', 'SCOR', 'SCSC', 'SDRL1', 'FGEN', 'FFIV', 'SCMP', 'FN', 'FNSR', 'FOE', 'SAVE', 'SBAC', 'FTNT', 'FTK', 'FTI1', 'FTI', 'SBH', 'FSLR', 'SBS', 'FRSH', 'FRPT', 'SC', 'FPRX', 'SCAI', 'FORM', 'FOR', 'FOLD', 'GMED', 'GNCMA', 'GNK', 'RPXC', 'RENT', 'HNT', 'HNGR', 'HMSY', 'HMST', 'HMHC', 'REXX', 'HOLX', 'HLX', 'RFP', 'RGEN', 'HHC', 'HGEN', 'RGLS', 'RGNX', 'RGS', 'HLF', 'RENN']},
	_2017_p0={'start_dt': '2017-01-01', 'end_dt': '2017-12-31', 'period': '0', 'tickers': ['ZYNE', 'PRAH', 'PRFT', 'FCB', 'FBP', 'PRLB', 'FBC', 'FB', 'PRO', 'FARO', 'FANG', 'PRSC', 'PRTA', 'EZPW', 'EYES', 'EXTN', 'FCN', 'PRAA', 'FCX', 'FDC', 'PLUG', 'FIT', 'FISV', 'PLUS', 'PLXS', 'PMC', 'PNK', 'PRTY', 'PNRA', 'FGEN', 'FFIV', 'PODD', 'POST', 'FEYE', 'FET', 'PPBI', 'POAI', 'EXPR', 'PRXL', 'EXLS', 'QDEL', 'ESPR', 'ESNT', 'QEP', 'QGEN', 'ESL', 'ESI', 'ESRX', 'ESGR', 'QLGC', 'ERII', 'QLYS', 'QRTEA', 'QRVO', 'QTWO', 'QUIK', 'ESEA', 'FIVE', 'QCP', 'PYPL', 'EXK', 'EXEL', 'PSTG', 'EXAS', 'PTC', 'EW', 'PTCT', 'ETFC', 'EVHC', 'PTHN', 'EVBG', 'PTLA', 'PVG', 'ETSY', 'PWR', 'PXD', 'EVH', 'FIVN', 'FIZZ', 'PLKI', 'PBYI', 'GCP', 'GCO', 'PCRX', 'PCTY', 'GBT', 'PDCE', 'GDDY', 'PDFS', 'G', 'PE', 'FWONA', 'FVE', 'PEIX', 'PEN', 'FTNT', 'PDS', 'FTK', 'GDOT', 'PBR']},
	_2018_p0={'start_dt': '2018-01-01', 'end_dt': '2018-12-31', 'period': '0', 'tickers': ['ZYNE', 'FBM', 'FBK', 'PLUS', 'FBC', 'FB', 'PLXS', 'FARO', 'PLYA', 'FANG', 'PNK', 'EZPW', 'EYES', 'EYE', 'EXTR', 'EXTN', 'POAI', 'EXPR', 'PLUG', 'PODD', 'FBP', 'FCAU', 'FFIV', 'PHIO', 'PI', 'FEYE', 'FET', 'FENG', 'PINC', 'PIRS', 'PIXY', 'FDC', 'FCX', 'PLAB', 'FCN', 'PLAY', 'FCEL', 'PLNT', 'FCB', 'PLSE', 'FG', 'POST', 'EXK', 'PRTY', 'ESPR', 'ESNT', 'PRXL', 'PSDO', 'ESL', 'ESIO', 'ESI', 'ESGR', 'PSTG', 'PTC', 'ERII', 'PTCT', 'PTE', 'PTLA', 'PUMP', 'PVAC', 'ESRX', 'EXLS', 'PRTK', 'ETFC', 'EXEL', 'PPBI', 'EXAS', 'PPC', 'EW', 'PQG', 'EVRI', 'PRAA', 'EVHC', 'EVH', 'PRAH', 'EVBG', 'PRFT', 'ETSY', 'PRLB', 'PRO', 'PRSC', 'PRTA', 'PVG', 'FGEN', 'PGTI', 'FWONA', 'PACB', 'PAM', 'PANW', 'FTNT', 'FTK', 'PARR', 'PATK', 'FSM', 'FSLR', 'PAY', 'FSCT', 'FRTA', 'PAYC', 'FRPT']},
	_2019_p0={'start_dt': '2019-01-01', 'end_dt': '2019-12-31', 'period': '0', 'tickers': ['KEYW', 'MASI', 'MANH', 'LYV', 'LXRX', 'LXFT', 'LX', 'LULU', 'LTRPA', 'LTHM', 'LTBR', 'LSCC', 'LRN', 'LPSN', 'LPL', 'LPI', 'LOPE', 'LOMA', 'LOCO', 'LNTH', 'LN', 'LL', 'MAT', 'MBI', 'MBUU', 'MCFT', 'MMI', 'MLNX', 'MKL', 'MIME', 'MIK', 'MIDD', 'MHO', 'MHK', 'MGNX', 'MGLN', 'LKQ', 'MGEN', 'MELI', 'MEET', 'MEDP', 'MDSO', 'MDRX', 'MDGL', 'MDCO', 'MDB', 'MD', 'MCRN', 'MESA', 'LJPC', 'LIVN', 'LITE', 'KLXI', 'KGC', 'KEYS', 'KEX', 'KEP', 'KEM', 'KB', 'KANG', 'JT', 'JOE', 'KMX', 'JOBS', 'JKS', 'JILL', 'JELD', 'JD', 'JBLU', 'JAZZ', 'JAG', 'ITRI', 'ITGR', 'ITCI', 'JMEI', 'MMSI', 'KN', 'KODK', 'LILA', 'LHCG', 'LH', 'LGND', 'LGIH', 'LEGH', 'LE', 'LCI', 'LC', 'LBTYA', 'KNSA', 'LBRDA', 'LAUR', 'LASR', 'KURA', 'KTOS', 'KT', 'KRNT', 'KRA', 'KPTI', 'KOS', 'KOP']},
	_2020_p0={'start_dt': '2020-01-01', 'end_dt': '2020-12-31', 'period': '0', 'tickers': ['ZYNE', 'FARO', 'PING', 'PINS', 'PIRRQ', 'EZPW', 'EYE', 'EXTR', 'PINC', 'PIXY', 'EXLS', 'EXK', 'EXEL', 'PKX', 'EXAS', 'PLAB', 'EW', 'EXPR', 'FATE', 'FB', 'PI', 'FFIV', 'PEN', 'FEYE', 'FET', 'PENN', 'PETQ', 'PFGC', 'PFPT', 'PGEN', 'FCN', 'PGNX', 'PGNY', 'FCEL', 'PGTI', 'PHAT', 'PHIO', 'FBM', 'EVRI', 'PLAN', 'EVOP', 'EVH', 'PRDO', 'PRFT', 'PRLB', 'PRNB', 'PRO', 'PROS', 'PRSC', 'PRTA', 'PRTY', 'EPZM', 'PRVB', 'PS', 'PSN', 'EPC', 'EPAY', 'EPAM', 'EOLS', 'PRAH', 'FGEN', 'ERJ', 'ESGR', 'EVER', 'EVBG', 'PLMR', 'EURN', 'ETSY', 'PLNT', 'PLUG', 'ETNB', 'PLUS', 'PLXS', 'PNTG', 'PODD', 'POST', 'ESTC', 'PPC', 'ESPR', 'ESI', 'PRAA', 'PSNL', 'PDS', 'FI', 'OPRT', 'FTSV', 'FTSI', 'ORBC', 'FTNT', 'ORLY', 'FTDR', 'OPK', 'FTCH', 'OSIS', 'FSM', 'FSLY', 'FSLR', 'OSPN', 'FSCT', 'FRTA']},
	_2021_p0={'start_dt': '2021-01-01', 'end_dt': '2021-12-31', 'period': '0', 'tickers': ['ZUO', 'EPC', 'EQOS', 'ESGC', 'ESTC', 'QNST', 'PTON', 'EXPR', 'EXTR', 'PTC', 'PSTI', 'FFIV', 'FICO', 'FIVE', 'FIZZ', 'PSTG', 'FLEX', 'FLWS', 'FN', 'POST', 'FOXF', 'FRAN', 'FRHC', 'PLXS', 'PLUS', 'GCO', 'GENE', 'PLL', 'PLAN', 'GIII', 'EPAY', 'ENTA', 'QRVO', 'QTNT', 'SGH', 'SFIX', 'DCT', 'LPG', 'DECK', 'DELL', 'SBH', 'SANM', 'DGII', 'RYAAY', 'ROLL', 'RH', 'DLTH', 'DLTR', 'PIXY', 'DOCU', 'RGS', 'REX', 'DSGX', 'DT', 'REPL', 'DY', 'EA', 'RCEL', 'EDU', 'EGAN', 'EGHT', 'RAMP', 'ELF', 'RAD', 'DOMO', 'DAVA', 'GMBL', 'GMS', 'MYGN', 'MUFG', 'MU', 'MTSI', 'MTOR', 'MSGN', 'MSGE', 'MRCY', 'KERN', 'MODN', 'MMYT', 'KLXE', 'ZUMZ', 'KMX', 'MIME', 'MIK', 'LAKE', 'MESO', 'MEIP', 'LCI', 'MDLA', 'LE', 'LGF.B', 'LITE', 'MDB', 'MCFT', 'MBUU', 'LOVE', 'LULU', 'MYOV', 'NEOG', 'NEWR']},
)

# 39th day: high netinccmn: 39 days: Annualized return: -0.03: overall mean roi: 0.0010
# 29th day: high netinccmn: 29 days: Annualized return: 0.08: overall mean roi: 0.0008
# 39th day: high netinccmn:
# 29th day: high netinccmn:
stock_dict_high_netinccmn = dict(
	_2016_p0={'start_dt': '2016-01-01', 'end_dt': '2016-12-31', 'period': '0', 'tickers': ['TLK', 'KEP', 'CIB', 'SHG', 'TM', 'KB', 'MUFG', 'SKM', 'LPL', 'SMFG', 'BCH', 'KT', 'HMC', 'BSAC', 'TSM', 'CAJ', 'PKX', 'CCU', 'TTM', 'IBN', 'CHL', 'HDB', 'WIT', 'AAPL', 'MBT', 'CHT', 'PTR', 'NVO', 'LFC', 'BIDU', 'SNP', 'SSL', 'ITUB', 'BABA', 'BRK.B', 'JPM', 'RDY', 'PHI', 'WFC', 'CEO', 'ASX', 'BBD', 'GILD', 'VZ', 'NVS', 'FMX', 'C', 'XOM', 'GOOGL', 'BAC', 'ERIC', 'T', 'IBM', 'HSBC', 'ABEV', 'MSFT', 'INTC', 'TV', 'CHU', 'KOF', 'ORCL', 'RY', 'GM', 'YNDX', 'SPIL', 'CSCO', 'GSK', 'DIS', 'TFCF', 'BUD', 'CMCSA', 'WBK', 'TD', 'AAL', 'F', 'KO', 'DD', 'UAL', 'MDLZ', 'PG', 'PFE', 'AMGN', 'BNS', 'PM', 'NTES', 'V', 'UBS', 'VOD', 'UNH', 'MS', 'PRU', 'USB', 'GS', 'PEP', 'QCOM', 'MO', 'CVS', 'MET', 'QIWI', 'BA']},
	_2017_p0={'start_dt': '2017-01-01', 'end_dt': '2017-12-31', 'period': '0', 'tickers': ['TLK', 'KEP', 'CIB', 'SHG', 'EC', 'TM', 'KB', 'SKM', 'PKX', 'LPL', 'SMFG', 'MUFG', 'KT', 'BCH', 'BSAC', 'HMC', 'TSM', 'IX', 'CAJ', 'SNE', 'CCU', 'HDB', 'CHL', 'IBN', 'TTM', 'WIT', 'BABA', 'MBT', 'SNP', 'AAPL', 'CHT', 'NVO', 'FMX', 'BRK.B', 'JPM', 'ITUB', 'ASX', 'MSFT', 'WFC', 'RDY', 'PHI', 'GOOGL', 'LFC', 'BBD', 'BAC', 'JNJ', 'C', 'AGN', 'WMT', 'MO', 'GILD', 'SSL', 'VZ', 'T', 'ABEV', 'IBM', 'BIDU', 'NTES', 'CSCO', 'KOF', 'PG', 'RY', 'INTC', 'FB', 'EBR', 'SPIL', 'GM', 'DIS', 'ORCL', 'TD', 'CMCSA', 'PTR', 'XOM', 'AMGN', 'WBK', 'EBAY', 'PFE', 'GS', 'UNH', 'HD', 'BNS', 'PM', 'GE', 'YNDX', 'LN', 'NVS', 'BMA', 'KO', 'PEP', 'TOT', 'RAI', 'V', 'ABBV', 'QCOM', 'USB', 'MS', 'AXP', 'CVS', 'UN', 'UL']},
	_2018_p0={'start_dt': '2018-01-01', 'end_dt': '2018-12-31', 'period': '0', 'tickers': ['TLK', 'EC', 'KB', 'SHG', 'PKX', 'CIB', 'SKM', 'LPL', 'TM', 'KEP', 'SMFG', 'HMC', 'BCH', 'BSAC', 'KT', 'TSM', 'CAJ', 'MUFG', 'CCU', 'HDB', 'CHL', 'IBN', 'WIT', 'SNE', 'TTM', 'MBT', 'VEDL', 'SNP', 'AAPL', 'BRK.B', 'BABA', 'CHT', 'NVO', 'BTI', 'FMX', 'LFC', 'VZ', 'T', 'MSFT', 'CEO', 'ASX', 'PTR', 'ITUB', 'CMCSA', 'JPM', 'PFE', 'WFC', 'SSL', 'XOM', 'BIDU', 'BBD', 'BAC', 'FB', 'PG', 'TEO', 'WMT', 'PHI', 'GRVY', 'RDS.A', 'YPF', 'GOOGL', 'RDY', 'RY', 'KHC', 'UNP', 'NTES', 'UNH', 'TD', 'MO', 'CHTR', 'HSBC', 'CSCO', 'INTC', 'ORCL', 'YNDX', 'CVX', 'BMA', 'DIS', 'TGS', 'PAM', 'RIO', 'TOT', 'BA', 'SNY', 'LN', 'WBK', 'HD', 'BNS', 'PRU', 'EDN', 'NGG', 'F', 'NVS', 'BUD', 'ABEV', 'V', 'UMC', 'CVS', 'PM', 'UN']},
	_2019_p0={'start_dt': '2019-01-01', 'end_dt': '2019-12-31', 'period': '0', 'tickers': ['TLK', 'EC', 'SHG', 'SKM', 'KB', 'CIB', 'TM', 'PKX', 'MUFG', 'HMC', 'SMFG', 'KT', 'BCH', 'BSAC', 'SNE', 'TSM', 'CCU', 'IX', 'CAJ', 'TAK', 'HDB', 'CHL', 'WIT', 'IBN', 'TTM', 'BABA', 'SNP', 'AAPL', 'PTR', 'CEO', 'YNDX', 'NVO', 'YPF', 'CHT', 'FMX', 'GOOGL', 'JPM', 'BIDU', 'ASX', 'CEPU', 'BAC', 'ITUB', 'RDS.A', 'FB', 'CHA', 'INTC', 'XOM', 'WFC', 'T', 'C', 'TGS', 'PAM', 'BBD', 'MSFT', 'VZ', 'JNJ', 'KOF', 'CVX', 'MU', 'VEDL', 'RIO', 'EBR', 'NVS', 'HSBC', 'DIS', 'PEP', 'RY', 'AVGO', 'UNH', 'CMCSA', 'TOT', 'LFC', 'PFE', 'TD', 'ABEV', 'BA', 'V', 'CHU', 'AMZN', 'WMT', 'GS', 'RDY', 'PG', 'BP', 'UL', 'UN', 'BMA', 'VIV', 'SSL', 'IBM', 'HD', 'AMGN', 'BNS', 'MS', 'TEO', 'WBK', 'GM', 'PM', 'NGG', 'EQNR']},
	_2020_p0={'start_dt': '2020-01-01', 'end_dt': '2020-12-31', 'period': '0', 'tickers': ['TLK', 'EC', 'SHG', 'KB', 'CIB', 'TM', 'PKX', 'SNE', 'SKM', 'MUFG', 'KT', 'BSAC', 'HMC', 'SMFG', 'TSM', 'IX', 'HDB', 'CCU', 'TAK', 'CAJ', 'CHL', 'WIT', 'BABA', 'BRK.B', 'CEO', 'LFC', 'SNP', 'AAPL', 'MBT', 'VEDL', 'PTR', 'IBN', 'MSFT', 'NVO', 'JPM', 'GOOGL', 'CHT', 'ITUB', 'BAC', 'NTES', 'INTC', 'BBD', 'C', 'VZ', 'RDY', 'FB', 'ASX', 'WFC', 'PFE', 'RDS.A', 'JNJ', 'XOM', 'T', 'UNH', 'CMCSA', 'RY', 'YNDX', 'TGS', 'PAM', 'KOF', 'JD', 'V', 'ABEV', 'NVS', 'CSCO', 'AMZN', 'LBTYA', 'TD', 'CHU', 'TOT', 'HD', 'ORCL', 'DIS', 'PBR', 'MRK', 'IBM', 'KO', 'BUD', 'MS', 'LLY', 'BHP', 'WUBA', 'BNS', 'MA', 'RIO', 'GS', 'ABBV', 'AMGN', 'EBR', 'PEP', 'COP', 'PM', 'TCOM', 'WBK', 'AXP', 'WMT', 'CVS', 'FCAU', 'USB', 'GM']},
	_2021_p0={'start_dt': '2021-01-01', 'end_dt': '2021-12-31', 'period': '0', 'tickers': ['TM', 'SNE', 'HMC', 'MUFG', 'IX', 'HDB', 'SMFG', 'BABA', 'WIT', 'IBN', 'AAPL', 'MSFT', 'TAK', 'RDY', 'WMT', 'PG', 'TD', 'RY', 'HD', 'CSCO', 'V', 'ORCL', 'BHP', 'BNS', 'VMW', 'QCOM', 'ACN', 'BMO', 'MDT', 'DELL', 'LOW', 'COST', 'NLOK', 'CM', 'TGT', 'TJX', 'EA', 'NVDA', 'MU', 'NKE', 'ADP', 'DHI', 'INFY', 'WBK', 'LRCX', 'GIS', 'TSN', 'EMR', 'APD', 'INTU', 'AZO', 'DG', 'ROST', 'KR', 'CPB', 'MRVL', 'BBY', 'DEO', 'FDX', 'NGG', 'ADI', 'KLAC', 'PH', 'HOLX', 'PAYX', 'ROK', 'STX', 'FOXA', 'CLX', 'SBUX', 'HRL', 'MCK', 'KMX', 'CTAS', 'CAG', 'BF.B', 'DLTR', 'NTAP', 'RJF', 'TXT', 'SWKS', 'BEN', 'XLNX', 'SJM', 'BDX', 'ULTA', 'CPRT', 'KSS', 'SJR', 'EL', 'VFC', 'LDOS', 'MXIM', 'RYAAY', 'LULU', 'JCI', 'RMD', 'AMCR', 'ATO', 'MCHP']},
)


# 39th day: high roe: 39 days: Annualized return: 0.08: overall mean roi: 0.0033
# 29th day: high roe: 29 days: Annualized return: 0.10: overall mean roi: 0.0022
# 39th day: high roe:
# 29th day: high roe:
stock_dict_high_roe = dict(
	_2016_p0={'start_dt': '2016-01-01', 'end_dt': '2016-12-31', 'period': '0', 'tickers': ['BNFT', 'OMER', 'CUDA', 'SRRA', 'AZPN', 'HTGM', 'UNISQ', 'ALLE', 'ARIA', 'KMB', 'CL', 'SNECQ', 'WTI', 'UPLMQ', 'NYMX', 'CCK', 'BEAV', 'XCOOQ', 'INST', 'MAS', 'LII', 'AMD', 'GLBR', 'FUN', 'PBI', 'CLX', 'SONC', 'AVP', 'PAHC', 'UPS', 'MJN', 'SPGI', 'MNKD', 'TOWR', 'AAL', 'OUTR', 'SGMS', 'MO', 'CSTM', 'GSK', 'SIRI', 'AMRN', 'MX', 'HSNI', 'LGND', 'SABR', 'VZ', 'USG', 'CEB', 'SIX', 'SHW', 'PZZA', 'BSIG', 'SEDG', 'ABBV', 'VC', 'STRZA', 'JE', 'BAH', 'UAL', 'TUP', 'EXEL', 'LMT', 'FPRX', 'XOMA', 'AXL', 'NHTC', 'NXST', 'LAZ', 'GILD', 'MACK', 'IBM', 'BZH', 'HW', 'ALDW', 'RPD', 'JMBA', 'AVDL', 'JACK', 'NVO', 'YUM', 'BRSS', 'BA', 'EVTC', 'NTI', 'ASPS', 'SHLX', 'MSI', 'MTG', 'TCO', 'APAM', 'EVH', 'PLKI', 'ALGT', 'VIAB', 'CZR', 'APTV', 'WU', 'PAM', 'LYB']},
	_2017_p0={'start_dt': '2017-01-01', 'end_dt': '2017-12-31', 'period': '0', 'tickers': ['GOGO', 'HALO', 'LII', 'SNES', 'NKTR', 'MCD', 'CRZO', 'AMD', 'KMB', 'ISEE', 'FUN', 'CHRS', 'ZIOP', 'SPGI', 'WIX', 'IRTC', 'IMGN', 'AMCX', 'NOVN', 'CLX', 'BERY', 'BA', 'KOP', 'MO', 'PNK', 'HLF', 'RACE', 'LMT', 'BEAV', 'PLKI', 'TNET', 'ALLE', 'VVV', 'WNRL', 'OMER', 'UPS', 'IMMU', 'KLAC', 'OKE', 'TPX', 'CCK', 'TLND', 'PAHC', 'BUFF', 'HRB', 'SGY', 'PBI', 'EXEL', 'BNFT', 'TCO', 'VLP', 'TUP', 'ABBV', 'AMRN', 'NSP', 'MESG', 'EBAY', 'INTU', 'ISLE', 'TPL', 'BAH', 'NVO', 'APTI', 'HSY', 'BWXT', 'HD', 'NHTC', 'MASI', 'SEE', 'GILD', 'MAR', 'SHW', 'WYND', 'AIRG', 'MTD', 'SSNI', 'NILE', 'ABC', 'DAN', 'NRP', 'TSE', 'EVTC', 'IBM', 'YRD', 'EGRX', 'HSNI', 'MANH', 'BF.B', 'MA', 'MACK', 'BSIG', 'ABG', 'VZ', 'NXST', 'SUPN', 'REN', 'BLDR', 'FDS', 'POOL', 'BETR']},
	_2018_p0={'start_dt': '2018-01-01', 'end_dt': '2018-12-31', 'period': '0', 'tickers': ['KERX', 'MACK', 'FG', 'MYSZ', 'BA', 'CMTA', 'GOVX', 'FUN', 'LII', 'HMNY', 'NAKD', 'KALA', 'KMB', 'AMCX', 'CISN', 'MARA', 'HDP', 'UPS', 'MARK', 'MCFT', 'VRAY', 'WK', 'WBT', 'INPX', 'HTGM', 'PBI', 'AGEN', 'APPN', 'ENR', 'ROKU', 'TPX', 'GSK', 'GCP', 'NVAX', 'AVEO', 'PRO', 'HLF', 'ASPS', 'SPWH', 'OMER', 'CURO', 'LMT', 'CLX', 'CDK', 'IMMU', 'SPGI', 'SEE', 'BNFT', 'WYNN', 'TCO', 'AMRN', 'TNET', 'TPL', 'PGEM', 'AZUL', 'HD', 'CORT', 'CSRA', 'LPI', 'WYND', 'ORLY', 'GOGO', 'QTRX', 'CC', 'VLP', 'CAR', 'CWH', 'HOV', 'BTI', 'CIEN', 'BLMN', 'VZ', 'NSP', 'FSCT', 'HGV', 'ABBV', 'ALLE', 'HSY', 'RYAM', 'MSCI', 'HALO', 'RACE', 'RDFN', 'OEC', 'KLAC', 'ZIOP', 'MBUU', 'LW', 'NPO', 'SECO', 'INTU', 'NVO', 'IMGN', 'LOMA', 'POOL', 'BUFF', 'MO', 'EXEL', 'MTD', 'ALSN']},
	_2019_p0={'start_dt': '2019-01-01', 'end_dt': '2019-12-31', 'period': '0', 'tickers': ['FUN', 'JE', 'PRO', 'FTSI', 'MYT', 'GLNG', 'LXRX', 'NIO', 'AVLR', 'PIXY', 'LMT', 'PS', 'HEAR', 'ENDP', 'BLPH', 'MDB', 'WK', 'MCO', 'GOVX', 'SPGI', 'AKS', 'HJLI', 'ORLY', 'RST', 'HD', 'AM', 'ENR', 'IRWD', 'BNFT', 'W', 'MSCI', 'DCTH', 'UPS', 'GSK', 'VSM', 'OMER', 'NIHD', 'AMCX', 'DLPH', 'BLMN', 'NVAX', 'WFTIQ', 'ACRX', 'HCC', 'APAM', 'PBI', 'RETA', 'YRD', 'AGEN', 'TPL', 'NSP', 'SBUX', 'MCFT', 'VAPO', 'CLX', 'PEP', 'MA', 'TNTR', 'RAD', 'HSY', 'ALSN', 'BSIG', 'CC', 'ENPH', 'CTXS', 'MTD', 'AMRS', 'OEC', 'HLT', 'SIBN', 'STX', 'CASA', 'ATKR', 'CBB', 'RHP', 'UXIN', 'CELG', 'AZUL', 'CEPU', 'POOL', 'HX', 'SGH', 'LNTH', 'WEN', 'CHDN', 'FTDR', 'ALLE', 'PVAC', 'NVO', 'EXEL', 'UN', 'UL', 'HDS', 'MANH', 'SPB', 'SPG', 'CYH', 'RACE', 'INTU', 'MAR']},
	_2020_p0={'start_dt': '2020-01-01', 'end_dt': '2020-12-31', 'period': '0', 'tickers': ['JE', 'QTNT', 'CYTK', 'HD', 'RDUS', 'TMDX', 'APDN', 'IAA', 'VIVE', 'NIO', 'CLVS', 'PAE', 'ORLY', 'SPGI', 'MDRIQ', 'LJPC', 'OCGN', 'RH', 'MCO', 'RAPT', 'HRB', 'LXRX', 'CHRS', 'LLY', 'XBIT', 'IDXX', 'TBLT', 'BSIG', 'PIXY', 'CURO', 'MTCH2', 'AVEO', 'ACRX', 'BNFT', 'BURL', 'LMT', 'NSP', 'BPMP', 'UI', 'GOVX', 'BE', 'GSKY', 'PBI', 'WAT', 'IMGN', 'AVDL', 'MA', 'DAO', 'W', 'TBPH', 'APAM', 'MKD', 'LBTYA', 'WKHS', 'AMRS', 'CLX', 'RCM', 'MTD', 'MAR', 'ENPH', 'REPH', 'RST', 'INSG', 'DOMO', 'MBT', 'UPS', 'STX', 'CTXS', 'AZUL', 'HSC', 'CROX', 'RAMP', 'QCOM', 'TGI', 'THC', 'CLF', 'CRON', 'DBD', 'AVNT', 'ALSN', 'ITW', 'NTAP', 'CMPR', 'BKNG', 'CDW', 'RHP', 'ATKR', 'SMG', 'TPL', 'POOL', 'BWXT', 'NVAX', 'FICO', 'AMGN', 'SPG', 'NVO', 'BLMN', 'MTOR', 'HSY', 'KFRC']},
	_2021_p0={'start_dt': '2021-01-01', 'end_dt': '2021-12-31', 'period': '0', 'tickers': ['WBK', 'PIXY', 'MYOV', 'DOMO', 'NTNX', 'QTNT', 'WMG', 'GMBL', 'LW', 'NTAP', 'LOW', 'AVCT', 'CLX', 'VMW', 'ROK', 'BURL', 'QCOM', 'HRB', 'FICO', 'JE', 'NLOK', 'AAPL', 'CPB', 'ORCL', 'CHWY', 'MTOR', 'JWN', 'TJX', 'BAH', 'STX', 'ROST', 'SMG', 'FDS', 'ATKR', 'HOLX', 'LRCX', 'KLAC', 'CLCT', 'BBY', 'ADP', 'HLNE', 'BF.B', 'PLAY', 'EA', 'INTU', 'PAYX', 'WDFC', 'LULU', 'MSFT', 'MXIM', 'BR', 'ULTA', 'LOGI', 'GOOS', 'BIG', 'HDS', 'ACN', 'LB', 'FIZZ', 'CPRT', 'CSCO', 'WSM', 'XLNX', 'V', 'BERY', 'PLCE', 'NKE', 'GIS', 'TGT', 'PG', 'CTAS', 'RMD', 'DCI', 'DECK', 'MBUU', 'BKE', 'FIVE', 'INFY', 'AQUA', 'NVDA', 'DG', 'APPS', 'KMX', 'FOXF', 'EMR', 'CRVL', 'EXPO', 'EGAN', 'COST', 'JBSS', 'BABA', 'RPM', 'SCS', 'DHI', 'PINC', 'SPWH', 'WMT', 'VIVO', 'MRVL', 'WNS']},
)

# 39th day: low roe:
# 29th day: low roe:
stock_dict_low_roe = dict(
	_2016_p0={'start_dt': '2016-01-01', 'end_dt': '2016-12-31', 'period': '0', 'tickers': ['CLB', 'FDC', 'LTBR', 'WIX', 'CHTR', 'QUNR', 'CTIC', 'EAT', 'NTRA', 'IDXX', 'ET', 'WINT', 'CSOD', 'VIVE', 'IHG', 'WMS', 'CHRS', 'TNET', 'IMMU', 'PLNT', 'VNRSQ', 'HGEN', 'CRK', 'EXXIQ', 'SGY', 'OMED', 'DENN', 'BUFF', 'NVIV', 'AERI', 'AMCX', 'MCO', 'NKTR', 'TTNP', 'SNSS', 'HLF', 'AVXL', 'AKTX', 'BIOC', 'LINE', 'EKSO', 'XNPT', 'HDP', 'SLS', 'KOP', 'LPI', 'RYAM', 'APDN', 'RAD', 'IRWD', 'TSRO', 'PFPT', 'SRPT', 'CRZO', 'AGEN', 'BTUUQ', 'CHFS', 'GOVX', 'NFX', 'PODD', 'CLVS', 'EEQ', 'PHIO', 'IT', 'TXMD', 'INFI', 'ZIOP', 'ARNA', 'REXX', 'NK', 'GKOS', 'BDSI', 'GBT', 'WING', 'WYNN', 'BCEI', 'ISEE', 'IMGN', 'TDOC', 'CHMA', 'GOGO', 'ELNK', 'FCX', 'HNGR', 'BLPH', 'RDEN', 'ANAC', 'DVN', 'TNXP', 'ERF', 'BERY', 'SSNI', 'MGEN', 'ANTH', 'KERX', 'SBH', 'RCKT', 'SWN', 'PBYI', 'ALIM']},
	_2017_p0={'start_dt': '2017-01-01', 'end_dt': '2017-12-31', 'period': '0', 'tickers': ['AGEN', 'FMSA', 'EEQ', 'CARB', 'HDS', 'NAKD', 'HTGM', 'NSTG', 'CL', 'GOVX', 'WYNN', 'ENR', 'IT', 'IDXX', 'POAI', 'EKSO', 'VIVE', 'PZZA', 'KERX', 'BCRX', 'HRTX', 'PRO', 'CHFS', 'NVCN', 'HDP', 'CSOD', 'CLVS', 'AXAS', 'CIEIQ', 'NVAX', 'LPI', 'MAS', 'FRP', 'SWN', 'AZPN', 'SGRY', 'DRYS', 'LB', 'INST', 'WATT', 'BURL', 'BCEI', 'ORIG', 'PGEM', 'PBYI', 'INPX', 'AERI', 'PFPT', 'EYES', 'CRBP', 'IDXG', 'PHIO', 'AVXL', 'PSTG', 'APVO', 'ALIM', 'SPWH', 'CWEI', 'TNXP', 'WINMQ', 'W', 'SLS', 'SONC', 'GNMK', 'SIX', 'PI', 'NOW', 'CWH', 'RRD', 'AKBA', 'NFX', 'SIRI', 'SCON', 'BOX', 'IRWD', 'EAT', 'IHG', 'MTOR', 'SRPT', 'KTOV', 'WFTIQ', 'RIGL', 'TSRO', 'ARWR', 'ICPT', 'CPST', 'MJN', 'CLMT', 'RPD', 'PTLA', 'TRVN', 'ARNA', 'PTCT', 'DNKN', 'MSI', 'SHIP', 'FCX', 'DVAX', 'LJPC', 'COLL']},
	_2018_p0={'start_dt': '2018-01-01', 'end_dt': '2018-12-31', 'period': '0', 'tickers': ['W', 'OPTN', 'EEQ', 'PTE', 'AEMD', 'DIN', 'IRWD', 'BLPH', 'WIX', 'EQGP', 'WINMQ', 'TEUM', 'INST', 'CL', 'CDNA', 'CVNA', 'APRN', 'ALTR', 'MTOR', 'TLND', 'CHRS', 'NEOS', 'SVU', 'THC', 'SQNS', 'IDXX', 'BIOC', 'DRIO', 'MAS', 'VIVE', 'SE', 'MDCO', 'WATT', 'CYH', 'WFTIQ', 'PBYI', 'SNSS', 'ICPT', 'PIXY', 'PHIO', 'PZZA', 'TTNP', 'NRG', 'NTNX', 'VSM', 'XTLY', 'AKCA', 'HRTX', 'ISEE', 'DCPH', 'EKSO', 'P', 'VERI', 'BURL', 'PENN', 'SYNT', 'CSOD', 'FMI', 'LNTH', 'SRAX', 'POAI', 'MCD', 'NETE', 'ENDP', 'YTEN', 'CLSN', 'EYES', 'NKTR', 'QURE', 'MCO', 'KND', 'TUP', 'ATNX', 'PLUG', 'PIRS', 'NVIV', 'BOX', 'CBI', 'SLS', 'CERS', 'DNKN', 'VVV', 'CHFS', 'OCUL', 'TGTX', 'RPD', 'APDN', 'MX', 'ACER', 'TBPH', 'WU', 'WSC', 'VSTM', 'EIGI', 'BHVN', 'SPWR', 'NMBL', 'INSY', 'LXRX', 'TSRO']},
	_2019_p0={'start_dt': '2019-01-01', 'end_dt': '2019-12-31', 'period': '0', 'tickers': ['BA', 'KMB', 'TBPH', 'CHRS', 'NAKD', 'INSY', 'MAS', 'IDXX', 'CFRX', 'SPWR', 'AMRN', 'SE', 'MDCO', 'INPX', 'CLF', 'BURL', 'BXC', 'SLS', 'EYES', 'NTRA', 'CL', 'ADIL', 'VIVE', 'IMGN', 'ICPT', 'IQ', 'INVA', 'BIOC', 'BOX', 'DBD', 'CBLK', 'TTNP', 'EKSO', 'SFET', 'PLUG', 'ADSK', 'DERM', 'HPQ', 'QTT', 'AZPN', 'RCM', 'LII', 'WYND', 'APDN', 'HRB', 'PBYI', 'NSTG', 'CLDR', 'TGTX', 'YETI', 'SHLX', 'NVIV', 'AEMD', 'WU', 'AAL', 'LJPC', 'SGLB', 'ABBV', 'TCDA', 'SNES', 'SNBR', 'CDK', 'CHFS', 'RDUS', 'PTE', 'PTLA', 'BCRX', 'TNDM', 'CCXI', 'WATT', 'ZIOP', 'TNXP', 'RMBL', 'SMTA', 'ALDR', 'PHIO', 'CGIX', 'TCO', 'PRTK', 'CLVS', 'AXNX', 'NBRV', 'USAU', 'DVAX', 'OSTK', 'WVE', 'ESPR', 'TXMD', 'BHVN', 'TLND', 'STML', 'SIEN', 'AKER', 'VYGR', 'BHC', 'SVMK', 'SIGM', 'CRBP', 'BLCM', 'TLGT']},
	_2020_p0={'start_dt': '2020-01-01', 'end_dt': '2020-12-31', 'period': '0', 'tickers': ['TTNP', 'BCRX', 'QTT', 'NAKD', 'TGTX', 'KMB', 'TXMD', 'AAL', 'WU', 'CL', 'BLCM', 'RETA', 'CWH', 'ALTM', 'DVAX', 'MAS', 'FLXN', 'MYOV', 'NRG', 'HLT', 'SCYX', 'AXDX', 'TCO', 'ICPT', 'LW', 'FUN', 'BOX', 'RKDA', 'REAL', 'VSTM', 'SRNE', 'BBIO', 'INPX', 'SOS', 'SLS', 'PLUG', 'PBYI', 'PTLA', 'MSCI', 'INO', 'SILK', 'CHFS', 'SNDL', 'KPTI', 'TLND', 'BHVN', 'IMMU', 'CHH', 'CRBP', 'PHAT', 'HPQ', 'CAN', 'SBH', 'BIOC', 'APLS', 'SIRI', 'LYFT', 'HNGR', 'NTNX', 'LII', 'ATEC', 'BRP', 'NBRV', 'NTEC', 'SPCE', 'PJT', 'SOLY', 'EOLS', 'APVO', 'AEMD', 'ADMA', 'ETNB', 'FTSI', 'FCEL', 'WVE', 'PGEN', 'GLBS', 'ZIOP', 'AIMT', 'ACHV', 'UXIN', 'WK', 'SLDB', 'SIEN', 'NERV', 'PACB', 'SQBG', 'MOBL', 'AXSM', 'HCAT', 'SRRA', 'CVNA', 'ZGNX', 'JMIA', 'FSCT', 'CTMX', 'CERS', 'PIRRQ', 'AERI', 'CFRX']},
	_2021_p0={'start_dt': '2021-01-01', 'end_dt': '2021-12-31', 'period': '0', 'tickers': ['ACST', 'ASTC', 'BOX', 'HD', 'PHR', 'SBH', 'CSCW', 'EXTR', 'CAH', 'XAIR', 'RH', 'VVV', 'PLT', 'AEMD', 'BJ', 'AVYA', 'DELL', 'ABC', 'JILL', 'UI', 'APEX', 'IMVT', 'AZO', 'ADSK', 'PSTI', 'ESGC', 'AKTS', 'ACB', 'RCEL', 'MDB', 'GENE', 'HEXO', 'DOOO', 'EGHT', 'RGS', 'WORK', 'DT', 'MDP', 'MEIP', 'DXC', 'AGTC', 'OKTA', 'KERN', 'GME', 'YEXT', 'TWST', 'GWB', 'PLAN', 'RAD', 'ZUO', 'SSL', 'TEAM', 'CHNG', 'IMRN', 'PDCO', 'ESTC', 'CAMP', 'WMS', 'FRAN', 'OGI', 'COHR', 'MMYT', 'PLL', 'ADNT', 'AGYS', 'DOCU', 'BMRA', 'MDLA', 'MCFT', 'PRSP', 'REPL', 'CRWD', 'CDK', 'BBBY', 'ZS', 'EXPR', 'CMPR', 'AHPI', 'NGL', 'MSGN', 'ANGO', 'SNOA', 'VSTO', 'HOME', 'AYTU', 'KLXE', 'CBT', 'ENR', 'PSTG', 'COTY', 'CGC', 'UNFI', 'NEWR', 'TPR', 'CLDR', 'SCSC', 'SMAR', 'COUP', 'PANW', 'WDAY']},
)

# 39th day: low evebitda: 39 days: Annualized return: 0.17: overall mean roi: 0.0037
# 29th day: low evebitda: 29 days: Annualized return: 1.86: overall mean roi: 0.0036
# 39th day: low evebitda:
# 29th day: low evebitda:
stock_dict_low_evebitda = dict(
	_2016_p0={'start_dt': '2016-01-01', 'end_dt': '2016-12-31', 'period': '0', 'tickers': ['CYS', 'BLT', 'QLIK', 'TAHO', 'ARR', 'MXL', 'EHTH', 'WMC', 'PCTY', 'ACHN', 'HES', 'AMTG', 'ABCO', 'BMRN', 'NYCB', 'DATA', 'PANW', 'AAAP', 'CHGG', 'SGRY', 'IONS', 'SHOP', 'DXCM', 'MTGE', 'OFG', 'NOW', 'TWTR', 'CPA', 'WAC', 'TSLA', 'MMYT', 'ALKS', 'CS', 'ANAC', 'ETSY', 'LBRDA', 'TRCO', 'SA', 'HALO', 'AKTX', 'RNG', 'W', 'VRTX', 'N', 'SMLP', 'AKS', 'GLNG', 'BLOX', 'SGMS', 'OMF', 'PARR', 'DWRE', 'CNX', 'TXTR', 'KTWO', 'WTS', 'TWOU', 'OPK', 'ZG', 'FVE', 'SSRM', 'NBIX', 'QTWO', 'SGEN', 'SRNE', 'GOLD', 'HUBS', 'PODD', 'NRE', 'NKTR', 'PFPT', 'CSOD', 'ERII', 'IMPV', 'AVP', 'UTEK', 'SAFT', 'GHDX', 'MGNX', 'LDRH', 'QUOT', 'PACB', 'FET', 'TUBE', 'CLLS', 'RMTI', 'ATEX', 'NEWR', 'SPNC', 'ARAY', 'SSP', 'ATRC', 'MXWL', 'BHI', 'SCOR', 'JD', 'SPPI', 'ZEN', 'XNCR', 'WFTIQ']},
	_2017_p0={'start_dt': '2017-01-01', 'end_dt': '2017-12-31', 'period': '0', 'tickers': ['OPK', 'RNG', 'GLP', 'FORM', 'IONS', 'CIT', 'CAG', 'CPE', 'ACOR', 'CALD', 'GHDX', 'LPI', 'RES', 'BLOX', 'RRC', 'AUY', 'ARR', 'OCSL', 'CLMT', 'SHOP', 'HMHC', 'EVBG', 'CAVM', 'WMC', 'SA', 'ACTG', 'BL', 'CSOD', 'EXEL', 'DB', 'TWOU', 'ARAY', 'VNDA', 'PANW', 'KTWO', 'DXCM', 'NVRO', 'XEC', 'CECE', 'ACIU', 'TEX', 'GLNG', 'IRWD', 'ALKS', 'VIAV', 'MNTA', 'CS', 'SPNC', 'GLBS', 'SPXC', 'PFPT', 'PCRX', 'HES', 'FCX', 'TWLO', 'VRNS', 'WDAY', 'RETA', 'VCRA', 'AMD', 'SSNI', 'SGEN', 'PRGS', 'ZG', 'MBI', 'WPX', 'MB', 'MDCO', 'SUN', 'NBR', 'LC', 'HUBS', 'QTWO', 'WIX', 'BNFT', 'FET', 'FI', 'AR', 'NFG', 'NOW', 'NR', 'KMT', 'CRSP', 'ATEN', 'CY', 'IRTC', 'KOS', 'BHI', 'CBI', 'FMSA', 'BCEI', 'BCOR', 'CHGG', 'CWEI', 'SQ', 'SHIP', 'ATRC', 'FGEN', 'EZPW', 'COWN']},
	_2018_p0={'start_dt': '2018-01-01', 'end_dt': '2018-12-31', 'period': '0', 'tickers': ['LACQ', 'CALD', 'BLDP', 'SAIL', 'LPSN', 'SQ', 'TRVG', 'AU', 'DNOW', 'DFRG', 'KTOS', 'ATEN', 'VNET', 'GE', 'MDRX', 'SHOP', 'ONDK', 'PFPT', 'VCRA', 'RDFN', 'TWOU', 'AEGN', 'ALKS', 'RAMP', 'DXCM', 'CSOD', 'MB', 'PCRX', 'COWN', 'EVHC', 'KTWO', 'ZG', 'NKTR', 'HUBS', 'OSTK', 'BL', 'QTWO', 'VRNS', 'PANW', 'AXGN', 'MZOR', 'APOP', 'GLNG', 'SA', 'EVBG', 'NVRO', 'AYX', 'FRGI', 'ROKU', 'APEX', 'THS', 'AMBC', 'ANAB', 'ALTM', 'CLNE', 'INCY', 'SPTN', 'SRPT', 'ALTR', 'MAT', 'APPN', 'EXAS', 'XENT', 'EHTH', 'WINMQ', 'WIX', 'CVNA', 'WDAY', 'SEAS', 'NBIX', 'NVCR', 'SGEN', 'DRQ', 'BGNE', 'VNDA', 'IRTC', 'ADSK', 'MGNX', 'ARGX', 'HZNP', 'TWLO', 'ANGI', 'W', 'ARAY', 'ZEN', 'APTI', 'RNR', 'NEWR', 'SFS', 'BITA', 'LL', 'LC', 'XL', 'JT', 'ATRC', 'BNFT', 'MULE', 'OR', 'VECO', 'FRO']},
	_2019_p0={'start_dt': '2019-01-01', 'end_dt': '2019-12-31', 'period': '0', 'tickers': ['TWO', 'ROKU', 'BMRN', 'MBI', 'CLW', 'WMGI', 'COHU', 'SRDX', 'CVNA', 'KEYS', 'ZG', 'ALKS', 'GSHD', 'EVH', 'CPTA', 'NMRD', 'BL', 'RAMP', 'ATRS', 'SHOP', 'GKOS', 'HUBS', 'DATA', 'IVR', 'TWOU', 'WIX', 'NEWR', 'TRVG', 'QTWO', 'PFPT', 'SLCA', 'ZS', 'ATRC', 'LPSN', 'UPWK', 'VCEL', 'DXCM', 'WDAY', 'NVCR', 'GLNG', 'SMTA', 'MTSI', 'TLRY', 'EB', 'CPLG', 'GLPG', 'TDOC', 'CRON', 'TWLO', 'SPLK', 'CDXS', 'AQ', 'ORC', 'RGS', 'ZEN', 'EGHT', 'ARR', 'RST', 'EXAS', 'NOK', 'SA', 'NIHD', 'DNLI', 'BNFT', 'ADSK', 'EVBG', 'AVEO', 'BRSWQ', 'RMBS', 'VRNS', 'COUP', 'MDGL', 'CNO', 'FGEN', 'INSP', 'ALLK', 'SIBN', 'PSTG', 'HCM', 'MODN', 'RE', 'LC', 'PS', 'SGEN', 'GH', 'XENT', 'TRHC', 'FEYE', 'AMRN', 'RPD', 'INST', 'NVRO', 'ARGX', 'IRTC', 'AXGN', 'HALO', 'FTCH', 'CYRX', 'NTNX', 'WK']},
	_2020_p0={'start_dt': '2020-01-01', 'end_dt': '2020-12-31', 'period': '0', 'tickers': ['BYND', 'CIR', 'BILI', 'INSG', 'SHOP', 'ERJ', 'ZS', 'NFE', 'LPI', 'AMRN', 'SXC', 'OFIX', 'ROKU', 'PGNY', 'VCRA', 'PFPT', 'BLFS', 'BAND', 'TXG', 'DX', 'UPWK', 'SCWX', 'TNDM', 'AVLR', 'WDAY', 'ICD', 'TDOC', 'APPS', 'SGEN', 'COUP', 'EVER', 'BITA', 'VCYT', 'SVMK', 'DDD', 'AVNS', 'JE', 'KIDS', 'TLRA', 'CDLX', 'RPD', 'DLX', 'CDXS', 'GH', 'QTWO', 'SPLK', 'MODN', 'TDW', 'ZG', 'EVBG', 'AAWW', 'WIX', 'VCEL', 'AUDC', 'DVN', 'SA', 'ZEN', 'DLTR', 'OII', 'OKTA', 'NWL', 'ATEN', 'EXAS', 'SUPV', 'MBI', 'LOVE', 'PAR', 'FGEN', 'SMAR', 'ATRC', 'FSLY', 'ESTC', 'NET', 'ADTN', 'TEAM', 'ADPT', 'INSP', 'CFX', 'MDB', 'NLY', 'KOD', 'LN', 'PEGA', 'UTHR', 'TWLO', 'GKOS', 'MOS', 'APPN', 'THS', 'EIDX', 'AXSM', 'IOTS', 'SKY', 'LMPX', 'BREW', 'FEYE', 'WK', 'ARR', 'ACB', 'CDNA']},
	_2021_p0={'start_dt': '2021-01-01', 'end_dt': '2021-12-31', 'period': '0', 'tickers': ['MODN', 'HAIN', 'DCT', 'STZ', 'WDAY', 'COUP', 'APHA', 'WMG', 'BILL', 'ZS', 'TEAM', 'PHR', 'SPLK', 'DOCU', 'CRWD', 'HOME', 'SFIX', 'OKTA', 'CREE', 'SMAR', 'MDB', 'CAMP', 'DT', 'PLAN', 'AMBA', 'CHWY', 'AINV', 'CSII', 'MSGS', 'ARWR', 'PSTG', 'MDP', 'ASH', 'BMRA', 'COTY', 'SCHL', 'SMFG', 'MDLA', 'PD', 'ESTC', 'BOX', 'MCFT', 'ENTA', 'PRSP', 'ZUO', 'EXTR', 'TWST', 'EQOS', 'TPR', 'WORK', 'ATEX', 'KLXE', 'AHPI', 'VSTO', 'AYTU', 'HP', 'CLDR', 'APEX', 'MESO', 'YEXT', 'NWSA', 'IMRN', 'LOVE', 'CASH', 'AGYS', 'EGHT', 'BBBY', 'IMVT', 'RAMP', 'GENE', 'AVCT', 'AKTS', 'EXPR', 'PLL', 'AGX', 'GMBL', 'MUFG', 'COHR', 'PSTI', 'CAH', 'MEIP', 'QTNT', 'MYGN', 'KERN', 'JILL', 'REPL', 'NTNX', 'SCSC', 'JE', 'DOMO', 'XAIR', 'CGC', 'PDCO', 'ABC', 'DXC', 'GME', 'RGS', 'PLT', 'CSCW', 'RCEL']},
)

# 39th day: high roa: Annualized return: 0.44: overall mean roi: 0.0029
# 29th day: high roa: Annualized return: 0.76: overall mean roi: 0.0020
stock_dict_high_roa = dict(
	_2016_p0={'start_dt': '2016-01-01', 'end_dt': '2016-12-31', 'period': '0', 'tickers': ['FPRX', 'LGND', 'NHTC', 'VC', 'ABMD', 'EVH', 'NVO', 'GILD', 'KING', 'IHG', 'AZPN', 'FDS', 'LCI', 'CPRI', 'CLNY', 'ENTA', 'MANH', 'UTHR', 'ANTE', 'PDLI', 'TARO', 'ZLTQ', 'RMBS', 'WETF', 'LLTC', 'RAD', 'NTI', 'BIDU', 'VA', 'SHLX', 'GPP', 'LAZ', 'MA', 'TREE', 'MMI', 'LXFT', 'USG', 'BSTC', 'MKTX', 'GGG', 'SWKS', 'CNS', 'MDVN', 'TROW', 'UI', 'EFOI', 'CBB', 'SBUX', 'AVDL', 'SEIC', 'CGNX', 'RGR', 'PETS', 'NTRI', 'RHI', 'XPER', 'MTG', 'PM', 'FAST', 'PII', 'PPC', 'INFY', 'BUFF', 'IQNT', 'ALDW', 'VIVO', 'AAPL', 'VLRS', 'BIIB', 'EGOV', 'INSY', 'TSM', 'CYBX', 'TREX', 'MCO', 'LYB', 'CPSI', 'SYNT', 'AAON', 'NEU', 'NTES', 'CHH', 'CALM', 'UAL', 'ROL', 'CLB', 'ZNH', 'ATRI', 'GSK', 'SAFM', 'IPGP', 'TXN', 'SHW', 'SCHL', 'CBPO', 'MTD', 'TSCO', 'ACN', 'JRJC', 'ARMH']},
	_2017_p0={'start_dt': '2017-01-01', 'end_dt': '2017-12-31', 'period': '0', 'tickers': ['MNKD', 'TPL', 'EGRX', 'MASI', 'NVO', 'MANH', 'NHTC', 'AZPN', 'MO', 'SUPN', 'TNH', 'EBAY', 'CPRI', 'FDS', 'BEAT', 'UI', 'YRD', 'UTHR', 'BAX', 'CNS', 'MEET', 'DPZ', 'ACIA', 'DLTH', 'CALM', 'TREX', 'TARO', 'ELY', 'MTOR', 'BKE', 'MKTX', 'TTNP', 'GILD', 'SWKS', 'RGR', 'LLTC', 'SPGI', 'BF.B', 'NTRI', 'AEIS', 'YUM', 'SHLX', 'HDS', 'CCRC', 'MA', 'NTES', 'EGOV', 'PETS', 'USNA', 'TXN', 'INTU', 'BUFF', 'ACN', 'FIZZ', 'MOMO', 'BABA', 'SEDG', 'SEIC', 'AAON', 'SIMO', 'SBUX', 'IDCC', 'ROST', 'AMBA', 'PZZA', 'EQR', 'LULU', 'FRAN', 'LXFT', 'TJX', 'VLP', 'IDTI', 'PM', 'CL', 'VVV', 'SRI', 'RHI', 'VRSN', 'TROW', 'VLRS', 'MMI', 'TSM', 'INFY', 'MIK', 'BSTC', 'LANC', 'FAST', 'ROL', 'EA', 'MTD', 'YY', 'MESG', 'FCPT', 'LORL', 'NEU', 'FB', 'NKE', 'TSEM', 'CBPO', 'SHW']},
	_2018_p0={'start_dt': '2018-01-01', 'end_dt': '2018-12-31', 'period': '0', 'tickers': ['MACK', 'CORT', 'TPL', 'AZPN', 'CNCE', 'ISEE', 'HCC', 'ASPS', 'LNTH', 'BTI', 'CIEN', 'NVO', 'GCP', 'MANH', 'SYNT', 'INVA', 'JE', 'DPZ', 'TGS', 'ACLS', 'FG', 'LOMA', 'NPO', 'FIZZ', 'TREX', 'CUTR', 'NTRI', 'MOMO', 'UI', 'LPI', 'BIVV', 'EVC', 'PK', 'MKTX', 'EXEL', 'SINO', 'HKRSQ', 'MITK', 'YUM', 'BUFF', 'CNS', 'SEIC', 'SWKS', 'PETS', 'FRAN', 'MO', 'STMP', 'INTU', 'NBLX', 'MCFT', 'DRE', 'KRO', 'TXN', 'OCLR', 'TROW', 'ROST', 'CPRT', 'EGRX', 'FDS', 'TEO', 'CMCM', 'CPRI', 'MED', 'FB', 'TARO', 'SHLX', 'YY', 'WING', 'LULU', 'FAST', 'SBUX', 'AEIS', 'LBRDA', 'MSGN', 'EGOV', 'WB', 'NVDA', 'AMAT', 'LYB', 'TSEM', 'MA', 'PZZA', 'CRUS', 'ANET', 'NKE', 'UNP', 'QTNA', 'TJX', 'AAON', 'CCRC', 'ATRI', 'ATHM', 'GGG', 'NVMI', 'NVR', 'RGR', 'HD', 'ROL', 'MIK', 'BOBE']},
	_2019_p0={'start_dt': '2019-01-01', 'end_dt': '2019-12-31', 'period': '0', 'tickers': ['ZIOP', 'AM', 'INVA', 'TPL', 'FTSI', 'AZPN', 'HX', 'EXEL', 'HCC', 'EAF', 'CEPU', 'VRTX', 'HEAR', 'DPZ', 'ESIO', 'NKTR', 'FIZZ', 'IMMR', 'NVO', 'JE', 'CLF', 'YUM', 'MANH', 'MU', 'MSGN', 'MED', 'TXN', 'NVDA', 'TREX', 'NTRI', 'CARG', 'PETS', 'MKTX', 'VRSN', 'INTU', 'CORT', 'NVR', 'SEIC', 'WTI', 'MCFT', 'HRB', 'CCRC', 'PAM', 'TGS', 'MA', 'IDXX', 'CNS', 'PVAC', 'REGI', 'ROST', 'FB', 'FAST', 'TROW', 'AVGO', 'REGN', 'RGNX', 'SBUX', 'FTV', 'TUSK', 'GGG', 'RHI', 'USNA', 'EVR', 'LTHM', 'KEM', 'CHE', 'SPGI', 'BPMP', 'MNST', 'ROL', 'CHDN', 'STMP', 'ALGN', 'XYF', 'ATHM', 'GNTX', 'SGH', 'MTD', 'ULTA', 'INFY', 'CTRL', 'WB', 'SWKS', 'TJX', 'PM', 'CRCM', 'ENTA', 'CPRT', 'CHH', 'EGOV', 'OMAB', 'HD', 'JKHY', 'EXPD', 'CL', 'YNDX', 'LSTR', 'GOOS', 'SHLX', 'UI']},
	_2020_p0={'start_dt': '2020-01-01', 'end_dt': '2020-12-31', 'period': '0', 'tickers': ['XBIT', 'RAMP', 'TPL', 'CRON', 'EAF', 'NRG', 'INMD', 'LXRX', 'MED', 'LGND', 'CPRX', 'CDNS', 'UI', 'DPZ', 'NVO', 'VRSN', 'NVDA', 'CNS', 'KFRC', 'ARNA', 'ENPH', 'MA', 'CHRS', 'REGI', 'BRKS', 'POWI', 'TXN', 'AZPN', 'ABMD', 'VNDA', 'FIZZ', 'DENN', 'INTU', 'CORT', 'YUM', 'KL', 'ROST', 'TREX', 'SEIC', 'PETS', 'CPRT', 'AMSC', 'IDXX', 'HD', 'LULU', 'MKTX', 'NVR', 'FDS', 'INVA', 'BIO', 'BPMP', 'TROW', 'ANET', 'MANH', 'MTCH2', 'LBTYA', 'STX', 'HCC', 'BKNG', 'PINC', 'MSGN', 'MNST', 'QNST', 'BIIB', 'HSC', 'LLY', 'WUBA', 'TJX', 'WAT', 'GGG', 'NTES', 'FAST', 'BSTC', 'AVEO', 'GOOS', 'ULTA', 'MTD', 'MXIM', 'SPGI', 'ARWR', 'RHI', 'GNTX', 'OMAB', 'USNA', 'SLP', 'AVNT', 'SHLX', 'QD', 'CHE', 'ALGN', 'LII', 'LRCX', 'EXEL', 'SBUX', 'GMAB', 'DECK', 'ATHM', 'WDFC', 'FIVE', 'INFY']},
	_2021_p0={'start_dt': '2021-01-01', 'end_dt': '2021-12-31', 'period': '0', 'tickers': ['UI', 'VMW', 'EA', 'NLOK', 'INTU', 'LULU', 'CPRT', 'FIZZ', 'HD', 'MSGN', 'CLCT', 'LOGI', 'FDS', 'INFY', 'MXIM', 'NVDA', 'ROST', 'AAPL', 'ABMD', 'WDFC', 'PETS', 'LRCX', 'CLX', 'HOLX', 'XLNX', 'SWKS', 'FOXF', 'QCOM', 'DECK', 'EXPO', 'MSFT', 'VEEV', 'MRVL', 'FICO', 'BF.B', 'ACN', 'ULTA', 'ROK', 'V', 'RMD', 'TJX', 'LANC', 'HLNE', 'GOOS', 'DHI', 'JBSS', 'KLAC', 'AZO', 'CPB', 'JKHY', 'WNS', 'VIVO', 'PAYX', 'BABA', 'CSWI', 'CSCO', 'HLI', 'MBUU', 'BKE', 'WIT', 'TECH', 'SLP', 'STX', 'DCI', 'APPS', 'CTAS', 'VVV', 'CRVL', 'PG', 'SLQT', 'DOOO', 'NTAP', 'MMS', 'LOW', 'SMG', 'BAH', 'EBF', 'MSM', 'CRUS', 'ATKR', 'ROLL', 'BR', 'HRL', 'LW', 'FIVE', 'BBY', 'ORCL', 'CVCO', 'HDS', 'MEI', 'BRC', 'HZO', 'OLLI', 'NKE', 'RAVN', 'WSM', 'EMR', 'RH', 'BURL', 'EGAN']},
)

# 39th day: high revenueusd: Annualized return: -0.12: overall mean roi: 0.0003
# 29th day: high revenueusd: Annualized return: 0.01: overall mean roi: 0.0007
# 39th day: high revenueusd:
# 29th day: high revenueusd:
stock_dict_high_revenueusd = dict(
	_2016_p0={'start_dt': '2016-01-01', 'end_dt': '2016-12-31', 'period': '0', 'tickers': ['SNP', 'RDS.A', 'PTR', 'XOM', 'AAPL', 'TM', 'BP', 'BRK.B', 'MCK', 'UNH', 'CVS', 'F', 'T', 'TOT', 'CVX', 'ABC', 'GM', 'VZ', 'FCAU', 'GE', 'COST', 'HMC', 'KR', 'AMZN', 'WBA', 'CHL', 'CAH', 'ESRX', 'PSX', 'PBR', 'BA', 'MSFT', 'JPM', 'VLO', 'WFC', 'BAC', 'IBM', 'E', 'ANTM', 'LFC', 'C', 'GOOGL', 'CMCSA', 'PM', 'MPC', 'HSBC', 'PG', 'SNE', 'ADM', 'MT', 'PEP', 'VOD', 'MET', 'PUK', 'AET', 'TEF', 'EQNR', 'UPS', 'AIG', 'UN', 'UL', 'PRU', 'INTC', 'HUM', 'DIS', 'HPQ', 'NVS', 'KEP', 'PKX', 'CSCO', 'PFE', 'DD', 'SYY', 'FDX', 'CAT', 'BHP', 'KO', 'ORAN', 'BG', 'BUD', 'CHU', 'TTM', 'MUFG', 'TSN', 'AEG', 'AAL', 'DAL', 'LMT', 'HCA', 'MRK', 'HON', 'ORCL', 'CI', 'UAL', 'SNY', 'ET', 'ALL', 'ABB', 'SLB', 'DB']},
	_2017_p0={'start_dt': '2017-01-01', 'end_dt': '2017-12-31', 'period': '0', 'tickers': ['WMT', 'SNP', 'TM', 'RDS.A', 'PTR', 'BRK.B', 'AAPL', 'XOM', 'MCK', 'BP', 'UNH', 'CVS', 'T', 'F', 'GM', 'ABC', 'AMZN', 'HMC', 'TOT', 'VZ', 'CAH', 'GE', 'COST', 'WBA', 'CVX', 'FCAU', 'KR', 'CHL', 'ESRX', 'JPM', 'BA', 'MSFT', 'GOOGL', 'PUK', 'HD', 'PSX', 'ANTM', 'WFC', 'BAC', 'PBR', 'CMCSA', 'IBM', 'LFC', 'VLO', 'PM', 'TGT', 'SNE', 'VOD', 'C', 'JNJ', 'PG', 'MPC', 'AET', 'PEP', 'ADM', 'UPS', 'MET', 'HSBC', 'E', 'INTC', 'LOW', 'PRU', 'MT', 'AEG', 'DIS', 'UN', 'UL', 'TEF', 'HUM', 'PFE', 'AIG', 'SYY', 'FDX', 'KEP', 'NVS', 'CSCO', 'LYG', 'HPQ', 'DD', 'LMT', 'EQNR', 'BUD', 'PKX', 'IM', 'ORAN', 'BG', 'KO', 'HCA', 'TTM', 'CNC', 'AAL', 'CI', 'MRK', 'MFC', 'BBY', 'MUFG', 'CHU', 'DAL', 'HON', 'CAT']},
	_2018_p0={'start_dt': '2018-01-01', 'end_dt': '2018-12-31', 'period': '0', 'tickers': ['WMT', 'SNP', 'RDS.A', 'PTR', 'TM', 'BP', 'XOM', 'BRK.B', 'AAPL', 'UNH', 'MCK', 'CVS', 'AMZN', 'T', 'F', 'ABC', 'TOT', 'GM', 'CVX', 'CAH', 'COST', 'FCAU', 'HMC', 'VZ', 'WBA', 'KR', 'CHL', 'GOOGL', 'PSX', 'PUK', 'JPM', 'ESRX', 'GE', 'LFC', 'MSFT', 'HD', 'BA', 'VLO', 'ANTM', 'BAC', 'WFC', 'E', 'CMCSA', 'IBM', 'PM', 'PBR', 'JNJ', 'MPC', 'C', 'TGT', 'AEG', 'MT', 'SNE', 'UPS', 'PG', 'LOW', 'UN', 'UL', 'HSBC', 'PEP', 'INTC', 'TEF', 'MET', 'DELL', 'EQNR', 'ADM', 'AET', 'FDX', 'PRU', 'VOD', 'PKX', 'KEP', 'SYY', 'DIS', 'BUD', 'JD', 'HUM', 'PFE', 'HPQ', 'LMT', 'AIG', 'ORAN', 'CNC', 'CSCO', 'LYG', 'MFC', 'BG', 'CAT', 'HCA', 'SNY', 'NVS', 'AAL', 'CI', 'CHTR', 'CHU', 'DAL', 'TTM', 'BAM', 'GSK', 'FB']},
	_2019_p0={'start_dt': '2019-01-01', 'end_dt': '2019-12-31', 'period': '0', 'tickers': ['WMT', 'SNP', 'RDS.A', 'PTR', 'BP', 'XOM', 'AAPL', 'TM', 'AMZN', 'UNH', 'BRK.B', 'MCK', 'CVS', 'TOT', 'T', 'ABC', 'CVX', 'F', 'GM', 'COST', 'GOOGL', 'CAH', 'HMC', 'WBA', 'VZ', 'FCAU', 'KR', 'VLO', 'PSX', 'MSFT', 'JPM', 'CHL', 'BA', 'HD', 'MPC', 'GE', 'CMCSA', 'ANTM', 'BAC', 'LFC', 'E', 'WFC', 'PBR', 'JNJ', 'PM', 'EQNR', 'IBM', 'DELL', 'MT', 'SNE', 'C', 'TGT', 'UPS', 'INTC', 'LOW', 'MET', 'JD', 'PG', 'FDX', 'VOD', 'PEP', 'ADM', 'HSBC', 'PRU', 'CNC', 'DIS', 'SYY', 'UN', 'UL', 'PKX', 'HPQ', 'HUM', 'BAM', 'TEF', 'FB', 'CAT', 'CHA', 'ET', 'KEP', 'LMT', 'PFE', 'BUD', 'CSCO', 'CI', 'ORAN', 'AIG', 'HCA', 'NVS', 'BG', 'PUK', 'AAL', 'DAL', 'TTM', 'CHTR', 'TMUS', 'BHP', 'MRK', 'BBY', 'CHU', 'HON']},
	_2020_p0={'start_dt': '2020-01-01', 'end_dt': '2020-12-31', 'period': '0', 'tickers': ['WMT', 'SNP', 'PTR', 'RDS.A', 'BRK.B', 'BP', 'AMZN', 'TM', 'XOM', 'AAPL', 'CVS', 'UNH', 'MCK', 'T', 'ABC', 'TOT', 'GOOGL', 'F', 'CI', 'COST', 'CVX', 'CAH', 'HMC', 'GM', 'WBA', 'VZ', 'MSFT', 'MPC', 'PUK', 'KR', 'FCAU', 'JPM', 'PSX', 'CMCSA', 'VLO', 'HD', 'CHL', 'ANTM', 'LFC', 'GE', 'BAC', 'DELL', 'JD', 'WFC', 'JNJ', 'E', 'SNE', 'PM', 'IBM', 'RTX', 'PBR', 'BA', 'AEG', 'TGT', 'CNC', 'C', 'UPS', 'INTC', 'LOW', 'HSBC', 'FB', 'MT', 'FDX', 'MET', 'DIS', 'BAM', 'PG', 'PEP', 'HUM', 'PRU', 'ADM', 'EQNR', 'MFC', 'SYY', 'LMT', 'HPQ', 'UL', 'UN', 'VOD', 'BABA', 'PKX', 'LYG', 'TEF', 'ET', 'CAT', 'BUD', 'CSCO', 'PFE', 'HCA', 'KEP', 'AIG', 'NVS', 'ORAN', 'DAL', 'MRK', 'AAL', 'CHTR', 'TMUS', 'ALL', 'GSK']},
	_2021_p0={'start_dt': '2021-01-01', 'end_dt': '2021-12-31', 'period': '0', 'tickers': ['WMT', 'TM', 'AAPL', 'MCK', 'ABC', 'COST', 'CAH', 'MSFT', 'WBA', 'HMC', 'KR', 'HD', 'DELL', 'TGT', 'SNE', 'BABA', 'LOW', 'PG', 'FDX', 'DIS', 'VOD', 'SYY', 'CSCO', 'ACN', 'BBY', 'TSN', 'BHP', 'TJX', 'ORCL', 'NKE', 'TECD', 'RY', 'MUFG', 'TTM', 'TD', 'TAK', 'MDT', 'DG', 'JBL', 'UNFI', 'PFGC', 'SMFG', 'M', 'FLEX', 'BNS', 'DLTR', 'QCOM', 'SBUX', 'JCI', 'RAD', 'V', 'MU', 'IX', 'KMX', 'DHI', 'KSS', 'IBN', 'DXC', 'BMO', 'NGG', 'AVT', 'GIS', 'WRK', 'BDX', 'CRM', 'EMR', 'WDC', 'GPS', 'ROST', 'JWN', 'DEO', 'WBK', 'ADP', 'CM', 'EL', 'PH', 'TXT', 'J', 'ACM', 'BJ', 'LB', 'ARMK', 'INFY', 'ADNT', 'AZO', 'AMCR', 'FOXA', 'TEL', 'BERY', 'BBBY', 'LDOS', 'VEDL', 'CAG', 'SSL', 'NVDA', 'VMW', 'STX', 'VFC', 'LRCX', 'PVH']},
)


# 39th day: low pe: Num invs: 761; annualized return: 0.12: overall mean roi: 0.0051
# 29th day: low pe: Num invs: 6000; annualized return: 0.20: overall mean roi: 0.0015
stock_dict_low_pe_p4 = dict(
	_2016_p0={'start_dt': '2016-01-01', 'end_dt': '2016-04-02', 'period': '0', 'tickers': ['RUTH', 'COLM', 'CLGX', 'PRFT', 'ISBC', 'CHH', 'BIIB', 'ROLL', 'GLPI', 'FIS', 'FUN', 'TMO', 'FCAU', 'TREE', 'SHW', 'AVB', 'RPM', 'BLMN', 'EBS', 'USM', 'SXT', 'FICO', 'POM', 'TSCO', 'USPH', 'SBRA', 'MGLN', 'SEAS', 'STE1', 'AAON', 'DAL', 'PDFS', 'ECOL', 'HRC', 'MED', 'GMCR', 'APOL', 'ANSS', 'IDTI', 'CBPO', 'BBDC', 'APD', 'SBSI', 'MWV', 'MSCI', 'LH', 'ZGNX', 'RGR', 'SLG', 'HNT', 'BRKS', 'GRMN', 'ALLE', 'SONC', 'NVO', 'WOOF', 'SCHW', 'WST', 'RXN', 'CORE', 'STLD', 'PZZA', 'HURN', 'NNN', 'BPL', 'EEFT', 'SPH', 'SIAL', 'TE', 'IPAR', 'STC', 'MMSI', 'MNRO', 'TR', 'CLNY1', 'PXD', 'NATI', 'TPX', 'SEE', 'YUM', 'PCL', 'SFNC', 'AWI', 'MTRX', 'TEP', 'LSI', 'EQT', 'ACIW', 'VSTO', 'TTMI', 'TECH', 'BHI', 'BIDU', 'DPZ', 'FARO', 'ADS', 'AYI', 'ETFC', 'MDVN', 'PKI']},
	_2016_p1={'start_dt': '2016-04-02', 'end_dt': '2016-07-02', 'period': '1', 'tickers': ['MCEP', 'EL', 'MIDD', 'WOOF', 'TFX', 'DLTR', 'COLM', 'TFM', 'PG', 'MOH', 'LSI', 'FIG', 'SIRO', 'RRGB', 'EBAY', 'SBUX', 'ROLL', 'DNKN', 'NVO', 'SKT', 'LGF.B', 'EBSB', 'CLR', 'NATI', 'LEG', 'WFM', 'TR', 'EGOV', 'OHI', 'POM', 'ALOG', 'REG', 'VFC', 'PAA', 'SKUL', 'CHUY', 'TAP', 'COKE', 'PRFT', 'TPX', 'LULU', 'FICO', 'MDLZ', 'ARMK', 'EEP', 'SAM', 'TREX', 'FE', 'STL', 'UDR', 'MCK', 'MGLN', 'CEB', 'TSCO', 'ATNI', 'TCX', 'HIW', 'TEP', 'PKY1', 'ISCA', 'GLPI', 'WYNN', 'FWRD', 'CTRN', 'PSA', 'CXP', 'MED', 'ACIW', 'SPG', 'MNRO', 'EEFT', 'ANSS', 'AMN', 'PLKI', 'BMI', 'SPB1', 'SBSI', 'MMSI', 'BIDU', 'ADTN', 'EXLS', 'DLR', 'FCH', 'AZPN', 'BWLD', 'MTN', 'HBI', 'BXP', 'IDXX', 'EGP', 'SYY', 'CRS', 'TYPE', 'OMI', 'CDNS', 'FLWS', 'CLNY', 'FRGI', 'LTBR', 'T']},
	_2016_p2={'start_dt': '2016-07-02', 'end_dt': '2016-10-01', 'period': '2', 'tickers': ['ITGR', 'THS', 'POWI', 'SYK', 'HAIN', 'FLT', 'DIN', 'HLT', 'RSE', 'BCPC', 'HNT', 'AVGO', 'FICO', 'ABMD', 'CHUY', 'COKE', 'RRD', 'PF', 'HNI', 'FCN', 'USG', 'DMND', 'SPG', 'STBZ', 'ANDX', 'LULU', 'SKX', 'CMPR', 'APAM', 'ISRG', 'CORE', 'EQR', 'ABAX', 'SBUX', 'LSI', 'AKR', 'MSCI', 'ANSS', 'JJSF', 'DAKT', 'SCU', 'EBSB', 'CLGX', 'REG', 'CW', 'BMI', 'AVB', 'ABBV', 'CXP', 'PNRA', 'FRGI', 'WETF', 'AAOI', 'DVA', 'MIDD', 'TECH', 'BF.B', 'ADS', 'AMSG', 'FSL', 'DPZ', 'MNRO', 'TAP', 'TIVO1', 'NTUS', 'ADTN', 'PYPL', 'PLKI', 'EW', 'SNPS', 'ARMK', 'AIN', 'LNN', 'RRGB', 'PAGP', 'SWI1', 'CAMP', 'RAVN', 'WCG', 'BSTC', 'NATI', 'TPX', 'ALGN', 'ON', 'SIAL', 'TREE', 'STOR', 'NLSN', 'SRC', 'VRTU', 'HHC', 'ALEX', 'RCL', 'OMCL', 'HSY', 'STE1', 'SSNI', 'JEF', 'BGS', 'SEE']},
	_2016_p3={'start_dt': '2016-10-01', 'end_dt': '2016-12-31', 'period': '3', 'tickers': ['HUN', 'GTN', 'PKI', 'PAA', 'MKC', 'LII', 'COST', 'BDC', 'RPAI', 'CVA', 'AZN', 'SFS', 'PMC', 'ABMD', 'SYY', 'PSMT', 'CPSI', 'NSP', 'LNN', 'JJSF', 'EFX', 'EGOV', 'WDFC', 'PRIM', 'BSTC', 'PLAY', 'ECOL', 'HCKT', 'NKE', 'TIVO1', 'PSXP', 'A', 'TNC', 'MLM', 'ARMK', 'MTSI', 'GPN', 'SHPG', 'CMG', 'NCLH', 'GTT', 'EVHC', 'EBSB', 'WM', 'NSA', 'MNRO', 'ATVI', 'SCHW', 'MIDD', 'STL', 'KATE', 'SF', 'AMAG', 'SIRO', 'MTW', 'FICO', 'BCPC', 'BF.B', 'AGNC', 'MDVN', 'USPH', 'APAM', 'ETFC', 'CE', 'BWLD', 'MPLX', 'ANSS', 'SIX', 'DM', 'MATW', 'FI', 'EA', 'GHL', 'BMI', 'FIZZ', 'FBP', 'CVGW', 'OVTI', 'SPG', 'DISH', 'MSCI', 'PNY', 'WY', 'FR', 'MRK', 'PNRA', 'TAL', 'BANR', 'PRAH', 'AGN', 'RCL', 'WEX', 'FSL', 'NNN', 'BXP', 'NWL', 'PPL', 'ROCK', 'ECL', 'TECH']},
	_2017_p0={'start_dt': '2017-01-01', 'end_dt': '2017-04-01', 'period': '0', 'tickers': ['LULU', 'RACE', 'WYNN', 'RXN', 'SUI', 'MCHP', 'ASTE', 'ASH', 'OSIS', 'AAON', 'ARG', 'PSXP', 'MKC', 'PCAR', 'RLGY', 'MSCI', 'TXRH', 'MJN', 'LII', 'EFX', 'UHT', 'STAY', 'TWC', 'AKAM', 'EXLS', 'OKS', 'PCG', 'JBT', 'CSH', 'ANSS', 'ANIP', 'KFY', 'MLM', 'ZLTQ', 'WEX', 'ICUI', 'NLSN', 'CHEF', 'SFM', 'AKR', 'STX', 'WELL', 'GOOGL', 'WRE', 'MRK', 'CVGW', 'APLE', 'PLD', 'WBC', 'PRFT', 'WDFC', 'GVA', 'GTT', 'PFGC', 'CORR', 'CUB', 'CVA', 'MAT', 'MIDD', 'ARMK', 'RMAX', 'SYY', 'CTXS', 'CNR', 'IMAX', 'ABAX', 'BMI', 'EEFT', 'CDK', 'COO', 'TR', 'TACO', 'EGP', 'BXP', 'POWI', 'ECL', 'CBPO', 'FBP', 'DVA', 'ANET', 'PRIM', 'PNRA', 'BXLT', 'ROCK', 'NSA', 'FIVE', 'SITC', 'UEIC', 'TECH', 'DPZ', 'SCCO', 'MNRO', 'WPC', 'MINI', 'NTUS', 'AVB', 'PNY', 'SBUX', 'EQC', 'WBMD']},
	_2017_p1={'start_dt': '2017-04-01', 'end_dt': '2017-07-01', 'period': '1', 'tickers': ['SBUX', 'SXT', 'NJR', 'ITC', 'EL', 'SIRI', 'AKAM', 'PSMT', 'AGR', 'EGOV', 'WBMD', 'IPAR', 'VRTU', 'RRMS', 'ANET', 'RXN', 'ANF', 'SITC', 'AWK', 'EVR', 'MATW', 'IM', 'SNPS', 'MAT', 'ANSS', 'ABM', 'FLOW', 'MWA', 'MKC', 'ASTE', 'ARMK', 'NLSN', 'FEIC', 'LSI', 'AVB', 'SFM', 'MRK', 'JBT', 'SIX', 'MPAA', 'MXL', 'DNKN', 'GNRC', 'MDT', 'POWI', 'VC', 'NI', 'BDX', 'LULU', 'CTXS', 'EXPO', 'CERN', 'CEB', 'LHX', 'WDFC', 'FICO', 'ITRI', 'CNR', 'IPHS', 'RRD', 'SF', 'ICUI', 'BEAT', 'MSEX', 'MNRO', 'FWRD', 'COKE', 'MTN', 'NTUS', 'ADTN', 'PYPL', 'DPZ', 'TMUS', 'SCHL', 'OXM', 'EPAM', 'BRKR', 'EFX', 'IBP', 'ACHC', 'MJN', 'MLM', 'BXP', 'PRLB', 'WW', 'FLT', 'TACO', 'OSPN', 'GDOT', 'GNL', 'TYC', 'OPI', 'CSH', 'ALLE', 'ABAX', 'MC', 'PRAH', 'EVHC', 'USM', 'CVGW']},
	_2017_p2={'start_dt': '2017-07-01', 'end_dt': '2017-09-30', 'period': '2', 'tickers': ['MKC', 'MTD', 'SIRI', 'SYY', 'OKS', 'ELY', 'STX', 'EGOV', 'FIG', 'GLPI', 'CAG', 'COST', 'SCCO', 'PFE', 'ANSS', 'DAN', 'BMI', 'IBP', 'CVA', 'CTLT', 'DLTH', 'CLF', 'FCFS', 'HEI', 'CORE', 'SXC', 'MKSI', 'MNRO', 'MRK', 'JBT', 'BGS', 'NILE', 'MSCI', 'CERN', 'PNRA', 'NTUS', 'GNL', 'KBR', 'MWA', 'KNX', 'DLTR', 'WETF', 'BURL', 'INVA', 'WDFC', 'PLD', 'IPAR', 'PZZA', 'HSY', 'ITC', 'UE', 'NLSN', 'ARMK', 'HOLX', 'CABO', 'GDOT', 'WMS', 'BCR', 'CMC', 'PPG', 'LLL', 'RXN', 'BLMN', 'HRC', 'CHUY', 'H', 'BEAT', 'OLLI', 'MAA', 'A', 'CBPO', 'WELL', 'CTRE', 'TIVO', 'NVDA', 'ABAX', 'RACE', 'ECL', 'TR', 'DRE', 'LFUS', 'EQGP', 'CDK', 'MDT', 'EFX', 'STJ', 'SNPS', 'RBA', 'LHX', 'PSA', 'CPB', 'RMAX', 'EXR', 'CVGW', 'MANH', 'FWRD', 'DPZ', 'CTRL', 'EPAM', 'ICUI']},
	_2017_p3={'start_dt': '2017-09-30', 'end_dt': '2017-12-31', 'period': '3', 'tickers': ['ORA', 'HTLD', 'AF', 'MAT', 'ANSS', 'DRE', 'UE', 'TXRH', 'APAM', 'CTRE', 'MKSI', 'MANH', 'SPG', 'PDM', 'HSY', 'AZPN', 'ESE', 'WMS', 'SCI', 'QUAD', 'IPAR', 'A', 'MTRN', 'ADTN', 'BWLD', 'FDC', 'PRFT', 'APLE', 'PSMT', 'RUSHA', 'NVDA', 'XRAY', 'FNSR', 'BCR', 'CASH', 'ANH', 'KHC', 'PZZA', 'STOR', 'ECOL', 'COO', 'AAWW', 'LDOS', 'EQGP', 'CXP', 'RSG', 'OLLI', 'UCTT', 'PRLB', 'SCCO', 'WCC', 'CRTO', 'FIVE', 'KRO', 'ITC', 'YDKN', 'CHUY', 'KIM', 'ZTS', 'COMM', 'QSR', 'JJSF', 'NNN', 'ROLL', 'EXPO', 'FB', 'CZR', 'OCLR', 'EDU', 'AAON', 'LFUS', 'PSA', 'AIR', 'CDK', 'WNR', 'MLM', 'EPAM', 'RPM', 'SMTC', 'ISRG', 'GIMO', 'BMI', 'GK', 'JW.A', 'CWT', 'MWA', 'ATRI', 'PNRA', 'HOLX', 'SCMP', 'SNPS', 'PFGC', 'OCFC', 'TMUS', 'UDR', 'IBP', 'BKNG', 'HL', 'MENT', 'BIDU']},
	_2018_p0={'start_dt': '2018-01-01', 'end_dt': '2018-04-02', 'period': '0', 'tickers': ['SPG', 'GWR', 'VAR', 'SF', 'LANC', 'ORA', 'GEF', 'ALLE', 'BCR', 'COO', 'MTD', 'PBI', 'OMF', 'GPRE', 'ACLS', 'EFX', 'WDFC', 'EW', 'AYI', 'JBL', 'AXTI', 'SCCO', 'PRLB', 'NCR', 'ZTS', 'FICO', 'ANDX', 'FLR', 'BWLD', 'FIG', 'XNCR', 'A', 'TKR', 'H', 'PSA', 'SIRI', 'OPI', 'NLSN', 'HEI', 'MGI', 'EXPO', 'PPG', 'JW.A', 'THG', 'AHH', 'INTU', 'IBKR', 'RMD', 'KWR', 'OAK', 'ROP', 'COST', 'SATS', 'POOL', 'AZPN', 'SSP', 'UDR', 'CDK', 'ECOL', 'SJI', 'LVLT', 'CHH', 'ATGE', 'MAT', 'SNPS', 'MSCI', 'AKAM', 'K', 'JBT', 'CLI', 'PII', 'BMI', 'KHC', 'BKH', 'CBF', 'MYRG', 'SXT', 'MLM', 'PAGP', 'CTRE', 'PF', 'WST', 'WCC', 'OKE', 'TMUS', 'ROLL', 'BUFF', 'VTR', 'RSG', 'SCHL', 'BRKS', 'IRBT', 'JJSF', 'COMM', 'GNL', 'BETR', 'CTLT', 'NEWM', 'ABAX', 'NTAP']},
	_2018_p1={'start_dt': '2018-04-02', 'end_dt': '2018-07-02', 'period': '1', 'tickers': ['IEX', 'CLDT', 'VHI', 'BURL', 'VSH', 'TMO', 'GMS', 'VWR', 'V', 'CDK', 'A', 'OPI', 'SYK', 'TXRH', 'WPZ', 'CAB', 'TCS', 'CWT', 'MPC', 'K', 'FDC', 'KEX', 'CFX', 'OUT', 'DAR', 'XCRA', 'LHCG', 'GWR', 'ALLE', 'COMM', 'CAR', 'RPT', 'COST', 'VIVO', 'MKL', 'MYRG', 'DD1', 'NVDA', 'MAT', 'WCG', 'BUFF', 'GDOT', 'PETS', 'BIDU', 'MLM', 'SIRI', 'MAR', 'SJI', 'OSUR', 'HTLD', 'NTRI', 'WMS', 'GFF', 'SXT', 'AMBA', 'AET', 'OKE', 'RMD', 'IDTI', 'BNCL', 'TR', 'RSG', 'MSCI', 'WWW', 'BDC', 'WRD', 'ANDV', 'CERN', 'HR', 'PPBI', 'ROLL', 'WAB', 'INWK', 'ESS', 'ESQ', 'JJSF', 'PINC', 'GOOGL', 'FB', 'LVLT', 'AIV', 'XEC', 'COHR', 'GEL', 'BMI', 'FCFS', 'WRK', 'GOLF', 'CVX', 'HSY', 'EQGP', 'MTCH', 'ILMN', 'MC', 'ROP', 'WOOF', 'MRK', 'RPXC', 'MTSC', 'HEI']},
	_2018_p2={'start_dt': '2018-07-02', 'end_dt': '2018-10-01', 'period': '2', 'tickers': ['ASML', 'NTRI', 'LGF.B', 'COL', 'FRT', 'ACGL', 'TDG', 'A', 'CIGI', 'KAMN', 'AHH', 'MINI', 'BECN', 'EA', 'ABCO', 'WOW', 'CME', 'IEX', 'STOR', 'NI', 'EQGP', 'EW', 'SHW', 'RMD', 'JJSF', 'BLD', 'KEX', 'BRKR', 'LHCG', 'MYRG', 'DXPE', 'IPAR', 'PSA', 'BIDU', 'PGTI', 'CLDT', 'SXT', 'CLW', 'QCOM', 'DD', 'LMNX', 'JHG', 'AMBA', 'RLI', 'WERN', 'MCY', 'NEP', 'TMO', 'ARRS', 'MGM', 'ESS', 'MDCA', 'BUFF', 'NYT', 'GOOGL', 'PII', 'FOXF', 'EQR', 'FICO', 'HSY', 'CVCO', 'CC', 'FIVE', 'MA', 'FB', 'MTRN', 'ULTA', 'V', 'ASTE', 'GRA', 'COMM', 'FLS', 'CELG', 'IXYS', 'MC', 'BAX', 'ROCK', 'KEYS', 'DLTH', 'ZTS', 'AIV', 'CHSP', 'ORA', 'HR', 'MSCC', 'NS', 'BRKS', 'THG', 'JKHY', 'FWONA', 'MIC', 'ARGO', 'MSCI', 'CVX', 'JW.A', 'EXPO', 'GDOT', 'KMI', 'RE', 'COO']},
	_2018_p3={'start_dt': '2018-10-01', 'end_dt': '2018-12-31', 'period': '3', 'tickers': ['SHLM', 'LMNX', 'MED', 'SMCI', 'CTAS', 'BHLB', 'SON', 'MORN', 'ASML', 'GGG', 'MKC', 'NNN', 'NLSN', 'AMTD', 'ETSY', 'PH', 'HUBB', 'CMTL', 'AGCO', 'CDK', 'SYX', 'STOR', 'HSY', 'STE', 'PEB', 'AZN', 'AWR', 'CLH', 'UCBI', 'PPBI', 'CR', 'ELF', 'AET', 'ESIO', 'WDFC', 'PSA', 'MCRI', 'NTCT', 'CLDT', 'FCE.A', 'IBKC', 'WABC', 'AXP', 'MGPI', 'TEX', 'COO', 'CBPO', 'SCHW', 'TER', 'LITE', 'A', 'COHR', 'TMHC', 'RGC', 'FB', 'VMI', 'ELY', 'CFX', 'EA', 'WCN', 'IPAR', 'ENTA', 'CA', 'CL', 'RAVN', 'KAMN', 'DECK', 'LNCE', 'MTCH', 'BKS', 'SRNE', 'V', 'THRM', 'BC', 'BUFF', 'AHH', 'WES2', 'TCX', 'EXTN', 'IPGP', 'AXTI', 'SKX', 'APU', 'FRT', 'TREX', 'ISBC', 'SIR', 'HOME', 'NCR', 'REGN', 'HHC', 'FOXF', 'ITW', 'MAR', 'FBC', 'RES', 'LHX', 'GPN', 'KLXI', 'IIVI']},
	_2019_p0={'start_dt': '2019-01-01', 'end_dt': '2019-04-02', 'period': '0', 'tickers': ['CL', 'FLOW', 'IEX', 'NEPT', 'SKT', 'DVA', 'APD', 'BLBD', 'SPGI', 'AHH', 'TREX', 'UCBI', 'SKX', 'ETR', 'NTES', 'PEP', 'AVA', 'WDFC', 'ALV', 'HMSY', 'PAA', 'CR', 'WSO', 'PII', 'MAA', 'ACM', 'BR', 'PQG', 'MOG.A', 'PX', 'FHN', 'LHX', 'KAI', 'MMM', 'INFO', 'AVY', 'CLDT', 'PSMT', 'FDS', 'SJI', 'WMT', 'DPZ', 'SXI', 'OC', 'SHO', 'CBPO', 'SUPN', 'MAR', 'CTSH', 'BLL', 'GTES', 'ENLK', 'TPL', 'CLI', 'CORE', 'IRBT', 'GGP', 'AVP', 'TRI', 'TECD', 'AZN', 'YUMC', 'BKI', 'APEI', 'WTS', 'AMTD', 'ATRI', 'MED', 'IPGP', 'FOE', 'SSNC', 'AWK', 'IPAR', 'PRA', 'CATO', 'RAVN', 'AA', 'ASML', 'BC', 'MCY', 'CTRE', 'NAVG', 'FIVE', 'EQR', 'XPO', 'STL', 'URBN', 'VIVO', 'AUB', 'SHLM', 'EDR', 'PLAB', 'WELL', 'TER', 'EXLS', 'CVGI', 'ROLL', 'ADNT', 'REVG', 'GPN']},
	_2019_p1={'start_dt': '2019-04-02', 'end_dt': '2019-07-02', 'period': '1', 'tickers': ['SWM', 'NMRK', 'OUT', 'MCY', 'PCH', 'ESGR', 'IPGP', 'RYN', 'ASML', 'WTS', 'FDS', 'GDOT', 'SEP', 'SKY', 'CASS', 'TIF', 'CORE', 'TXRH', 'CTRE', 'AOS', 'HY', 'AVA', 'WW', 'IIVI', 'CFX', 'CTB', 'SCSC', 'TREX', 'MBUU', 'ALB', 'FHN', 'CCMP', 'DRH', 'ABCB', 'HELE', 'CPRT', 'PQG', 'ADP', 'NEWM', 'SPGI', 'PSA', 'BR', 'URBN', 'HALO', 'CTSH', 'UI', 'FLR', 'CA', 'AHH', 'GPN', 'ENB', 'AWK', 'CRAI', 'INFO', 'BCPC', 'PX', 'SLG', 'BKI', 'VMI', 'ATRI', 'XYL', 'IFF', 'WAB', 'JCOM', 'NTES', 'KAMN', 'OCFC', 'AIN', 'WDFC', 'FORM', 'PEP', 'FLO', 'XLNX', 'BSM', 'CNR', 'FRTA', 'AVY', 'MAA', 'VREX', 'FND', 'RBA', 'BANC', 'FRT', 'SRCL', 'LMT', 'INTU', 'UE', 'TPR', 'ROLL', 'MOD', 'NI', 'FIVE', 'KALU', 'CTRL', 'PTEN', 'PSMT', 'WDC', 'AWR', 'MDP', 'USNA']},
	_2019_p2={'start_dt': '2019-07-02', 'end_dt': '2019-10-01', 'period': '2', 'tickers': ['HSTM', 'RH', 'CLH', 'VVC', 'RMR', 'SUN', 'NEWM', 'VRSK', 'ENS', 'SEP', 'OKE', 'CDEV', 'FIZZ', 'AVB', 'WTS', 'RPT', 'GVA', 'AVY', 'BECN', 'NLSN', 'STE', 'ZBRA', 'RGNX', 'MXIM', 'FLO', 'CENX', 'HUM', 'ARE', 'DLTH', 'USCR', 'RPM', 'CNMD', 'CONN', 'ENTG', 'CTSH', 'WTTR', 'ALB', 'IOSP', 'NVEE', 'ONDK', 'TXRH', 'HHC', 'RBA', 'JCOM', 'CPRT', 'SIRI', 'MNRO', 'TREE', 'CTRE', 'PX', 'PEP', 'OUT', 'ANIK', 'WCG', 'MOG.A', 'LMT', 'HASI', 'FOE', 'IIVI', 'JKHY', 'TRU', 'LGND', 'SUP', 'LOGM', 'GPN', 'BDN', 'COST', 'WAB', 'BLL', 'LSI', 'WLTW', 'BJ', 'ATR', 'EBS', 'BWXT', 'FDS', 'EQH', 'HSIC', 'OCLR', 'CWST', 'USNA', 'SAM', 'ADP', 'SRC', 'CNC', 'LOCO', 'IBKR', 'TPB', 'QNST', 'BKNG', 'ETR', 'MNST', 'BR', 'AVAV', 'WDC', 'NBHC', 'SRCL', 'LOGI', 'MBUU', 'EEFT']},
	_2019_p3={'start_dt': '2019-10-01', 'end_dt': '2019-12-31', 'period': '3', 'tickers': ['PRFT', 'RPAI', 'ATR', 'CGNX', 'USG', 'PBF', 'PSMT', 'TMO', 'VNO', 'PSDO', 'TIF', 'SITE', 'SNPS', 'ADP', 'VRSN', 'FSLR', 'AIR', 'AON', 'DAR', 'HLF', 'IRT', 'AM', 'AMED', 'KO', 'JJSF', 'OFC', 'FDS', 'PJT', 'EXLS', 'PRGS', 'TTWO', 'DD', 'MRK', 'SRE', 'ALV', 'BCPC', 'ROLL', 'BG', 'DLB', 'CUBE', 'CME', 'PLCE', 'TRNO', 'STAG', 'QCOM', 'CBT', 'LANC', 'CLB', 'SHW', 'MA', 'CTLT', 'THRM', 'AKAM', 'WPX', 'OTEX', 'STE', 'MTN', 'JKHY', 'KFY', 'DCI', 'ARE', 'GPRE', 'BLL', 'WELL', 'KELYA', 'PQG', 'ANIP', 'IDCC', 'CF', 'NTES', 'KNSL', 'CWT', 'ADC', 'RYN', 'OSUR', 'WST', 'BABA', 'KRNY', 'GDOT', 'CDNS', 'NGVC', 'WRLD', 'HCSG', 'RPM', 'WCN', 'ARGO', 'WEX', 'EXPO', 'APC', 'RMD', 'GPN', 'FTNT', 'PKI', 'SAFM', 'WDFC', 'OSIS', 'MLNX', 'AVNS', 'WLDN', 'EQR']},
	_2020_p0={'start_dt': '2020-01-01', 'end_dt': '2020-04-02', 'period': '0', 'tickers': ['ROLL', 'KAMN', 'RBA', 'WRLD', 'WETF', 'CLDT', 'WAT', 'SBUX', 'VNOM', 'CRL', 'IPI', 'SEAS', 'EEFT', 'LVS', 'SCHL', 'EXR', 'MORN', 'AZPN', 'PSDO', 'DRE', 'KOP', 'HRC', 'IONS', 'TPB', 'VMI', 'CLGX', 'WPC', 'NR', 'OUT', 'RCII', 'CLB', 'CME', 'TNC', 'NSP', 'LRN', 'BANC', 'ALX', 'TTGT', 'AMED', 'HLT', 'TTWO', 'SAM', 'NEE', 'DLB', 'POWI', 'CZR', 'ROP', 'AVAV', 'KNSL', 'NKE', 'GMED', 'UCTT', 'ROG', 'AIMC', 'AXTA', 'UI', 'FOXF', 'AWK', 'BRKR', 'EL', 'DLTH', 'GMRE', 'AKAM', 'RMD', 'FLWS', 'HPE', 'HIW', 'LOW', 'ATR', 'MTD', 'VAR', 'SRE', 'NP', 'WH', 'PRFT', 'SWK', 'JJSF', 'AON', 'TITN', 'NJR', 'CABO', 'ECL', 'TMO', 'GTLS', 'THRM', 'MSA', 'ZTS', 'MANH', 'RPM', 'MGPI', 'STOR', 'FISV', 'GRA', 'SITE', 'CTRE', 'FND', 'WAB', 'RACE', 'CORE', 'TRMB']},
	_2020_p1={'start_dt': '2020-04-02', 'end_dt': '2020-07-02', 'period': '1', 'tickers': ['MANT', 'NKE', 'SM', 'COST', 'PLD', 'BABA', 'VFC', 'RTEC', 'DPZ', 'WES', 'ETRN', 'POOL', 'BF.B', 'IEX', 'TCPC', 'RLI', 'PCH', 'BR', 'QSR', 'NSP', 'KO', 'AVB', 'AMCR', 'AKAM', 'SAIC', 'JBT', 'CMP', 'WDFC', 'EXR', 'ADP', 'AMED', 'OSIS', 'CRL', 'BFS', 'XLNX', 'EXPE', 'Y', 'MKC', 'FR', 'MWA', 'AIMC', 'PSDO', 'SCPL', 'VMC', 'HIW', 'TPX', 'FDS', 'FB', 'ARES', 'AON', 'HRC', 'UNIT', 'AZPN', 'MNST', 'DLTH', 'MAR', 'NVDA', 'HOME', 'SWK', 'NJR', 'LRN', 'JJSF', 'EEFT', 'ROG', 'WBT', 'TMO', 'KW', 'FND', 'CLBK', 'CALM', 'CORE', 'CRVL', 'NCR', 'FLS', 'SHEN', 'COO', 'MSA', 'RAVN', 'XPER', 'ASML', 'KAMN', 'ROP', 'MIC', 'MTCH', 'NR', 'AMKR', 'QDEL', 'SMPL', 'WPC', 'AXTA', 'MMC', 'TDG', 'TREX', 'STOR', 'CLDT', 'CTRE', 'AVAV', 'MNRO', 'HASI', 'MGP']},
	_2020_p2={'start_dt': '2020-07-02', 'end_dt': '2020-10-01', 'period': '2', 'tickers': ['CPRT', 'IPHS', 'NVEE', 'SIRI', 'SKY', 'DRE', 'PLD', 'CHD', 'YUM', 'TNC', 'JCOM', 'PRGO', 'AON', 'ECHO', 'ODP', 'EPR', 'MANT', 'HMST', 'STOR', 'RLJ', 'PSEC', 'LOW', 'NKE', 'BR', 'CMPR', 'TDY', 'POOL', 'MKL', 'NDAQ', 'AZPN', 'ES', 'MSCI', 'MDT', 'FDP', 'MAR', 'ABM', 'OXY', 'MTD', 'PSDO', 'AMC', 'SNPS', 'CHE', 'BF.B', 'MGEE', 'ALX', 'ALV', 'TMO', 'BFS', 'ROP', 'TTEC', 'KW', 'SAIC', 'MEDP', 'RBA', 'ATR', 'MSA', 'INGN', 'MNRO', 'MKC', 'CLBK', 'CIM', 'BRKR', 'MTN', 'MSEX', 'CZR', 'GSKY', 'WELL', 'HLX', 'AKAM', 'AMED', 'FTNT', 'VMC', 'CMP', 'MCRN', 'SWK', 'LOB', 'CDEV', 'BAX', 'MGP', 'TITN', 'YETI', 'MMC', 'LE', 'NSSC', 'WSR', 'BMI', 'DLTH', 'IFF', 'QDEL', 'AVT', 'QRVO', 'OTEX', 'CHDN', 'THRM', 'UGI', 'TWNK', 'BGCP', 'ABBV', 'RAVN', 'ALGN']},
	_2020_p3={'start_dt': '2020-10-01', 'end_dt': '2020-12-31', 'period': '3', 'tickers': ['TTC', 'TWNK', 'WHD', 'MEDP', 'IFF', 'ST', 'ES', 'MDT', 'IBP', 'CMTL', 'ATVI', 'BMY', 'SAIC', 'KEYS', 'ATR', 'RHP', 'HAYN', 'STOR', 'IEX', 'MNST', 'VMC', 'VFC', 'COO', 'MTN', 'CRUS', 'EQR', 'TNC', 'EPR', 'RBA', 'PFGC', 'MSEX', 'CSV', 'NEE', 'ABMD', 'SPGI', 'MGEE', 'MCO', 'TDY', 'SEDG', 'ARMK', 'VRA', 'FB', 'MEET', 'NI', 'MLNX', 'MSI', 'ESI', 'AON', 'NKE', 'CHE', 'IAA', 'LBRT', 'ROLL', 'ARES', 'MMC', 'TUP', 'KDP', 'POOL', 'CKH', 'EXR', 'JRVR', 'MGP', 'STE', 'AZPN', 'CBPO', 'CMP', 'PXD', 'EHTH', 'DLB', 'MNRO', 'BR', 'TRIP', 'LFUS', 'CRVL', 'FND', 'EQM', 'WMB', 'CME', 'MKC', 'PSN', 'SXT', 'PE', 'NATI', 'IRM', 'GOOS', 'MGLN', 'TR', 'SPXC', 'MTD', 'VC', 'SIRI', 'CNNE', 'SHW', 'EXLS', 'HONE', 'COST', 'AVAV', 'PJT', 'TMO', 'CLBK']},
	_2021_p0={'start_dt': '2021-01-01', 'end_dt': '2021-04-01', 'period': '0', 'tickers': ['TEL', 'TTC', 'MSEX', 'MDT', 'PFGC', 'CHE', 'ALX', 'NNI', 'CUBE', 'EGOV', 'MTD', 'POOL', 'PAYS', 'FTV', 'MA', 'AES', 'IT', 'FORM', 'BURL', 'VRRM', 'NUAN', 'HNGR', 'MTN', 'BRKR', 'AKR', 'TWNK', 'RAVN', 'FDP', 'INFO', 'YETI', 'FUN', 'AAT', 'CPRT', 'ABMD', 'NKE', 'DIS', 'BMI', 'RGLD', 'FE', 'XYL', 'MTCH2', 'PRLB', 'INSW', 'WPC', 'JHG', 'EGP', 'TCX', 'TTWO', 'PRGO', 'ATRI', 'ADI', 'STAG', 'A', 'NEE', 'VFC', 'LRN', 'OTEX', 'EE', 'ADC', 'ESRT', 'LAKE', 'KEM', 'KRC', 'D', 'FLIR', 'AWK', 'EXP', 'CPT', 'AROC', 'RCM', 'ZTS', 'PLD', 'CLBK', 'SITE', 'WY', 'TSE', 'LHX', 'MORN', 'WTRG', 'WCN', 'RPAI', 'CVX', 'SWBI', 'AWR', 'O', 'NFG', 'BFAM', 'GNL', 'TR', 'ALRM', 'EW', 'DOC', 'EPAM', 'FIVE', 'PFC', 'ZYXI', 'TRU', 'CHEF', 'IPGP', 'MANH']},
	_2021_p1={'start_dt': '2021-04-01', 'end_dt': '2021-07-01', 'period': '1', 'tickers': ['QNST', 'ERIE', 'PSB', 'SHW', 'CTS', 'CRVL', 'VRSN', 'IAA', 'EXLS', 'ICHR', 'RAVN', 'PRGO', 'SPGI', 'EGOV', 'GOOGL', 'MEDP', 'KEYS', 'AIV', 'OLLI', 'CRL', 'FDS', 'LNC', 'IFF', 'KSS', 'LANC', 'KALU', 'CBT', 'BR', 'RMAX', 'STBA', 'ABB', 'GPK', 'QRVO', 'FE', 'RLI', 'JCI', 'PAHC', 'STE', 'AMRC', 'CIGI', 'IEX', 'JELD', 'RPM', 'PRFT', 'UBA', 'MNST', 'V', 'AKAM', 'ROK', 'STMP', 'MSEX', 'ATVI', 'EHTH', 'LMAT', 'CLBK', 'SYNH', 'HEI', 'DPZ', 'CUBE', 'TWNK', 'FORM', 'TDG', 'ALLE', 'CLH', 'WMS', 'MKC', 'VTR', 'NEE', 'APEI', 'GMS', 'ATRI', 'ETH', 'SXT', 'CTRE', 'NVEE', 'ROST', 'ODFL', 'ENTG', 'WPC', 'PSN', 'MIC', 'TJX', 'ADI', 'KDP', 'AWR', 'XLNX', 'TFX', 'SKX', 'INFO', 'IOSP', 'A', 'MSFT', 'SHEN', 'ESI', 'DRE', 'HRC', 'PKI', 'ENPH', 'SITC', 'AVAV']},
	_2021_p2={'start_dt': '2021-07-01', 'end_dt': '2021-09-30', 'period': '2', 'tickers': ['CHRW', 'AMRC', 'ALLE', 'GWW', 'HASI', 'MC', 'FWRD', 'CBPO', 'FAST', 'NXRT', 'KEYS', 'AMN', 'UBA', 'QSR', 'ACN', 'SCVL', 'CPRT', 'DORM', 'HOG', 'FSLR', 'FRT', 'EXR', 'WM', 'MEDP', 'STOR', 'AKAM', 'COG', 'DUK', 'TT', 'WGO', 'DPZ', 'AVB', 'BR', 'LSI', 'WRB', 'FDX', 'IP', 'VMW', 'ITGR', 'AIV', 'STZ', 'VRA', 'NPTN', 'EBS', 'NTGR', 'OLLI', 'ALX', 'ITT', 'KRC', 'MCD', 'CWH', 'ARI', 'EPRT', 'AWR', 'RGLD', 'AAPL', 'WRE', 'NDSN', 'ERIE', 'MSFT', 'MSI', 'RAVN', 'GGG', 'FLIR', 'ODFL', 'SHW', 'FUTU', 'IBP', 'TMO', 'WSO', 'PSA', 'BF.B', 'INFO', 'IFF', 'BRBR', 'CLCT', 'CTVA', 'NEE', 'ATR', 'APD', 'ATRI', 'DOYU', 'LMAT', 'ENTG', 'TR', 'COF', 'KNL', 'MNST', 'STE', 'HR', 'JOE', 'FDS', 'CRL', 'V', 'SPGI', 'PCH', 'LITE', 'ALRM', 'CGC', 'STBA']},
	_2021_p3={'start_dt': '2021-09-30', 'end_dt': '2021-12-31', 'period': '3', 'tickers': ['CHRW', 'SWKS', 'ENS', 'AMRC', 'ALLE', 'GWW', 'HASI', 'MC', 'FWRD', 'CBPO', 'FAST', 'NXRT', 'AMN', 'QSR', 'DLTH', 'FSLR', 'FRT', 'EXR', 'WM', 'MEDP', 'LE', 'STOR', 'AKAM', 'COG', 'DUK', 'TT', 'AVB', 'BR', 'LSI', 'WRB', 'IP', 'NUE', 'AIV', 'NPTN', 'EBS', 'ALX', 'ITT', 'KRC', 'MCD', 'CWH', 'ARI', 'EPRT', 'AWR', 'RGLD', 'WRE', 'QRVO', 'ERIE', 'MSFT', 'PKI', 'FLIR', 'ODFL', 'SHW', 'FUTU', 'IBP', 'WSO', 'PSA', 'IFF', 'BRBR', 'CLCT', 'CTVA', 'NEE', 'ATR', 'APD', 'ATRI', 'DOYU', 'LMAT', 'TR', 'COF', 'KNL', 'MNST', 'STE', 'HR', 'JOE', 'V', 'SPGI', 'ADI', 'RAVN', 'PCH', 'ALRM', 'NVEE', 'CGC', 'STBA', 'SCVL', 'SXT', 'PIPR', 'RMD', 'IEX', 'LANC', 'VRTU', 'ROIC', 'THRM', 'SSTK', 'CMPR', 'USPH', 'CRVL', 'SR', 'DLX', 'IPAR', 'RBA', 'PSN']},
)

# 39th day: high pe: 39 days: Num invs: 911; annualized return: -0.00: overall mean roi: 0.0018
# 29 days: Num invs: 3019; annualized return: 0.36: overall mean roi: 0.0036
# 19th day: high pe: 29 days: Num invs: 6000; annualized return: 0.43: overall mean roi: 0.0023
# 9 days: Num invs: 6000; annualized return: 0.09: overall mean roi: 0.0010
stock_dict_high_pe_p4 = dict(
	_2016_p0={'start_dt': '2016-01-01', 'end_dt': '2016-04-02', 'period': '0', 'tickers': ['FOR', 'DATA', 'HABT', 'WPZ', 'JOE', 'NRG', 'KRA', 'BGCP', 'MC', 'TVTY', 'FCB', 'OWW', 'CWEN', 'ETP', 'PE', 'NTGR', 'EGHT', 'SPSC', 'ASEI', 'MDSO', 'OSUR', 'COG', 'DPLO', 'FTNT', 'AVNS', 'DGI', 'POWL', 'BDN', 'EGRX', 'PCYC', 'SSP', 'SHLX', 'USG', 'LOGI', 'ENTG', 'CSGP', 'TRNO', 'PMCS', 'SEMG', 'MINI', 'OPI', 'BSFT', 'RATE', 'REMY', 'LOGM', 'ZLTQ', 'SUI', 'CUBE', 'AM2', 'PAYC', 'BEL', 'HW', 'TNGO', 'IBKR', 'PLAY', 'RKUS', 'RGEN', 'ENV', 'LGND', 'ENB', 'HAE', 'REGN', 'EXAM', 'BWXT', 'NYT', 'ADBE', 'NCMI', 'BDC', 'GRUB', 'ARE', 'MELI', 'EVHC', 'SSTK', 'PGNX', 'ATI', 'ULTI', 'RPAI', 'CYBR', 'MWE', 'EQY', 'WAGE', 'WCG', 'INN', 'NFLX', 'ZU', 'AVID', 'ACOR', 'FRSH', 'HCSG', 'WES', 'VMC', 'SUPN', 'OXSQ', 'EVRI', 'SEDG', 'ESS', 'HMSY', 'FWONA', 'AIR', 'ACAT']},
	_2016_p1={'start_dt': '2016-04-02', 'end_dt': '2016-07-02', 'period': '1', 'tickers': ['BKI', 'MWE', 'CSC', 'CLW', 'RDC', 'RENT', 'VRNT', 'ACAT', 'MGNX', 'INCY', 'EXAM', 'CSGP', 'WMS', 'ZOES', 'MTSI', 'CCO', 'MBLY', 'DOC', 'HSC', 'PCRX', 'HABT', 'ATHN', 'EGHT', 'OSUR', 'FTNT', 'BGCP', 'PMCS', 'WPZ', 'HES', 'IPXL', 'RPT', 'MDSO', 'RELYQ', 'DPLO', 'SPSC', 'ENOC', 'OLED', 'POWR', 'TGE', 'SYNH', 'CWEN', 'LQ', 'IONS', 'EPC', 'PRAH', 'NKTR', 'HHC', 'LXU', 'ENB', 'SHLX', 'ZLTQ', 'ATI', 'BDN', 'TVTY', 'RSE', 'NFLX', 'AVAV', 'PRGO', 'ADPTQ', 'FIT', 'GWRE', 'MINI', 'NPTN', 'LOGM', 'ARDX', 'KRNY', 'FNSR', 'PGNX', 'NLY', 'RGEN', 'ADSK', 'DGI', 'SUPN', 'STMP', 'BLDR', 'WWE', 'CVLT', 'HL', 'ZU', 'RBC', 'IPI', 'ACOR', 'NBHC', 'BEAV', 'RKUS', 'CUBE', 'ANF', 'RATE', 'HQY', 'SUM', 'ATML', 'WING', 'PAY', 'UIS', 'ANH', 'ULTI', 'AVD', 'REGN', 'ELY', 'PAYC']},
	_2016_p2={'start_dt': '2016-07-02', 'end_dt': '2016-10-01', 'period': '2', 'tickers': ['ISIL', 'PEN', 'NGL', 'XXIA', 'FNSR', 'REXR', 'BDBD', 'AMZN', 'SMTC', 'PRTY', 'CCOI', 'CG', 'ACOR', 'ZLTQ', 'BKI', 'CSC', 'VRNT', 'QDEL', 'GWRE', 'FTNT', 'USCR', 'BRC', 'SPGI', 'RENT', 'WES2', 'ATHN', 'IONS', 'SPSC', 'FCE.A', 'STC', 'OSUR', 'MXIM', 'NFLX', 'PE', 'STMP', 'HABT', 'WEB', 'PMCS', 'EXAM', 'VRTV', 'MTSI', 'RKUS', 'ATML', 'FTK', 'KW', 'THC', 'TKR', 'MSGN', 'ULTI', 'RAMP', 'MDSO', 'OI', 'KRNY', 'ELY', 'NBHC', 'MBLY', 'DTSI', 'SPLS', 'AVID', 'TGE', 'SUM', 'OLED', 'EGL', 'MINI', 'ALXN', 'DOC', 'PCRX', 'LOGM', 'LQ', 'STKL', 'ADPTQ', 'HQY', 'KRG', 'FWONA', 'DEL', 'RES', 'HAL', 'PAYC', 'IMMR', 'CUBE', 'BEAT', 'AXTA', 'GIMO', 'YHOO', 'BKH', 'FIT', 'ZBH', 'COMM', 'BLKB', 'RBC', 'RGEN', 'SUI', 'GPT', 'BCR', 'VSAT', 'CDR', 'BHC', 'INGN', 'SSNC', 'BETR']},
	_2016_p3={'start_dt': '2016-10-01', 'end_dt': '2016-12-31', 'period': '3', 'tickers': ['GERN', 'BSFT', 'INCY', 'PENN', 'PCRX', 'CIVI', 'MITT', 'FTI', 'TRU', 'TEAM', 'RAMP', 'SGRY', 'PEN', 'FTNT', 'YRCW', 'VRNT', 'REXR', 'EGRX', 'AMZN', 'SNCR', 'ISIL', 'INVN', 'ZOES', 'ATHN', 'NFLX', 'ULTI', 'ODP', 'GWRE', 'CCOI', 'MIME', 'ALXN', 'CIEN', 'SPLS', 'BKI', 'SPSC', 'MINI', 'PRGO', 'FCPT', 'ENV', 'RGLD', 'HABT', 'CSC', 'MDSO', 'FWONA', 'RKUS', 'MOMO', 'ORC', 'EXAM', 'MPSX', 'CXO', 'OLED', 'XXIA', 'ACOR', 'KRNY', 'PNM', 'WMS', 'NUE', 'SSNC', 'VIRT', 'GIMO', 'PRTY', 'KMI', 'BRC', 'UNVR', 'ZBH', 'PRE', 'KRG', 'AAWW', 'ATML', 'NBHC', 'MBLY', 'GPRE', 'HQY', 'CCRN', 'BLKB', 'NPTN', 'VSAT', 'LOGM', 'SIGM', 'SCU', 'DOC', 'IRC', 'ITRI', 'PAYC', 'HTA', 'CUB', 'BCR', 'OAK', 'HSC', 'RGEN', 'TVPT', 'EQT', 'EQIX', 'WES', 'EDR', 'QTS', 'GRPN', 'TYL', 'HASI', 'CAFD']},
	_2017_p0={'start_dt': '2017-01-01', 'end_dt': '2017-04-01', 'period': '0', 'tickers': ['TAST', 'QRVO', 'NLY', 'MIC', 'IART', 'SIGM', 'AMPH', 'CVLT', 'GERN', 'ACM', 'BSFT', 'CHS', 'SHOR', 'GLP', 'TEAM', 'DEL', 'FTNT', 'WES2', 'LC', 'KMI', 'CKEC', 'GWRE', 'ODP', 'OFG', 'NFLX', 'REXR', 'ULTI', 'PEN', 'CSGP', 'EQIX', 'MSGN', 'INCY', 'SSNC', 'MDRX', 'ZBH', 'RAMP', 'ATHN', 'SHAK', 'AMZN', 'TCP', 'PNM', 'RUN', 'UNVR', 'ALXN', 'SEAS', 'RKUS', 'BNED', 'TRU', 'KRG', 'HZNP', 'CCOI', 'EXAM', 'STMP', 'ECHO', 'OLED', 'VSAT', 'NXGN', 'NEM', 'DWA', 'NBHC', 'BKI', 'KRNY', 'DK', 'JOE', 'SPSC', 'CVX', 'MOMO', 'HABT', 'BCR', 'KATE', 'ETP', 'BID', 'DOC', 'VRNT', 'CIEN', 'ELLI', 'SE1', 'OAK', 'MDSO', 'PLNT', 'CPN', 'RAVN', 'SMTC', 'RGEN', 'PBF', 'SFLY', 'ANH', 'BLKB', 'HTA', 'UNIT', 'ABMD', 'CDR', 'TRGP', 'VIRT', 'NPTN', 'MITK', 'MBLY', 'LOGM', 'PRTY', 'BRC']},
	_2017_p1={'start_dt': '2017-04-01', 'end_dt': '2017-07-01', 'period': '1', 'tickers': ['IRDM', 'CVLT', 'DFT', 'VRNT', 'CHS', 'SEMG', 'RP', 'LQ', 'TEAM', 'BCO', 'DOOR', 'FTNT', 'ORC', 'MDRX', 'L', 'CCRN', 'STC', 'CKEC', 'KMI', 'NEM', 'PGRE', 'ATHN', 'STLD', 'CONE', 'MPSX', 'KRG', 'SSNC', 'DIOD', 'PNM', 'EQIX', 'ZOES', 'CUDA', 'CHCT', 'GWRE', 'FCS', 'GERN', 'IART', 'ULTI', 'LPX', 'PLNT', 'BSFT', 'NFLX', 'ALXN', 'WES2', 'SPH', 'LGF.B', 'DLR', 'PEN', 'MGP', 'MORE', 'SPSC', 'UNIT', 'INCY', 'DEA', 'BKH', 'CIEN', 'EGRX', 'DAKT', 'KHC', 'TCP', 'SHAK', 'TA', 'AMZN', 'EEP', 'VSAT', 'CIR', 'ACHN', 'TTWO', 'HOT', 'LNCE', 'MSGN', 'NUE', 'BMCH', 'UAN', 'TVPT', 'RAMP', 'DOC', 'CSGP', 'CCOI', 'MCHP', 'BKI', 'CRS', 'TRU', 'HONE', 'CLH', 'JOE', 'MDSO', 'LOGM', 'CDR', 'MUX', 'QTS', 'MITK', 'HSTM', 'ELLI', 'WAGE', 'HTA', 'RGEN', 'ABMD', 'GIMO', 'BLKB']},
	_2017_p2={'start_dt': '2017-07-01', 'end_dt': '2017-09-30', 'period': '2', 'tickers': ['PNM', 'PCH', 'CYTK', 'MTZ', 'TTWO', 'MTSI', 'FTNT', 'ELF', 'CUB', 'KRG', 'CREE', 'PGRE', 'UNIT', 'GKOS', 'MRT', 'BREW', 'BSX', 'SHPG', 'CHUBA', 'IRDM', 'EQIX', 'ULTI', 'LOGM', 'TISI', 'DFT', 'GWRE', 'MCHP', 'LGND', 'AIRG', 'ATHN', 'NFLX', 'NX', 'CRM', 'RAMP', 'COTY', 'ZOES', 'CVLT', 'MEDP', 'DEA', 'NVFY', 'TDC', 'CMPR', 'CPN', 'CONE', 'AOSL', 'BSFT', 'SPSC', 'SWC', 'LQ', 'TCP', 'LNCE', 'AMZN', 'AIG', 'SSP', 'CUDA', 'OMCL', 'CMG', 'PRGS', 'IRM', 'RP', 'JEF', 'AVAV', 'ASPS', 'KW', 'HSTM', 'PLNT', 'RGEN', 'SPH', 'BKI', 'CIR', 'MITK', 'GNCMA', 'DEL', 'SBAC', 'HAIN', 'VSAT', 'MBI', 'CKEC', 'SHAK', 'RAVN', 'BZUN', 'WAGE', 'MDSO', 'JOE', 'ABMD', 'ALRM', 'CCOI', 'TRNO', 'PEN', 'CIEN', 'TMH', 'KFY', 'QTS', 'CG', 'INCY', 'SHEN', 'DOC', 'HTA', 'FLTX', 'XXIA']},
	_2017_p3={'start_dt': '2017-09-30', 'end_dt': '2017-12-31', 'period': '3', 'tickers': ['MPLX', 'PEIX', 'ZLTQ', 'KRG', 'BSFT', 'SEMG', 'LOGM', 'KW', 'CC', 'TEVA', 'GWRE', 'CMG', 'ACHC', 'ECHO', 'HAWK', 'NTCT', 'RGLD', 'CVLT', 'TRP', 'SUI', 'ARRS', 'CUB', 'TTWO', 'CAMP', 'NFLX', 'WEB', 'SUM', 'ZOES', 'MYCC', 'IQV', 'GKOS', 'CRM', 'LNCE', 'ELF', 'SPSC', 'SALE', 'RMBS', 'TRCO', 'HSTM', 'OFIX', 'BIO', 'SWC', 'OFC', 'WEX', 'GTT', 'CG', 'EQIX', 'CALM', 'ATHN', 'RAMP', 'BZH', 'MORE', 'CONE', 'ICHR', 'INCY', 'ULTI', 'DEA', 'ANIP', 'BSM', 'NXPI', 'AXTA', 'SBAC', 'WAGE', 'LITE', 'FTNT', 'SHPG', 'MTSI', 'PCH', 'HPP', 'ITGR', 'VSAT', 'AMZN', 'SITC', 'RGS', 'SNCR', 'MCHP', 'ERII', 'RP', 'ORC', 'GPT', 'CHEF', 'PEN', 'KMPR', 'CKEC', 'HAYN', 'HAE', 'BKI', 'OMCL', 'ALRM', 'CCOI', 'TGE', 'TMH', 'PTHN', 'USCR', 'TRNO', 'GGG', 'VG', 'OII', 'CUDA', 'FLTX']},
	_2018_p0={'start_dt': '2018-01-01', 'end_dt': '2018-04-02', 'period': '0', 'tickers': ['CDEV', 'FANG', 'INFI', 'WMB', 'RAD', 'HLNE', 'PARR', 'EXEL', 'CWST', 'FPI', 'ALEX', 'RAMP', 'PEIX', 'IONS', 'SEMG', 'NX', 'GKOS', 'PCTY', 'JAKK', 'MRVL', 'ELF', 'BDN', 'CNSL', 'LGF.B', 'DECK', 'GWRE', 'IQV', 'PEN', 'YELP', 'MOS', 'FMC', 'ZAYO', 'HLT', 'ACHC', 'SBAC', 'MYCC', 'AFI', 'KW', 'STAG', 'BIO', 'ATHN', 'HSTM', 'RH', 'ANF', 'ULTI', 'SUI', 'QDEL', 'NFLX', 'RSPP', 'MLNX', 'SHPG', 'DGI', 'RMBS', 'AA', 'MUX', 'CYTK', 'CRM', 'CLNY', 'FTNT', 'AMZN', 'DEA', 'SEAS', 'TRTN', 'VSAT', 'ANIP', 'VRTX', 'BKS', 'GNBC', 'WEX', 'SPSC', 'TIVO', 'EQIX', 'PEGI', 'MHLD', 'HAYN', 'CMG', 'TRNO', 'SFLY', 'TGE', 'LRN', 'RP', 'IMAX', 'BKI', 'ALRM', 'VG', 'CCOI', 'CUDA', 'WRD', 'AIG', 'NPO', 'FOE', 'OLN', 'QTS', 'NODK', 'MBLY', 'OFC', 'HPP', 'REG', 'KMPR', 'AXTA']},
	_2018_p1={'start_dt': '2018-04-02', 'end_dt': '2018-07-02', 'period': '1', 'tickers': ['LYV', 'ENLC', 'YRCW', 'SOI', 'MLNX', 'EQT', 'AM', 'CNSL', 'LRN', 'CVLT', 'NCSM', 'DGI', 'CARB', 'AFI', 'ZOES', 'GCP', 'RAIL', 'TYPE', 'PEN', 'CAT', 'OMCL', 'SLB', 'BIO', 'CRCM', 'ACHC', 'GIMO', 'HAE', 'LBRDA', 'IQV', 'SBAC', 'GWRE', 'AR', 'OXY', 'DXC', 'PCTY', 'PDCE', 'FLOW', 'GDDY', 'VSAT', 'ARE', 'LGND', 'LAUR', 'SFLY', 'SEMG', 'GPT', 'CRAY', 'IT', 'MET', 'PSDO', 'AMPH', 'BEL', 'AMZN', 'PE', 'ALEX', 'EGL', 'WUBA', 'ULTI', 'CRM', 'FMC', 'SLCA', 'ESI', 'BDN', 'CLNY', 'RMBS', 'HSTM', 'ABM', 'NFLX', 'NTCT', 'ATHN', 'HLNE', 'EQIX', 'UIHC', 'CDEV', 'DEA', 'PXD', 'RRC', 'SGRY', 'SQBG', 'IMAX', 'HTA', 'BKI', 'X', 'YELP', 'REG', 'KRG', 'MDSO', 'WEX', 'QTS', 'SPSC', 'MITK', 'SUI', 'VIRT', 'EXEL', 'GPRE', 'VRTX', 'ELF', 'RRR', 'JELD', 'OLN', 'FOE']},
	_2018_p2={'start_dt': '2018-07-02', 'end_dt': '2018-10-01', 'period': '2', 'tickers': ['TYPE', 'CLDPQ', 'FARO', 'EOG', 'ASH', 'RH', 'CVLT', 'EXTN', 'AMH', 'AM', 'RNG', 'Y', 'PTC', 'LBRDA', 'ENLK', 'CLH', 'EPC', 'LOGM', 'IQV', 'PQG', 'KN', 'LYV', 'CRM', 'OFIX', 'FMC', 'PEGI', 'HAE', 'ENLC', 'SOI', 'GLT', 'BIO', 'CLNY', 'HRTG', 'SHEN', 'PE', 'EQT', 'CCRN', 'GWRE', 'APPF', 'QTNA', 'NR', 'PCTY', 'NEM', 'AMZN', 'HPE', 'NCSM', 'IMAX', 'OMCL', 'SYX', 'ASPS', 'ULTI', 'PXD', 'VRTX', 'AVGO', 'ZBRA', 'HAL', 'STRL', 'CCC1', 'DPLO', 'NFLX', 'SLB', 'LGND', 'SFLY', 'CAMP', 'NTCT', 'GDDY', 'SBAC', 'ANGO', 'BRCD', 'POST', 'DEA', 'GXP', 'ABM', 'CHCT', 'EXTR', 'MKL', 'ATHN', 'HTA', 'IMPV', 'YELP', 'ZAGG', 'EQIX', 'RMBS', 'INOV', 'BKI', 'CCOI', 'CUDA', 'ALEX', 'KW', 'HL', 'CDEV', 'ARE', 'LTRPA', 'KRG', 'ICUI', 'HSTM', 'PBPB', 'ETSY', 'QTS', 'UNVR']},
	_2018_p3={'start_dt': '2018-10-01', 'end_dt': '2018-12-31', 'period': '3', 'tickers': ['IONS', 'FTAI', 'WWW', 'RP', 'IT', 'SPSC', 'QTS', 'FLS', 'NSA', 'AM', 'KMI', 'MCRN', 'VIRT', 'MELI', 'SUM', 'PTEN', 'WAT', 'ABM', 'NYT', 'PEN', 'IMAX', 'ACIW', 'ULTI', 'CARG', 'BSIG', 'GRA', 'AVX', 'HLNE', 'IR', 'CCOI', 'GWRE', 'BSX', 'ZBRA', 'NCSM', 'QRVO', 'CONN', 'CRM', 'JNJ', 'AAXN', 'USM', 'TREE', 'ALB', 'SRCL', 'AMPH', 'FTNT', 'PTC', 'BCO', 'LGND', 'AQUA', 'VRTU', 'AXTA', 'RAMP', 'ORC', 'DEA', 'ABT', 'PCTY', 'GRPN', 'HSC', 'PLT', 'AMZN', 'SBAC', 'QGEN', 'ATGE', 'ATVI', 'EQC', 'HR', 'CRY', 'BDX', 'RH', 'OFIX', 'KO', 'EQIX', 'OPI', 'NFLX', 'BGFV', 'MTW', 'QNST', 'CCI', 'APPF', 'CHCT', 'VRTX', 'DD', 'NAV', 'SIEB', 'KRG', 'VRA', 'DLR', 'PUMP', 'COG', 'CWH', 'ZNGA', 'FTI', 'CAT', 'WRE', 'STAG', 'HELE', 'CASA', 'INGN', 'GLT', 'VER']},
	_2019_p0={'start_dt': '2019-01-01', 'end_dt': '2019-04-02', 'period': '0', 'tickers': ['ANIP', 'CROX', 'HR', 'CASA', 'WP', 'CARB', 'SPSC', 'SHAK', 'KRNT', 'TWTR', 'GCI', 'RP', 'TNC', 'CWEN', 'GDEN', 'FRTA', 'BCO', 'JEF', 'SFIX', 'NEM', 'UNIT', 'WAT', 'AVX', 'IMBI', 'WHD', 'VSH', 'ANGO', 'GLT', 'SOI', 'MCK', 'NEWM', 'SPKE', 'FPI', 'CARG', 'DCP', 'NXGN', 'RGS', 'NR', 'GRA', 'MSTR', 'BSX', 'FTAI', 'JD', 'NYT', 'KMI', 'PEN', 'SNPS', 'CMPR', 'ICUI', 'JNJ', 'ULTI', 'NAV', 'PTC', 'CCOI', 'CRM', 'IIPR', 'VICR', 'ABT', 'ATGE', 'SBAC', 'NTGR', 'ANF', 'DEA', 'NFLX', 'VRTX', 'MAC', 'BG', 'AMZN', 'SRE', 'AXTA', 'MTRX', 'CCI', 'CONN', 'CIVI', 'AM', 'NSA', 'QDEL', 'AAXN', 'ATVI', 'FTNT', 'ENV', 'DPLO', 'WDC', 'QGEN', 'VNO', 'CTXS', 'WRE', 'EQIX', 'KO', 'CHUBA', 'MMSI', 'TRGP', 'MLNX', 'A', 'CYBR', 'OPI', 'AMD', 'ADTN', 'CWH', 'IMAX']},
	_2019_p1={'start_dt': '2019-04-02', 'end_dt': '2019-07-02', 'period': '1', 'tickers': ['ANIP', 'GLT', 'IDTI', 'MYE', 'ACIW', 'NXGN', 'CARB', 'RP', 'JAG', 'TRC', 'VNDA', 'CLBK', 'GRA', 'SHAK', 'SMLP', 'CSII', 'SBAC', 'DPLO', 'GHDX', 'COLD', 'HAL', 'STAA', 'LASR', 'DNOW', 'CY', 'GME', 'HAIN', 'KRNT', 'ADNT', 'MAC', 'SPSC', 'WAT', 'GDEN', 'HR', 'ATI', 'AMBA', 'VRNT', 'BMY', 'FTAI', 'JNJ', 'AJRD', 'CCOI', 'CUB', 'IMBI', 'EPAY', 'ULTI', 'HAE', 'UNIT', 'NYT', 'PTC', 'PCG', 'MCHP', 'NSA', 'DEA', 'NFLX', 'AAXN', 'PEN', 'WHD', 'HBI', 'NTAP', 'DLB', 'TCMD', 'HUD', 'VNO', 'CTXS', 'LXP', 'ACB', 'TWTR', 'CCI', 'CEVA', 'IT', 'TFX', 'NEM', 'SNPS', 'MMSI', 'ENV', 'AMZN', 'VICR', 'HSKA', 'HRTG', 'CRM', 'LOCO', 'WRE', 'EQIX', 'ONDK', 'INGN', 'QDEL', 'MRK', 'INXN', 'RXN', 'RGS', 'FTNT', 'APPF', 'ABT', 'ATVI', 'DLR', 'HLNE', 'AQUA', 'CYBR', 'ABMD']},
	_2019_p2={'start_dt': '2019-07-02', 'end_dt': '2019-10-01', 'period': '2', 'tickers': ['SAIL', 'CSCO', 'CSII', 'MOV', 'ANIP', 'DBI', 'NBIX', 'CXP', 'RP', 'CMPR', 'GES', 'MCHP', 'HSKA', 'DPLO', 'SHAK', 'PEN', 'STAA', 'FRAN', 'CEVA', 'BDX', 'JELD', 'HBI', 'AYX', 'AQUA', 'IDTI', 'GHL', 'TRIP', 'WOW', 'DXCM', 'FDP', 'NYT', 'HAE', 'MUR', 'WAT', 'LLY', 'ATGE', 'SSP', 'EHTH', 'EPAY', 'PTC', 'JNJ', 'SNPS', 'CARB', 'ACIW', 'HR', 'MCK', 'UNIT', 'HAL', 'NXGN', 'ALXN', 'XRX', 'ULTI', 'BLFS', 'TCMD', 'ALRM', 'DEA', 'JD', 'TFX', 'JBGS', 'PCG', 'SPSC', 'DLB', 'CMP', 'CCOI', 'OFIX', 'NEO', 'CUB', 'AAXN', 'WTM', 'NUVA', 'NSA', 'IPI', 'KRNT', 'FRGI', 'ABT', 'PLXS', 'GCI', 'PEGA', 'FNKO', 'GHDX', 'APPF', 'FTNT', 'NFLX', 'INXN', 'INGN', 'CCI', 'BEAT', 'ZNGA', 'CBMB', 'CTXS', 'WWE', 'ENV', 'AA', 'NTCT', 'MPAA', 'GDDY', 'CARG', 'ATVI', 'AMZN', 'HOME']},
	_2019_p3={'start_dt': '2019-10-01', 'end_dt': '2019-12-31', 'period': '3', 'tickers': ['AXS', 'CONE', 'HP', 'EHTH', 'SONO', 'WP', 'PODD', 'GNL', 'PDCE', 'SYNA', 'CEVA', 'CVLT', 'SMG', 'PEN', 'ATUS', 'CSII', 'SUM', 'SAIL', 'PZZA', 'SWCH', 'NSA', 'ENV', 'SBAC', 'RGS', 'PEGA', 'BECN', 'UNIT', 'CATM', 'PGRE', 'ACIA', 'NBIX', 'MEET', 'ALXN', 'STAA', 'MTLS', 'CAMP', 'AMH', 'APA', 'CXP', 'Y', 'ADSW', 'ZNGA', 'PAAS', 'EIGI', 'NUVA', 'BEP', 'VRTU', 'NEO', 'CWST', 'TERP', 'LBRDA', 'AEGN', 'QTNA', 'SMLP', 'VEAC', 'SYNH', 'DEA', 'PTC', 'ICUI', 'TPIC', 'CSCO', 'TDC', 'GDDY', 'BB', 'FARO', 'RGEN', 'SCHL', 'OSPN', 'SJI', 'ELAN', 'EPAY', 'RP', 'AYX', 'QRVO', 'TCMD', 'BRK.B', 'ALTR', 'INCY', 'ULTI', 'GCP', 'ALRM', 'CARB', 'HSKA', 'RHT', 'CRM', 'INXN', 'HAE', 'KLXE', 'SHAK', 'JBGS', 'SSNC', 'ANGI', 'NXGN', 'RCII', 'MAC', 'APPF', 'RE', 'ELLI', 'CWH', 'NFLX']},
	_2020_p0={'start_dt': '2020-01-01', 'end_dt': '2020-04-02', 'period': '0', 'tickers': ['FTAI', 'VFF', 'CAH', 'NSA', 'ADSW', 'CRSA', 'CRY', 'UAA', 'PTC', 'CEVA', 'NAVG', 'PRMW', 'MTRX', 'KTOS', 'CVLT', 'ALTR', 'CSII', 'MCK', 'GOOD', 'SWCH', 'TROX', 'SBAC', 'HPP', 'BECN', 'PEN', 'AMPH', 'PODD', 'INVH', 'GNL', 'FE', 'NEO', 'BKS', 'PETQ', 'EIGI', 'DEA', 'SYNH', 'PGRE', 'STAA', 'ELAN', 'CWEN', 'WP', 'OPI', 'RXN', 'LBRDA', 'FORR', 'CXP', 'VG', 'MTLS', 'CUB', 'TAST', 'PCRX', 'LITE', 'CMO', 'UNIT', 'GWRE', 'AMH', 'CWST', 'MRT', 'TDC', 'ULTI', 'ANGO', 'ARWR', 'AYX', 'QTNA', 'CHCT', 'FARO', 'RP', 'ENR', 'DAR', 'ALRM', 'CATM', 'GDDY', 'INXN', 'BLKB', 'XPER', 'EYE', 'CNNE', 'SHAK', 'HSKA', 'SM', 'HABT', 'AAXN', 'APPF', 'VRTU', 'BEP', 'LMNX', 'MNR', 'GCI', 'AXS', 'WRE', 'EPAY', 'NFLX', 'RGEN', 'ATUS', 'TCMD', 'SSNC', 'CONE', 'MGLN', 'MLAB', 'AVNS']},
	_2020_p1={'start_dt': '2020-04-02', 'end_dt': '2020-07-02', 'period': '1', 'tickers': ['ZM', 'QTS', 'WY', 'NOW', 'LYV', 'MNRL', 'MELI', 'ALTR', 'HPP', 'UNVR', 'NEO', 'GOOD', 'GSX', 'TH', 'SWCH', 'STRA', 'NEWM', 'GLUU', 'VIAV', 'WMB', 'CEVA', 'FBM', 'GSHD', 'MYGN', 'CVLT', 'NBIX', 'COKE', 'VG', 'PODD', 'PEN', 'CDAY', 'SSYS', 'CRY', 'SYNH', 'EHTH', 'EZPW', 'FSLR', 'CAMP', 'HSKA', 'GRUB', 'WRE', 'LBRDA', 'BAND', 'SRDX', 'AAXN', 'GRPN', 'PCRX', 'BV', 'AYX', 'COLD', 'SFLY', 'PETQ', 'GDDY', 'FLEX', 'WAGE', 'CHCT', 'EPAY', 'SBAC', 'NTGR', 'TDC', 'ENPH', 'ADTN', 'KTOS', 'KLXE', 'AMD', 'STAA', 'EYE', 'PBF', 'INVH', 'LOGM', 'SBRA', 'SHAK', 'VREX', 'TEX', 'TREE', 'PAYS', 'BLKB', 'DEA', 'GWRE', 'RGEN', 'JYNT', 'LNN', 'LASR', 'AIR', 'NFLX', 'HABT', 'GNL', 'SLAB', 'WING', 'SFUN', 'UAA', 'MGLN', 'INXN', 'RP', 'LTRPA', 'WP', 'CARS', 'IQV', 'TCMD', 'MDSO']},
	_2020_p2={'start_dt': '2020-07-02', 'end_dt': '2020-10-01', 'period': '2', 'tickers': ['ATNI', 'ZM', 'GO', 'RRR', 'LASR', 'LYV', 'NOW', 'GRUB', 'MGM', 'NEO', 'PCRX', 'EBS', 'CRY', 'PODD', 'ADSK', 'AYX', 'SWCH', 'BAND', 'LBRDA', 'SBRA', 'ELF', 'LNN', 'SCU', 'AGX', 'GWRE', 'GSHD', 'NBIX', 'EHTH', 'MNRL', 'SSTI', 'PDLI', 'CVA', 'TREE', 'FOSL', 'TACO', 'DEA', 'TDC', 'RUN', 'PLMR', 'QTS', 'COLD', 'LOGM', 'CWST', 'BLKB', 'ETRN', 'AAXN', 'WETF', 'MGLN', 'CHCT', 'SBAC', 'SLAB', 'EPAY', 'WMB', 'FOCS', 'AMK', 'EYE', 'SHAK', 'IDCC', 'PBFS', 'RGEN', 'PGRE', 'NPO', 'JBGS', 'HTA', 'BEP', 'HR', 'AMD', 'HSKA', 'NTGR', 'AMEH', 'ARE', 'LCI', 'KTOS', 'UFCS', 'RPT', 'KRUS', 'RP', 'INVH', 'WEX', 'STAA', 'DLR', 'WING', 'KLIC', 'CRM', 'MNR', 'BB', 'IQV', 'ZNGA', 'VIAV', 'CLGX', 'HPP', 'INXN', 'WWE', 'FWONA', 'TAL', 'REXR', 'CORR', 'LSCC', 'FIS', 'ELAN']},
	_2020_p3={'start_dt': '2020-10-01', 'end_dt': '2020-12-31', 'period': '3', 'tickers': ['CWK', 'CEVA', 'CIIC', 'VSAT', 'AAXN', 'ELF', 'ZM', 'PRA', 'ALUS', 'SUM', 'SFTW', 'QTS', 'DRQ', 'ONTO', 'PODD', 'F', 'PRMW', 'BAND', 'CRY', 'FDX', 'DOYU', 'GSHD', 'EPAY', 'SWCH', 'AIR', 'PEAK', 'INOV', 'NEO', 'SONO', 'PNTG', 'WTTR', 'ENR', 'BANC', 'BLKB', 'MMSI', 'SWI', 'TAL', 'FIS', 'NBIX', 'AMG', 'CXP', 'SLAB', 'DEA', 'GBDC', 'COKE', 'AYX', 'MLAB', 'RGEN', 'DAVA', 'TREE', 'ADSK', 'VRT', 'CY', 'HTA', 'BKR', 'FOE', 'UEIC', 'DXCM', 'NTCT', 'CSTL', 'CVA', 'GO', 'LBRDA', 'GSX', 'UNIT', 'CRM', 'SBAC', 'CONE', 'HOLX', 'COHR', 'SSTI', 'ELAN', 'MNRL', 'IQV', 'BCO', 'KTOS', 'AMD', 'OPRT', 'BIDU', 'NXPI', 'GMRE', 'BRBR', 'COLD', 'ZNGA', 'HPP', 'CDK', 'VICR', 'HPK', 'FWONA', 'GKOS', 'VFF', 'GPN', 'ATUS', 'KRNT', 'REX', 'CDAY', 'WING', 'TW', 'ANIP', 'ANGI']},
	_2021_p0={'start_dt': '2021-01-01', 'end_dt': '2021-04-01', 'period': '0', 'tickers': ['PAAS', 'SVC', 'WTM', 'PODD', 'LPX', 'GSHD', 'PZZA', 'IPI', 'CRM', 'AYX', 'ZM', 'NEO', 'NVCR', 'MLAB', 'CDK', 'CEVA', 'FIS', 'XHR', 'SWCH', 'CLW', 'ATRS', 'SWI', 'ARWR', 'VAC', 'HPK', 'KRMD', 'EGRX', 'RDNT', 'VICR', 'RGEN', 'CUB', 'ADSK', 'DEA', 'INOV', 'OPI', 'PTC', 'VIAV', 'KRNT', 'KTOS', 'DXCM', 'ANGI', 'CINF', 'LBRDA', 'BLKB', 'FOCS', 'BCO', 'HTA', 'MGP', 'PEN', 'SSTI', 'IART', 'Y', 'UFS', 'VRNT', 'CMD', 'CNSL', 'BMRN', 'BMY', 'ESGR', 'WMB', 'GO', 'CXP', 'DAVA', 'HQY', 'ORI', 'MTCH', 'AMD', 'APPF', 'BGCP', 'STAA', 'SMTC', 'GMRE', 'FRTA', 'NPTN', 'SUI', 'EQIX', 'WING', 'VREX', 'XRAY', 'CCOI', 'BIDU', 'SHAK', 'FC', 'RUN', 'PPD', 'ZNGA', 'HR', 'IQV', 'RP', 'CDAY', 'SAFM', 'TCMD', 'NXPI', 'GPN', 'UNVR', 'AMZN', 'NXGN', 'SFIX', 'CCI', 'FOE']},
	_2021_p1={'start_dt': '2021-04-01', 'end_dt': '2021-07-01', 'period': '1', 'tickers': ['ADSW', 'DDOG', 'CHGG', 'CNMD', 'ONTO', 'TEVA', 'BOOM', 'COLL', 'FIS', 'PAAS', 'BHE', 'TRUP', 'GSHD', 'FRPT', 'CRS', 'ZM', 'PODD', 'ZBH', 'SAIL', 'STZ', 'PEN', 'LEVI', 'UNVR', 'TSLA', 'MIME', 'CEVA', 'RPAI', 'CVLT', 'NVCR', 'WYND', 'LOGM', 'OPES', 'CELH', 'ENTA', 'CONE', 'HLT', 'SWCH', 'VICR', 'KTOS', 'PPD', 'MTCH', 'CBRL', 'GSX', 'ANGI', 'DBX', 'INOV', 'LCA', 'AMPH', 'GRWG', 'NSA', 'DEA', 'CRSP', 'VREX', 'PRPL', 'BURL', 'PZZA', 'SLAB', 'RGEN', 'IQV', 'NTCT', 'KMI', 'SAMA', 'FOCS', 'SOI', 'NS', 'DXCM', 'BMRN', 'HTA', 'APPF', 'EQH', 'WMB', 'SWI', 'DAVA', 'LPX', 'AIR', 'KKR', 'TTD', 'EXPI', 'CDAY', 'SQ', 'BDSI', 'PLNT', 'GMRE', 'SPWR', 'ATEN', 'WBT', 'PCH', 'PPBI', 'WING', 'ARCC', 'FLGT', 'ADSK', 'LMNX', 'GPN', 'ECHO', 'NXGN', 'SMTC', 'YNDX', 'BCO', 'ARES']},
	_2021_p2={'start_dt': '2021-07-01', 'end_dt': '2021-09-30', 'period': '2', 'tickers': ['CEVA', 'HPE', 'POST', 'CNMD', 'VCEL', 'ESRT', 'SBE', 'TAL', 'LNTH', 'EPAC', 'TRN', 'CYBR', 'RUN', 'CDAY', 'FRPT', 'PLNT', 'PRPL', 'PGNY', 'MSTR', 'ONTO', 'INOV', 'TSLA', 'ANGI', 'SHOP', 'PTON', 'NVCR', 'OSPN', 'EYE', 'GSHD', 'PODD', 'LCA', 'KTOS', 'PMT', 'KWR', 'NVST', 'NUAN', 'VICR', 'DAVA', 'STAA', 'MTCH', 'ZM', 'ROG', 'USX', 'VITL', 'CELH', 'SWCH', 'PPD', 'SQ', 'PII', 'KMI', 'GRWG', 'PAAS', 'VRRM', 'GSKY', 'JBGS', 'GRA', 'MIME', 'FOCS', 'AVTR', 'HEES', 'ENBL', 'OSTK', 'GLUU', 'RGEN', 'VRNT', 'TTD', 'IQV', 'DXCM', 'MAR', 'HTA', 'HALO', 'KRG', 'SWI', 'DEA', 'OESX', 'HPP', 'EQIX', 'MOR', 'CMG', 'DT', 'CMD', 'EEFT', 'ADSK', 'SLAB', 'ATUS', 'CCOI', 'PLMR', 'REG', 'PCTY', 'WEX', 'PNTG', 'CR', 'AMPH', 'JJSF', 'NOW', 'WCN', 'HAIN', 'BFAM', 'EL', 'CWEN']},
	_2021_p3={'start_dt': '2021-09-30', 'end_dt': '2021-12-31', 'period': '3', 'tickers': ['CEVA', 'POST', 'CNMD', 'VCEL', 'ESRT', 'SBE', 'CAAS', 'LNTH', 'TRN', 'CYBR', 'SAMA', 'RUN', 'CDAY', 'KAMN', 'FRPT', 'PLNT', 'RMG', 'PRPL', 'PGNY', 'FSR', 'MSTR', 'INOV', 'TSLA', 'ANGI', 'SHOP', 'PTON', 'NVCR', 'OSPN', 'GSHD', 'PODD', 'LCA', 'PMT', 'KWR', 'ACAM', 'SMMC', 'NUAN', 'VICR', 'DAVA', 'RPLA', 'MTCH', 'SLAB', 'ZM', 'ROG', 'USX', 'STAA', 'CELH', 'SWCH', 'PPD', 'MOG.A', 'GXGX', 'SQ', 'PII', 'KMI', 'GRWG', 'PAAS', 'VRRM', 'GSKY', 'JBGS', 'GRA', 'MIME', 'FOCS', 'AVTR', 'HEES', 'ENBL', 'OSTK', 'GLUU', 'RGEN', 'TTD', 'IQV', 'DXCM', 'MAR', 'HTA', 'HALO', 'KRG', 'AOSL', 'SWI', 'DEA', 'OESX', 'TMX', 'HPP', 'EQIX', 'THCB', 'CMG', 'DT', 'EEFT', 'ATUS', 'CCOI', 'PLMR', 'REG', 'PCTY', 'WEX', 'PNTG', 'CR', 'AMPH', 'NOW', 'WCN', 'HAIN', 'BFAM', 'EL', 'CWEN']},
)

# NOTE: 2021-09-16: chris.flesche: 250k volume on NYSE and NASDAQ; highest percent price change in last month. Check this in October.
big_change = {
	"_2021_p0": {'start_dt': '2021-10-01', 'end_dt': '2021-10-16', 'period': '0',
				 "tickers": ["GREE", "CEI", "BBIG", "ATER", "TRIL", "EEIQ", "RGC", "OG", "LIFE", "UROY", "AEHR", "FCUV", "SGMA", "DATS", "ADGI", "OPAD", "KPLT",
							 "EFTR", "MTL", "RCMT", "KDMN",
							 "AFRM", "ISEE", "NNA", "ARQQ", "URG", "TASK", "UEC", "ITMR", "LPI", "LWLG", "UUUU", "BTCM", "VLON", "BLU", "IPHA", "GRTS", "ENVB"]}
}

# NOTE: 2021-10-05: chris.flesche: Based on prev year 2020 in Sept
# 39th day: low evebitda:
# 29th day: low evebitda:
test_stock_dict_low_evebitda_sept = dict(
	_2021_p0={'start_dt': '2021-09-01', 'end_dt': '2021-09-30', 'period': '0', 'tickers': ['QUOT', 'RNG', 'SDC', 'FEAC', 'HUBS', 'MNCL', 'MODN', 'OAC', 'AGNC', 'HYAC', 'ROKU', 'BYND', 'TDOC', 'ZG', 'PEN', 'RDFN', 'SITM', 'TCMD', 'WTRE', 'HCAC', 'PENN', 'ALGT', 'STAR', 'BYFC', 'FVRR', 'AVLR', 'AWI', 'SPOT', 'AAXN', 'SRCL', 'AMTX', 'LFAC', 'BDC', 'NET', 'WMG', 'CHEF', 'CNTY', 'SDGR', 'FSLY', 'OPES', 'BILL', 'TNDM', 'MUR', 'LMPX', 'TRNE', 'CMO', 'EVER', 'IRTC', 'DMYT', 'NLY', 'UPWK', 'WKHS', 'TEAM', 'TRHC', 'NEWR', 'APPN', 'SHOO', 'CDNA', 'AMRN', 'DK', 'TWLO', 'ZEN', 'EVBG', 'PDFS', 'BLFS', 'EFC', 'MXL', 'CYRX', 'MSGS', 'CVLT', 'TXG', 'EXTR', 'DKNG', 'MDP', 'GNMK', 'QTWO', 'PDD', 'CCXI', 'WIX', 'SVMK', 'PLUG', 'PDCE', 'INCY', 'CSII', 'GPMT', 'HLIT', 'RPD', 'NFE', 'NVRO', 'PEGA', 'PINS', 'HSII', 'GPRE', 'TRS', 'SILK', 'WK', 'OPRX', 'IMAX', 'LASR', 'GH']},
)
